In [ ]:
import pandas as pd
import re
import pymorphy3
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation, NMF, TruncatedSVD
from gensim import corpora
from gensim.models import LdaModel, Nmf

import warnings
warnings.filterwarnings('ignore')

In [49]:
train_df = pd.read_parquet(r'..\lab_5\train.parquet', engine='fastparquet')[:2000]
test_df = pd.read_parquet(r'..\lab_5\test.parquet', engine='fastparquet')

train_df

,text,summary,topic,url,title,date
0,Сладострастник в течение трех лет преследовал ...,Старший преподаватель института коммунального ...,incident,https://www.mk.ru/incident/article/2010/01/05/...,Педофил преследовал подростка три года,06/01/2010
1,Буквально за час до боя курантов в подземном п...,Манежная площадь Москвы стала местом последнег...,incident,https://www.mk.ru/incident/article/2010/01/05/...,Таджики устроили резню на Манежной площади под...,06/01/2010
2,"Там они покатались на лыжах и снегоходах, пооб...",Президент РФ Дмитрий Медведев с семьей проводи...,politics,https://www.mk.ru/politics/article/2010/01/05/...,"""""""За все платит президент""""""",06/01/2010
3,Сосед расстрелял соседа из-за претензий по пов...,Первое убийство в 2010 году произошло в Москве...,incident,https://www.mk.ru/incident/article/2010/01/05/...,Первое убийство года спровоцировал потоп,06/01/2010
4,Причиной трагедии специалисты считают нарушени...,"Шесть человек, в том числе 9-летний ребенок, з...",incident,https://www.mk.ru/incident/article/2010/01/05/...,Целая семья не пережила газовой атаки,06/01/2010
...,...,...,...,...,...,...
1995,"Скачка закончилась, а безусловный победитель т...",Как итоги выборов в туманном Альбионе могут от...,politics,https://www.mk.ru/politics/article/2010/05/07/...,Британия на весах,08/05/2010
1996,.Сводный оркестр — поистине белая кость военно...,Главный военный дирижер Валерий Халилов раскры...,politics,https://www.mk.ru/politics/interview/2010/05/0...,Победа в темпе марша. АУДИО,08/05/2010
1997,Эту горькую правду знает весь Междуреченск. Зд...,"Массовая гибель шахтеров не несчастный случай,...",incident,https://www.mk.ru/incident/article/2010/05/10/...,Распад начался не с “Распадской”. ВИДЕО,11/05/2010
1998,8 мая президент Медведев поставил свою подпись...,О последствиях реформы бюджетной сферы не знаю...,politics,https://www.mk.ru/politics/article/2010/05/10/...,В России вводят сырой закон,11/05/2010
1999,Учительница истории Плетнева рассказала собрав...,Памятник вождю в Тамбове поставил бизнесмен — ...,editions,https://www.mk.ru/editions/daily/article/2010/...,Сталин стал запчастью истории. ФОТО,11/05/2010

In [50]:
def preprocess_text(text, morph_analyzer, stop_words, min_word_len=3):
    if not isinstance(text, str) or not text.strip():
        return ""
    
    text = text.lower()
    text = re.sub(r'[^a-zа-яё\s]', ' ', text)
    tokens = word_tokenize(text)
    
    filtered_tokens = []
    for token in tokens:
        if len(token) < min_word_len or token in stop_words:
            continue
        
        parsed = morph_analyzer.parse(token)[0]
        normal_form = parsed.normal_form
        if len(normal_form) >= min_word_len and normal_form not in stop_words:
            filtered_tokens.append(normal_form)
    
    return ' '.join(filtered_tokens)


morph = pymorphy3.MorphAnalyzer()
stop_words = set(stopwords.words('russian'))

train_df['processed_text'] = train_df['text'].apply(
    lambda x: preprocess_text(x, morph, stop_words, min_word_len=3)
)
test_df['processed_text'] = test_df['text'].apply(
    lambda x: preprocess_text(x, morph, stop_words, min_word_len=3)
)

train_df = train_df[train_df['processed_text'].str.len() > 0]
test_df = test_df[test_df['processed_text'].str.len() > 0]

train_df

,text,summary,topic,url,title,date,processed_text
0,Сладострастник в течение трех лет преследовал ...,Старший преподаватель института коммунального ...,incident,https://www.mk.ru/incident/article/2010/01/05/...,Педофил преследовал подростка три года,06/01/2010,сладострастник течение год преследовать подрос...
1,Буквально за час до боя курантов в подземном п...,Манежная площадь Москвы стала местом последнег...,incident,https://www.mk.ru/incident/article/2010/01/05/...,Таджики устроили резню на Манежной площади под...,06/01/2010,буквально час бой курант подземный переход ста...
2,"Там они покатались на лыжах и снегоходах, пооб...",Президент РФ Дмитрий Медведев с семьей проводи...,politics,https://www.mk.ru/politics/article/2010/01/05/...,"""""""За все платит президент""""""",06/01/2010,покататься лыжа снегоход пообщаться отдыхать п...
3,Сосед расстрелял соседа из-за претензий по пов...,Первое убийство в 2010 году произошло в Москве...,incident,https://www.mk.ru/incident/article/2010/01/05/...,Первое убийство года спровоцировал потоп,06/01/2010,сосед расстрелять сосед претензия повод затопл...
4,Причиной трагедии специалисты считают нарушени...,"Шесть человек, в том числе 9-летний ребенок, з...",incident,https://www.mk.ru/incident/article/2010/01/05/...,Целая семья не пережила газовой атаки,06/01/2010,причина трагедия специалист считать нарушение ...
...,...,...,...,...,...,...,...
1995,"Скачка закончилась, а безусловный победитель т...",Как итоги выборов в туманном Альбионе могут от...,politics,https://www.mk.ru/politics/article/2010/05/07/...,Британия на весах,08/05/2010,скачок закончиться безусловный победитель выяв...
1996,.Сводный оркестр — поистине белая кость военно...,Главный военный дирижер Валерий Халилов раскры...,politics,https://www.mk.ru/politics/interview/2010/05/0...,Победа в темпе марша. АУДИО,08/05/2010,сводный оркестр поистине белый кость военный д...
1997,Эту горькую правду знает весь Междуреченск. Зд...,"Массовая гибель шахтеров не несчастный случай,...",incident,https://www.mk.ru/incident/article/2010/05/10/...,Распад начался не с “Распадской”. ВИДЕО,11/05/2010,горький правда знать весь междуреченск вообще ...
1998,8 мая президент Медведев поставил свою подпись...,О последствиях реформы бюджетной сферы не знаю...,politics,https://www.mk.ru/politics/article/2010/05/10/...,В России вводят сырой закон,11/05/2010,май президент медведев поставить подпись закон...
1999,Учительница истории Плетнева рассказала собрав...,Памятник вождю в Тамбове поставил бизнесмен — ...,editions,https://www.mk.ru/editions/daily/article/2010/...,Сталин стал запчастью истории. ФОТО,11/05/2010,учительница история плетнёв рассказать собрать...

In [52]:
vectorizer = CountVectorizer(
    max_features=15000,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.9
)

train_matrix = vectorizer.fit_transform(train_df['processed_text'])
test_matrix = vectorizer.transform(test_df['processed_text'])
vocabulary = vectorizer.get_feature_names_out()

print(f"Размер словаря: {len(vocabulary)}")
print(f"Размер матрицы обучающих данных: {train_matrix.shape}")

Размер словаря: 15000
Размер матрицы обучающих данных: (2000, 15000)

In [53]:
num_topics = 50

# **sklearn**

In [54]:
def print_topics(model, feature_names, n_top_words=10):
    for topic_idx, topic in enumerate(model.components_):
        message = f"Topic {topic_idx}: "
        message += " ".join([feature_names[i]
                           for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)

## LDA

In [55]:
sklearn_lda = LatentDirichletAllocation(
    n_components=num_topics,
    max_iter=20,
    batch_size=1000,
    random_state=42,
    n_jobs=-1
)

sklearn_lda.fit(train_matrix)

LatentDirichletAllocation(batch_size=1000, max_iter=20, n_components=50,
                          n_jobs=-1, random_state=42)

In [56]:
print("Темы sklearn LDA:")
print_topics(sklearn_lda, vocabulary)

Темы sklearn LDA:
Topic 0: это который новый школа оружие год ребёнок стать травматический время
Topic 1: дело уголовный преступление следователь сотрудник суд убийство следствие который милиция
Topic 2: рубль деньга фирма сотрудник тыс задержать сумма тыс рубль мвд сообщить
Topic 3: матч команда игрок футбол клуб лига россия чемпион первый спартак
Topic 4: война победа военный советский армия ветеран солдат великий наш день
Topic 5: который это стать солдат сказать президент часть день речник первый
Topic 6: машина водитель милиционер стать авто около произойти место который летний
Topic 7: ленин егэ язык год который июнь кремль человек белый зелёный
Topic 8: год россия новый страна это который день градус эксперимент система
Topic 9: москва московский область год город московский область место власть городской мэр
Topic 10: который сотрудник преступник рубль около казино грабитель бандит находиться место
Topic 11: пенсия год инвалид выплата размер пенсионный компенсация гражданин фонд часть
Topic 12: год шахматы шахматный который это иметь самбо россия турнир федерация
Topic 13: год человек это который дом знать свой дело стать мочь
Topic 14: год россия тысяча страна экономика новый российский который кризис стать
Topic 15: это который фильм свой мир очень год говорить человек наш
Topic 16: это человек который год журналист дело премия стать день сон
Topic 17: который камера татьяна дело долина имя абхазия год родственник решить
Topic 18: это год свой человек очень который говорить время жизнь знать
Topic 19: ребёнок врач год который пациент операция больной больница лечение медицинский
Topic 20: музей лекарство цена препарат тысяча аптека музейный год список который
Topic 21: игра наш спорт олимпийский команда это тренер который чемпионат сборная
Topic 22: взрыв теракт человек год который метро боевик террорист это дагестан
Topic 23: руб год рубль тыс дом услуга цена стоимость тариф налоговый
Topic 24: россия страна это год который наш время российский памятник новый
Topic 25: год время кофе снег мат алкоголь день свой председатель область
Topic 26: президент млн ребёнок должный год стать супруг матвеев млн руб место
Topic 27: храм церковь который первый это пётр православный миллион земля николай
Topic 28: который стать рубль молоко также продукт цена район однако сигарета
Topic 29: янукович президент украина свой выборы россия год который партия это
Topic 30: стать день аэродром встреча язык стать известно английский также который американский
Topic 31: суд ребёнок школа судья это решение родитель дело судебный который
Topic 32: это который наш человек свой россия мочь должный страна вопрос
Topic 33: который мир хиггинс первый англия марк время электромагнитный учёный чемпионат
Topic 34: алла пугачёв звезда год певица который валерий киркоров певец свой
Topic 35: задержать преступник жертва летний девушка стать несколько сыщик день мужчина
Topic 36: мотоцикл человек поезд звание вагон доллар владимир тысяча доллар свой станция
Topic 37: машина москва который место свой дорога день год автомобиль находиться
Topic 38: помещение год это который город аренда ольга объект малый адвокат
Topic 39: трасса спортивный который школа лыжный стать должный москва также спорт
Topic 40: год ребёнок летний дело суд стать мужчина уголовный который отношение
Topic 41: квартира жильё очередь день который жилищный договор год площадь метр
Topic 42: который пират алексей человек день дымовский корабль свой говорить экипаж
Topic 43: захаркина ирина день который мисс девушка девочка стать корона слово
Topic 44: район универсальный который специализировать сельскохозяйственный год округ вирус город москва
Topic 45: животное собака зоопарк сотрудник кошка вольер мочь бешенство специалист который
Topic 46: евсюков день год который человек друг максим телефон жена метро
Topic 47: улица самолёт полёт экипаж переулок пилот посадка случай площадь это
Topic 48: мужчина летний квартира дом удаться женщина дверь улица несколько свой
Topic 49: движение дорожный сотрудник инспектор водитель должный средство штраф нарушение транспортный

## NMF

In [60]:
tfidf_vectorizer = TfidfVectorizer(
    max_features=15000,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.9
)

train_tfidf = tfidf_vectorizer.fit_transform(train_df['processed_text'])
tfidf_vocab = tfidf_vectorizer.get_feature_names_out()

sklearn_nmf = NMF(
    n_components=num_topics,
    init='nndsvda',
    max_iter=500,
    random_state=42
)

sklearn_nmf.fit(train_tfidf)

NMF(init='nndsvda', max_iter=500, n_components=50, random_state=42)

In [61]:
print("Темы sklearn NMF:")
print_topics(sklearn_nmf, tfidf_vocab)

Темы sklearn NMF:
Topic 0: это человек очень говорить жизнь знать сказать ваш мочь наш
Topic 1: преступник сыщик задержать грабитель кража преступный жертва улица деньга преступление
Topic 2: год прошлый год прошлый родиться март загс смертность сравнение год год год родиться
Topic 3: олимпийский ванкувер игра медаль олимпиада спортсмен сочи тренер наш плющенко
Topic 4: ребёнок родитель мальчик усыновление астахов детский семья приёмный право ребёнок уполномоченный
Topic 5: врач пациент медик больной помощь лечение больница операция отделение клиника
Topic 6: область московский область московский подмосковье муниципальный муниципальный образование бюджет население регион образование
Topic 7: солдат военный парад войско офицер армия площадь минобороны знамя красный
Topic 8: россия страна наш экономика российский это экономический кризис власть государство
Topic 9: война ветеран победа сталин великий великий отечественный отечественный война отечественный участник советский
Topic 10: матч команда сборная игра тренер клуб игрок лига футбол спартак
Topic 11: спорт спортивный спортсмен вид спорт москомспорт занятие клуб вид соревнование трасса
Topic 12: водитель машина гибдд автомобиль дтп инспектор авто движение дорога иномарка
Topic 13: взрыв теракт боевик метро террорист смертник дагестан взрывной смертница станция
Topic 14: янукович украина тимошенко украинский виктор выборы тур юлия ющенко президент
Topic 15: руб стоимость тыс руб копа руб копа тыс цена услуга подорожать стандарт
Topic 16: колония год суд свобода осудить режим лишение свобода приговорить лишение год лишение
Topic 17: птица специалист вольер охрана самец пруд окружающий среда окружающий животное зоопарк
Topic 18: мвд сотрудник внутренний дело орган милиция внутренний орган внутренний работа милиционер дело
Topic 19: самолёт экипаж пилот полёт посадка аэродром воздушный командир борт полоса
Topic 20: молодой молодой человек парень человек студент юноша летний девушка вуз приятель
Topic 21: строительство москва здание дом объект мэр памятник гараж территория улица
Topic 22: документ должный паспорт обязать фмс новый случай стать регистрация егэ
Topic 23: школа учитель директор ученик учебный образование родитель учебный заведение заведение учиться
Topic 24: фильм режиссёр актёр кино роль картина герой играть сериал актриса
Topic 25: квартира дом жильё дверь сосед жилец этаж окно супруг пожар
Topic 26: градус ожидаться температура день гидрометцентр февраль сообщить гидрометцентр ночной дневный градус день
Topic 27: хиггинс салливана ронни снукер чемпионат марк чемпионат мир джон мир англия
Topic 28: песня концерт музыка певица альбом музыкальный сцена артист музыкант хит
Topic 29: мир чемпионат турнир чемпион кубок чемпион мир команда чемпионат мир соревнование россия
Topic 30: пристав судебный судебный пристав должник задолженность служба судебный долг служба посёлок федеральный служба
Topic 31: пистолет травматический оружие травматический пистолет пуля выстрелить милиционер выстрел охрана достать
Topic 32: отец мама дочь мать сын девочка семья женщина дочка вместе
Topic 33: собака животное пёс бездомный бешенство маша хозяин кошка который питомец
Topic 34: препарат лекарство цена аптека лекарственный перечень производитель жизненно список закон
Topic 35: белый дом сообщить аппарат аппарат белый белый аппарат инвалид выплата дом пенсия правительство
Topic 36: евсюков адвокат свидетель пронин тайм потерпевший суд карина майор убийство
Topic 37: музей церковь храм икона музейный музейщик памятник прихожанин монастырь предмет
Topic 38: фирма деньга млн бизнесмен доллар взятка предприниматель коммерсант сумма налоговый
Topic 39: рубль тыс тыс рубль тысяча тысяча рубль сумма штраф деньга доход сумма тыс
Topic 40: президент польский качиньский дмитрий медведев польша глава варшава катыни президентский
Topic 41: учёный институт ран ген исследование специалист организм эксперимент научный человек
Topic 42: пассажир билет проезд тариф станция электричка ржд автобус москва поезд
Topic 43: стража порядок стража порядок милиционер задержать блюститель милиция летний блюститель закон местный
Topic 44: суд судья верховный суд верховный фемид служитель служитель фемид иск дело сообщить верховный
Topic 45: уголовный уголовный дело дело возбудить возбудить уголовный отношение задержать скп факт следователь
Topic 46: захаркина ирина девочка адвокат присяжный катя даша николай момент окно
Topic 47: бакиев киргизия бишкек президент власть курманбек временной правительство киргизский курманбек бакиев максим
Topic 48: мужчина летний женщина гражданин несчастный скончаться тело бедолага дама свой
Topic 49: сайт интернет рекламный экран реклама канал информация сеть ролик система

## SVD/LSA

In [62]:
sklearn_svd = TruncatedSVD(
    n_components=num_topics,
    algorithm='randomized',
    n_iter=10,
    random_state=42
)

sklearn_svd.fit(train_tfidf)

TruncatedSVD(n_components=50, n_iter=10, random_state=42)

In [63]:
print("Темы sklearn SVD/LSA:")
print_topics(sklearn_svd, tfidf_vocab)

Темы sklearn SVD/LSA:
Topic 0: год это который человек свой стать наш ребёнок время россия
Topic 1: это наш россия команда игра сборная мир очень тренер матч
Topic 2: год рубль руб область тыс цена правительство власть средство московский область
Topic 3: ребёнок это фильм человек жизнь очень жить родитель мама говорить
Topic 4: ребёнок школа родитель мальчик семья врач девочка мать год малыш
Topic 5: суд год дело рубль деньга тыс уголовный задержать уголовный дело тыс рубль
Topic 6: суд ребёнок дело это судья водитель адвокат должный сотрудник документ
Topic 7: ребёнок президент школа янукович украина война россия родитель власть тимошенко
Topic 8: янукович россия президент украина страна пациент тимошенко выборы медик врач
Topic 9: суд квартира война судебный судья военный победа ветеран верховный суд верховный
Topic 10: матч квартира руб игрок янукович команда суд дом лига украина
Topic 11: квартира дом олимпийский ванкувер спорт спортсмен суд олимпиада жильё медаль
Topic 12: школа матч взрыв квартира дом клуб теракт милиционер устройство задержать
Topic 13: область теракт человек взрыв московский область московский метро станция пассажир автобус
Topic 14: янукович украина тимошенко москва украинский президент виктор выборы тур область
Topic 15: руб война военный квартира цена тыс солдат самолёт победа человек
Topic 16: собака животное ребёнок пёс самолёт уголовный уголовный дело военный война дело
Topic 17: руб самолёт экипаж янукович день теракт украина взрыв цена москва
Topic 18: руб фильм квартира область режиссёр милиционер московский область актёр кино роль
Topic 19: самолёт экипаж полёт пилот квартира посадка аэродром воздушный польский система
Topic 20: школа руб самолёт животное мужчина экипаж собака парень молодой молодой человек
Topic 21: янукович год человек украина собака животное школа тимошенко виктор квартира
Topic 22: документ янукович инвалид украина московский область область женщина ребёнок ветеран квартира
Topic 23: школа судебный песня пристав пистолет судебный пристав мир певица заведение концерт
Topic 24: фильм рубль собака режиссёр пристав судебный тысяча животное школа судебный пристав
Topic 25: квартира школа мир животное женщина турнир чемпионат препарат собака жильё
Topic 26: год мужчина руб собака женщина стать стать известно животное известно взрыв
Topic 27: собака животное документ мужчина пассажир спорт москва пистолет школа президент
Topic 28: песня концерт певица также музыка московский область взрыв адвокат машина препарат
Topic 29: человек руб бакиев мир турнир молодой молодой человек чемпионат чемпион президент
Topic 30: руб пристав судебный судебный пристав преступник год экипаж самолёт должник задержать
Topic 31: мужчина препарат пассажир лекарство песня самолёт концерт пристав цена квартира
Topic 32: мужчина тыс инвалид ребёнок это место пистолет жильё убийство чемпионат
Topic 33: мужчина человек руб ребёнок специалист пристав россия судебный учёный судебный пристав
Topic 34: животное собака песня ребёнок игра взрыв концерт стать известно квартира известно
Topic 35: мужчина система руб тариф осудить пристав школа учёный стать известно квартира
Topic 36: евсюков женщина работа стать девушка адвокат отец победа рост стать известно
Topic 37: музей церковь храм памятник икона руб музейный адвокат тысяча россия
Topic 38: женщина девушка отдел конкурс россия москва дама пристав судебный сообщить
Topic 39: пенсия тыс закон градус медаль рубль тыс рубль законопроект ванкувер пристав
Topic 40: россия улица москва год окно собака дело магазин стать известно гражданин
Topic 41: руб женщина работа стать известно сотрудник девушка девочка день захаркина известно
Topic 42: район мужчина президент бакиев новый улица тариф площадь парад военный
Topic 43: бакиев стража порядок милиционер стража порядок белый милиция ветеран сообщить станция
Topic 44: евсюков документ адвокат стража стража порядок порядок тыс год паспорт свидетель
Topic 45: пассажир бакиев молодой наркотик пристав автобус доллар улица судебный пристав проезд
Topic 46: захаркина пенсия уголовный дело машина уголовный день собака солдат возбудить возбудить уголовный
Topic 47: бакиев вуз тыс студент игра супруг выпускник руб день округ
Topic 48: девушка ядерный пристав тыс жильё уголовный оружие возбудить уголовный дело судебный пристав
Topic 49: мужчина документ собака музей депутат александр животное студент сайт москва

# **gensim**

In [64]:
tokenized_docs = [doc.split() for doc in train_df['processed_text']]
dictionary = corpora.Dictionary(tokenized_docs)
dictionary.filter_extremes(no_below=5, no_above=0.9)
corpus = [dictionary.doc2bow(doc) for doc in tokenized_docs]

## LDA

In [65]:
gensim_lda = LdaModel(
    corpus=corpus,
    id2word=dictionary,
    num_topics=num_topics,
    random_state=42,
    passes=10,
    per_word_topics=True
)

In [67]:
print("Темы gensim LDA:")
for topic_id in range(num_topics):
    print(f"Topic {topic_id}: ", end='')
    topic_words = gensim_lda.show_topic(topic_id, topn=10)
    print(" ".join([word for word, _ in topic_words]))

Темы gensim LDA:
Topic 0: год виза режим паспорт документ должный россия служба евросоюз отдел
Topic 1: стать волк известно флажок дело время год слово человек снегоход
Topic 2: магазин стать человек который год сайт порядок каждый продавщица спиртное
Topic 3: закон школа который это год свой время новый стать сми
Topic 4: год врач пациент операция который больной лечение россия медицинский человек
Topic 5: ребёнок год это который дело свой родитель человек время суд
Topic 6: янукович год москва школа витя кремль река время который первый
Topic 7: россия год который это экономика страна наш бизнес власть российский
Topic 8: год который президент свой это дело украина россия стать янукович
Topic 9: год война который ветеран область победа стать московский москва дом
Topic 10: ирина захаркина это девочка момент ребёнок очень даша адвокат подсудимый
Topic 11: пенсия год пенсионный который часть страховой фонд взнос размер новый
Topic 12: сталин знамя алексей генерал лейтенант комната свой командир который стена
Topic 13: это наш интернет который год сеть россия услуга телефон очень
Topic 14: человек евсюков который суд это год квартира дело стать слово
Topic 15: год который президент свой млн российский москва россия медведев это
Topic 16: суд пронин евсюков год который стать дело милиционер друг оказаться
Topic 17: летний мужчина машина который стать милиция свой милиционер несколько водитель
Topic 18: это который человек год говорить мочь ленин очень время дело
Topic 19: ядерный год человек иран это новый вуз страна тысяча который
Topic 20: теракт метро человек взрыв станция год боевик погибнуть автобус это
Topic 21: стать летний мужчина известно день год родитель свой дом заведение
Topic 22: осудить год тюрьма ребёнок который россия свой это человек артём
Topic 23: руб рубль цена тариф бюджет стоимость тыс билет москва проезд
Topic 24: песня год выпускник егэ который язык это волос стать the
Topic 25: год суд рубль который квартира летний сообщить тыс стать тысяча
Topic 26: который свой это человек день год слово мужчина время чехов
Topic 27: дело год задержать уголовный который деньга свой стать летний сотрудник
Topic 28: вирус год суд комиссия избирательный протокол вич дело копия стать
Topic 29: сотрудник год который рубль слово млн деньга стать друг день
Topic 30: год который гражданин россия квартира день это сообщить александр стать
Topic 31: район универсальный специализировать сельскохозяйственный округ город год москва западный который
Topic 32: который год квартира это дом москва время день также стать
Topic 33: день который летний женщина мочь рост получить девушка задержать магазин
Topic 34: это который самолёт первый матч игра команда человек свой мочь
Topic 35: команда который мир чемпионат тренер сборная россия матч игра чемпион
Topic 36: новый который год это школа свой наш время стать слово
Topic 37: год свой который дом человек это ребёнок сад место первый
Topic 38: стать время который вор храм известно икона украсть прихожанин рубль
Topic 39: театр человек это который софья минута москва поп ситуация концерт
Topic 40: год день который должный стать дом ребёнок новый мать время
Topic 41: кладбище движение который шоссе год также железнодорожный студент район место
Topic 42: год оружие который время стать день кофе грубость травматический человек
Topic 43: год московский область рубль который вклад услуга инвалид день норматив
Topic 44: год лекарство который цена препарат это стать аптека время должный
Topic 45: улица моссовет день который год пётр май война время автобус
Topic 46: год свой это который день сын брат солдат первый мама
Topic 47: год который москва это работа место тысяча улица область должный
Topic 48: это который год человек наш свой очень говорить время мочь
Topic 49: стать год который степень группа ограничение сообщить чаша инвалид новый

## NMF

In [69]:
gensim_nmf = Nmf(
    corpus=corpus,
    id2word=dictionary,
    num_topics=num_topics,
    random_state=42,
    passes=10
)

In [70]:
print("Темы gensim NMF:")
for topic_id in range(num_topics):
    print(f"Topic {topic_id}: ", end='')
    topic_words = gensim_nmf.show_topic(topic_id, topn=10)
    print(" ".join([word for word, _ in topic_words]))

Темы gensim NMF:
Topic 0: мир наш чемпионат сборная турнир команда чемпион тренер игрок памятник
Topic 1: улица переулок площадь набережная проезд проспект больший шоссе большой малый
Topic 2: который это игра россия свой олимпийский говорить первый сборная сказать
Topic 3: ребёнок врач серёжа клиника галина орган лечение месяц германия мама
Topic 4: который свой это закон власть человек мафия наш дело российский
Topic 5: год преступление республика работа орган вклад инвалид группа сотрудник также
Topic 6: президент украина выборы тимошенко голос партия тур политический который кандидат
Topic 7: который работа город должный оружие это год область спорт закон
Topic 8: трасса спортсмен спорт спортивный летний олимпиада дорога олимпийский ванкувер лыжный
Topic 9: млн год руб тыс президент супруг доход дом квартира заработать
Topic 10: ребёнок год который родитель семья ребята это говорить свой жить
Topic 11: наш год область страна это война московский подмосковье победа россия
Topic 12: цирк это москва власть вопрос цирковой музыка животное нужно новый
Topic 13: матч команда грубость авангард конец мина игра хоккей игрок дисциплинарный
Topic 14: это интернет очень говорить ваш сказать знать телевидение услуга канал
Topic 15: солдат следователь часть подполковник сказать стать аксёнов военный следственный год
Topic 16: шахматы теракт человек шахматный новый время мир взрыв играть компьютер
Topic 17: операция который человек сердце больной врач это наш пациент жизнь
Topic 18: янукович виктор школа витя президент фёдорович украина директор музей весь
Topic 19: рубль норматив тариф услуга жкх цена коммунальный область вода отопление
Topic 20: советский американский войско встреча наш песня армия офицер генерал группа
Topic 21: район универсальный специализировать сельскохозяйственный москва город округ административный строительный пересечение
Topic 22: пенсия пенсионный часть фонд страховой взнос ваш размер счёт пенсионер
Topic 23: дом осудить который южный деньга осетия средство восстановление год тюрьма
Topic 24: это фильм человек очень режиссёр кино артист театр роль делать
Topic 25: человек защита идти телефон электромагнитный война день знать работать излучение
Topic 26: квартира дело олег николаевич вопрос слово москва суд находиться документ
Topic 27: женщина год мужчина мочь метро морг песня теракт станция говорить
Topic 28: школа ребёнок родитель место поликлиника самолёт учитель образование инвалид департамент
Topic 29: это свой очень время жизнь говорить день друг знать музыка
Topic 30: музей система самолёт музейный мочь новый российский экипаж предмет церковь
Topic 31: москва тысяча свой человек японский япония наш сказать работа театр
Topic 32: суд рубль дело год тысяча месяц компания однако тыс деньга
Topic 33: интернат это артур цена экономика директор говорить понимать свой новый
Topic 34: наш это женщина министр ядерный президент иран хороший ельцин антонов
Topic 35: налоговый декларация доход год лицо продажа получить размер имущественный налог
Topic 36: профсоюз работник работодатель профсоюзный предприятие зарплата трудовой форд уволить который
Topic 37: год страна россия мир экономика первый вуз стать высокий кризис
Topic 38: который памятник москва охрана объект время исторический культурный вопрос здание
Topic 39: год это который человек мочь считать новый жить говорить сказать
Topic 40: александр саша стать очень день борисович комната война первый область
Topic 41: машина водитель сотрудник милиция который место это сказать свой автомобиль
Topic 42: дом год свой стать день город время летний театр который
Topic 43: алексей знамя стрелковый лейтенант полковник командир генерал крыша армия начальник
Topic 44: лекарство цена москва крым поликлиника препарат город лекарственный аптека московский
Topic 45: человек это год спорт тысяча мочь игра программа жизнь каждый
Topic 46: свой бакиев экспертиза новый эксперт президент институт киргизия весь который
Topic 47: война победа ветеран город место москва великий гараж московский день
Topic 48: сталин отец человек очень мама сказать семья деньга папа машина
Topic 49: россия страна который запад европа это германия российский год время