In [ ]:
# вспомогательные модули
import pandas as pd
import numpy as np

# предобработка
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler

# проверка моделей
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score, classification_report, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error, precision_score, recall_score, f1_score

# алгоритмы
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_text
from sklearn.linear_model import Ridge, ElasticNet
from sklearn.svm import SVC
from sklearn.ensemble import BaggingRegressor, BaggingClassifier, GradientBoostingRegressor, GradientBoostingClassifier, StackingRegressor, StackingClassifier, RandomForestRegressor, RandomForestClassifier
from catboost import CatBoostRegressor, CatBoostClassifier
from xgboost import XGBRegressor, XGBClassifier
from lightgbm import LGBMRegressor, LGBMClassifier

# 1. Изучение примеров
Перед началом выполнения лабораторной работы я изучил предложенные примеры

# 2. Загрузка и подготовка данных

In [33]:
data_regr = pd.read_csv('/content/post_diamonds.csv')
X_regr = data_regr.drop(columns=['price'])
y_regr = data_regr['price']
X_regr_train, X_regr_test, y_regr_train, y_regr_test = train_test_split(X_regr, y_regr, test_size=0.2, random_state=42)

data_clas = pd.read_csv('/content/post_card_transdata.csv')
X_clas = data_clas.drop(columns=['fraud'])
y_clas = data_clas['fraud']
X_clas_train, X_clas_test, y_clas_train, y_clas_test = train_test_split(X_clas, y_clas, test_size=0.2, stratify=y_clas, random_state=42)

In [34]:
scaler = StandardScaler()

X_regr_train_s = scaler.fit_transform(X_regr_train)
X_regr_test_s = scaler.transform(X_regr_test)

rus = RandomUnderSampler(random_state=42, sampling_strategy=0.5)
smote = SMOTE(random_state=42)
X_clas_train_bu, y_clas_train_bu = rus.fit_resample(X_clas_train, y_clas_train)
X_clas_train_b, y_clas_train_b = smote.fit_resample(X_clas_train, y_clas_train)
X_clas_train_bus = scaler.fit_transform(X_clas_train_bu)
X_clas_train_bs = scaler.fit_transform(X_clas_train_b)
X_clas_test_s = scaler.transform(X_clas_test)

# 3. Решение задачи регрессии и классификации

## 3.1.1 DecisionTreeRegressor

In [13]:
des_tree_regr = DecisionTreeRegressor(**{'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 8}, random_state=42)
des_tree_regr.fit(X_regr_train_s, y_regr_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='squared_error', max_depth=12,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_samples_leaf=8,
                      min_samples_split=13, min_weight_fraction_leaf=0.0,
                      monotonic_cst=None, random_state=42, splitter='best')

In [14]:
y_pred = des_tree_regr.predict(X_regr_test_s)

In [15]:
print(f"MAE: {mean_absolute_error(y_regr_test, y_pred)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_regr_test, y_pred))}")
print(f"R²: {r2_score(y_regr_test, y_pred)}")
print(f"MAPE: {mean_absolute_percentage_error(y_regr_test, y_pred)}")

MAE: 307.38324115431124
RMSE: 583.6247319504463
R²: 0.9776527845064426
MAPE: 0.08366229574625418

## 3.1.2 DecisionTreeClassifier

In [16]:
des_tree_clas = DecisionTreeClassifier(min_samples_split=5, max_depth=7, criterion='entropy', class_weight='balanced', random_state=42)
des_tree_clas.fit(X_clas_train_bs, y_clas_train_b)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight='balanced',
                       criterion='entropy', max_depth=7, max_features=None,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_samples_leaf=1, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, monotonic_cst=None,
                       random_state=42, splitter='best')

In [17]:
y_pred = des_tree_clas.predict(X_clas_test_s)

In [18]:
print(classification_report(y_clas_test, y_pred))
accuracy_score(y_clas_test, y_pred)

              precision    recall  f1-score   support

           0       1.00      0.98      0.99    182519
           1       0.85      1.00      0.92     17481

    accuracy                           0.98    200000
   macro avg       0.93      0.99      0.96    200000
weighted avg       0.99      0.98      0.99    200000

0.98465

## 3.2.1 BaggingRegressor

In [19]:
ens_bag_regr = BaggingRegressor(**{'n_estimators': 82, 'max_samples': 0.7650220936235242, 'max_features': 0.9943533773759213}, random_state=42, n_jobs=-1)
ens_bag_regr.fit(X_regr_train_s, y_regr_train)

BaggingRegressor(bootstrap=True, bootstrap_features=False, estimator=None,
                 max_features=0.9943533773759213,
                 max_samples=0.7650220936235242, n_estimators=82, n_jobs=-1,
                 oob_score=False, random_state=42, verbose=0, warm_start=False)

In [20]:
y_pred = ens_bag_regr.predict(X_regr_test_s)

In [21]:
print(f"MAE: {mean_absolute_error(y_regr_test, y_pred)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_regr_test, y_pred))}")
print(f"R²: {r2_score(y_regr_test, y_pred)}")
print(f"MAPE: {mean_absolute_percentage_error(y_regr_test, y_pred)}")

MAE: 264.680945080795
RMSE: 518.2833487725327
R²: 0.9823765652722098
MAPE: 0.06751857865456691

## 3.2.2 BaggingClassifier

In [22]:
ens_bag_clas = BaggingClassifier(**{'n_estimators': 43, 'max_samples': 0.7999412510648061, 'max_features': 0.9521873714773709}, random_state=42, n_jobs=-1)
ens_bag_clas.fit(X_clas_train_bs, y_clas_train_b)

BaggingClassifier(bootstrap=True, bootstrap_features=False, estimator=None,
                  max_features=0.9521873714773709,
                  max_samples=0.7999412510648061, n_estimators=43, n_jobs=-1,
                  oob_score=False, random_state=42, verbose=0,
                  warm_start=False)

In [23]:
y_pred = ens_bag_clas.predict(X_clas_test_s)

In [24]:
print(classification_report(y_clas_test, y_pred))
accuracy_score(y_clas_test, y_pred)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    182519
           1       0.88      1.00      0.94     17481

    accuracy                           0.99    200000
   macro avg       0.94      0.99      0.97    200000
weighted avg       0.99      0.99      0.99    200000

0.988265

## 3.2.3 GradientBoostingRegressor

In [25]:
gb_regr = GradientBoostingRegressor(**{'n_estimators': 333, 'learning_rate': 0.015750619803704784, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.7276427960501565}, random_state=42)
gb_regr.fit(X_regr_train_s, y_regr_train)

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.015750619803704784,
                          loss='squared_error', max_depth=8, max_features=None,
                          max_leaf_nodes=None, min_impurity_decrease=0.0,
                          min_samples_leaf=3, min_samples_split=7,
                          min_weight_fraction_leaf=0.0, n_estimators=333,
                          n_iter_no_change=None, random_state=42,
                          subsample=0.7276427960501565, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [26]:
y_pred = gb_regr.predict(X_regr_test_s)

In [27]:
print(f"MAE: {mean_absolute_error(y_regr_test, y_pred)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_regr_test, y_pred))}")
print(f"R²: {r2_score(y_regr_test, y_pred)}")
print(f"MAPE: {mean_absolute_percentage_error(y_regr_test, y_pred)}")

MAE: 256.5494699187415
RMSE: 492.5275336206774
R²: 0.9840846179098718
MAPE: 0.0714883126370642

## 3.2.4 GradientBoostingClassifier

In [28]:
gb_clas = GradientBoostingClassifier(**{'n_estimators': 500, 'learning_rate': 0.047491241225455304, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 2, 'subsample': 0.7314298772479082, 'max_features': 'log2'}, random_state=42)
gb_clas.fit(X_clas_train_bus, y_clas_train_bu)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.047491241225455304, loss='log_loss',
                           max_depth=4, max_features='log2',
                           max_leaf_nodes=None, min_impurity_decrease=0.0,
                           min_samples_leaf=2, min_samples_split=8,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, random_state=42,
                           subsample=0.7314298772479082, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [29]:
y_pred = gb_clas.predict(X_clas_test_s)

In [30]:
print(classification_report(y_clas_test, y_pred))
accuracy_score(y_clas_test, y_pred)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99    182519
           1       0.96      0.80      0.87     17481

    accuracy                           0.98    200000
   macro avg       0.97      0.90      0.93    200000
weighted avg       0.98      0.98      0.98    200000

0.979625

## 3.2.5 StackingRegressor

In [35]:
base_models = [
    ('Ridge', Ridge(alpha=25.241424867460356, random_state=42)),
    ('GradientBoosting', GradientBoostingRegressor(**{'n_estimators': 333, 'learning_rate': 0.015750619803704784, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.7276427960501565}, random_state=42)),
    ('RandomTree', RandomForestRegressor(**{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_features': 1.0, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 50, 'verbose': 0, 'warm_start': False}))
]
meta_model = ElasticNet(alpha=0.002183419021890954, l1_ratio=0.6572558012453984, random_state=42)

stack_regr = StackingRegressor(estimators=base_models, final_estimator=meta_model, n_jobs=-1)
stack_regr.fit(X_regr_train_s, y_regr_train)

StackingRegressor(cv=None,
                  estimators=[('Ridge',
                               Ridge(alpha=25.241424867460356, copy_X=True,
                                     fit_intercept=True, max_iter=None,
                                     positive=False, random_state=42,
                                     solver='auto', tol=0.0001)),
                              ('GradientBoosting',
                               GradientBoostingRegressor(alpha=0.9,
                                                         ccp_alpha=0.0,
                                                         criterion='friedman_mse',
                                                         init=None,
                                                         learning_rate=0.015750619803704784,
                                                         loss='squared_error',
                                                         max_dept...
                                                     n_estimators=100,
                                                     n_jobs=-1, oob_score=False,
                                                     random_state=50, verbose=0,
                                                     warm_start=False))],
                  final_estimator=ElasticNet(alpha=0.002183419021890954,
                                             copy_X=True, fit_intercept=True,
                                             l1_ratio=0.6572558012453984,
                                             max_iter=1000, positive=False,
                                             precompute=False, random_state=42,
                                             selection='cyclic', tol=0.0001,
                                             warm_start=False),
                  n_jobs=-1, passthrough=False, verbose=0)

In [36]:
y_pred = stack_regr.predict(X_regr_test_s)

In [37]:
print(f"MAE: {mean_absolute_error(y_regr_test, y_pred)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_regr_test, y_pred))}")
print(f"R²: {r2_score(y_regr_test, y_pred)}")
print(f"MAPE: {mean_absolute_percentage_error(y_regr_test, y_pred)}")

MAE: 251.85341896748247
RMSE: 490.30688631316826
R²: 0.98422780899724
MAPE: 0.0663179408408268

## 3.2.6 StackingClassifier

In [38]:
_, X_clas_train_bus_svc, _, y_clas_train_bu_svc = train_test_split(X_clas_train_bus, y_clas_train_bu, test_size=0.4, stratify=y_clas_train_bu, random_state=42)

In [39]:
base_models = [
    ('SVC', SVC(gamma=0.1, random_state=42)),
    ('Tree', DecisionTreeClassifier(min_samples_split=5, max_depth=7, criterion='entropy', class_weight='balanced', random_state=42)),
    ('RandomTree', RandomForestClassifier(**{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'gini', 'max_features': 'sqrt', 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 51, 'verbose': 0, 'warm_start': False}))
]
meta_model = LGBMClassifier(**{'n_estimators': 378, 'max_depth': 4, 'learning_rate': 0.045472411633406845, 'num_leaves': 167, 'min_child_samples': 15, 'subsample': 0.787300997249121, 'colsample_bytree': 0.8020043291010864, 'reg_alpha': 0.6629728220339912, 'reg_lambda': 0.12603478242435429}, force_col_wise=True)

stack_clas = StackingClassifier(estimators=base_models, final_estimator=meta_model, n_jobs=-1)
stack_clas.fit(X_clas_train_bus_svc, y_clas_train_bu_svc)

[LightGBM] [Info] Number of positive: 27969, number of negative: 55938
[LightGBM] [Info] Total Bins 327
[LightGBM] [Info] Number of data points in the train set: 83907, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.333333 -> initscore=-0.693147
[LightGBM] [Info] Start training from score -0.693147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

StackingClassifier(cv=None,
                   estimators=[('SVC',
                                SVC(C=1.0, break_ties=False, cache_size=200,
                                    class_weight=None, coef0=0.0,
                                    decision_function_shape='ovr', degree=3,
                                    gamma=0.1, kernel='rbf', max_iter=-1,
                                    probability=False, random_state=42,
                                    shrinking=True, tol=0.001, verbose=False)),
                               ('Tree',
                                DecisionTreeClassifier(ccp_alpha=0.0,
                                                       class_weight='balanced',
                                                       criterion='entro...
                                                  learning_rate=0.045472411633406845,
                                                  max_depth=4,
                                                  min_child_samples=15,
                                                  min_child_weight=0.001,
                                                  min_split_gain=0.0,
                                                  n_estimators=378, n_jobs=None,
                                                  num_leaves=167,
                                                  objective=None,
                                                  random_state=None,
                                                  reg_alpha=0.6629728220339912,
                                                  reg_lambda=0.12603478242435429,
                                                  subsample=0.787300997249121,
                                                  subsample_for_bin=200000,
                                                  subsample_freq=0),
                   n_jobs=-1, passthrough=False, stack_method='auto',
                   verbose=0)

In [40]:
y_pred = stack_clas.predict(X_clas_test_s)

In [41]:
print(classification_report(y_clas_test, y_pred))
accuracy_score(y_clas_test, y_pred)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99    182519
           1       0.94      0.80      0.87     17481

    accuracy                           0.98    200000
   macro avg       0.96      0.90      0.93    200000
weighted avg       0.98      0.98      0.98    200000

0.978505

## 3.3.1 CatBoost Regression

In [42]:
cat_boost_regr = CatBoostRegressor(**{'iterations': 1120, 'learning_rate': 0.0387592525723667, 'depth': 6, 'l2_leaf_reg': 0.0006357456098930143, 'bagging_temperature': 0.03172310195167838, 'random_strength': 3.7360878294978876, 'grow_policy': 'SymmetricTree'}, task_type='CPU', thread_count=-1, random_state=42)
cat_boost_regr.fit(X_regr_train_s, y_regr_train)

0:	learn: 3876.3185730	total: 32.3ms	remaining: 36.2s
1:	learn: 3744.5004501	total: 42.2ms	remaining: 23.6s
2:	learn: 3622.8470011	total: 49.5ms	remaining: 18.4s
3:	learn: 3509.1698650	total: 56.8ms	remaining: 15.8s
4:	learn: 3399.2064948	total: 64.3ms	remaining: 14.3s
5:	learn: 3293.1042851	total: 71.5ms	remaining: 13.3s
6:	learn: 3191.0808468	total: 80.1ms	remaining: 12.7s
7:	learn: 3091.5989186	total: 91.9ms	remaining: 12.8s
8:	learn: 2999.7389499	total: 112ms	remaining: 13.8s
9:	learn: 2909.9680242	total: 122ms	remaining: 13.6s
10:	learn: 2815.3148049	total: 132ms	remaining: 13.3s
11:	learn: 2730.8512821	total: 141ms	remaining: 13s
12:	learn: 2653.0528805	total: 149ms	remaining: 12.7s
13:	learn: 2577.5955053	total: 156ms	remaining: 12.3s
14:	learn: 2500.5535327	total: 163ms	remaining: 12s
15:	learn: 2427.3150869	total: 171ms	remaining: 11.8s
16:	learn: 2361.0691060	total: 179ms	remaining: 11.6s
17:	learn: 2294.9152652	total: 186ms	remaining: 11.4s
18:	learn: 2226.4756307	total: 194ms	remaining: 11.2s
19:	learn: 2161.1703615	total: 201ms	remaining: 11.1s
20:	learn: 2101.6906417	total: 209ms	remaining: 10.9s
21:	learn: 2045.8235194	total: 216ms	remaining: 10.8s
22:	learn: 1990.9231459	total: 223ms	remaining: 10.7s
23:	learn: 1935.1978582	total: 233ms	remaining: 10.6s
24:	learn: 1880.7680333	total: 241ms	remaining: 10.5s
25:	learn: 1830.8493150	total: 248ms	remaining: 10.5s
26:	learn: 1785.5941740	total: 256ms	remaining: 10.4s
27:	learn: 1740.4025349	total: 264ms	remaining: 10.3s
28:	learn: 1694.2915048	total: 272ms	remaining: 10.2s
29:	learn: 1649.0217128	total: 279ms	remaining: 10.2s
30:	learn: 1605.7815608	total: 287ms	remaining: 10.1s
31:	learn: 1564.8720456	total: 295ms	remaining: 10s
32:	learn: 1527.5588529	total: 303ms	remaining: 9.97s
33:	learn: 1489.7051151	total: 315ms	remaining: 10.1s
34:	learn: 1453.6436575	total: 323ms	remaining: 10s
35:	learn: 1421.6611798	total: 331ms	remaining: 9.96s
36:	learn: 1389.4133451	total: 339ms	remaining: 9.91s
37:	learn: 1364.2483736	total: 345ms	remaining: 9.82s
38:	learn: 1332.8699681	total: 353ms	remaining: 9.79s
39:	learn: 1304.1422173	total: 361ms	remaining: 9.75s
40:	learn: 1275.7954205	total: 369ms	remaining: 9.71s
41:	learn: 1248.7113305	total: 376ms	remaining: 9.66s
42:	learn: 1223.9048469	total: 384ms	remaining: 9.61s
43:	learn: 1200.6739289	total: 391ms	remaining: 9.57s
44:	learn: 1178.7718852	total: 399ms	remaining: 9.53s
45:	learn: 1155.0680992	total: 406ms	remaining: 9.49s
46:	learn: 1133.2995595	total: 414ms	remaining: 9.44s
47:	learn: 1114.1902441	total: 421ms	remaining: 9.4s
48:	learn: 1094.5208120	total: 428ms	remaining: 9.36s
49:	learn: 1075.7032478	total: 444ms	remaining: 9.49s
50:	learn: 1056.0352410	total: 452ms	remaining: 9.47s
51:	learn: 1040.6865507	total: 459ms	remaining: 9.43s
52:	learn: 1024.9480425	total: 466ms	remaining: 9.39s
53:	learn: 1008.8058378	total: 474ms	remaining: 9.36s
54:	learn: 992.4534044	total: 481ms	remaining: 9.32s
55:	learn: 977.1055511	total: 490ms	remaining: 9.3s
56:	learn: 963.2859873	total: 497ms	remaining: 9.27s
57:	learn: 951.2270967	total: 505ms	remaining: 9.24s
58:	learn: 937.5371059	total: 514ms	remaining: 9.25s
59:	learn: 925.4920503	total: 522ms	remaining: 9.22s
60:	learn: 912.6399884	total: 530ms	remaining: 9.19s
61:	learn: 901.1415466	total: 537ms	remaining: 9.16s
62:	learn: 891.5230844	total: 544ms	remaining: 9.13s
63:	learn: 881.9901119	total: 552ms	remaining: 9.1s
64:	learn: 871.1213761	total: 559ms	remaining: 9.07s
65:	learn: 861.8191194	total: 567ms	remaining: 9.06s
66:	learn: 852.5822063	total: 576ms	remaining: 9.04s
67:	learn: 843.8645852	total: 583ms	remaining: 9.02s
68:	learn: 837.8238520	total: 591ms	remaining: 9s
69:	learn: 828.8561781	total: 598ms	remaining: 8.97s
70:	learn: 821.6503977	total: 605ms	remaining: 8.95s
71:	learn: 814.1451478	total: 613ms	remaining: 8.92s
72:	learn: 806.4015569	total: 620ms	remaining: 8.89s
73:	learn: 798.6962673	total: 627ms	remaining: 8.86s
74:	learn: 791.6601814	total: 634ms	remaining: 8.84s
75:	learn: 784.1832735	total: 645ms	remaining: 8.85s
76:	learn: 777.4086932	total: 653ms	remaining: 8.85s
77:	learn: 771.0054085	total: 660ms	remaining: 8.82s
78:	learn: 764.5332116	total: 672ms	remaining: 8.86s
79:	learn: 758.4867369	total: 680ms	remaining: 8.84s
80:	learn: 753.2672271	total: 687ms	remaining: 8.82s
81:	learn: 747.7117803	total: 694ms	remaining: 8.79s
82:	learn: 742.3039176	total: 702ms	remaining: 8.77s
83:	learn: 738.9295047	total: 715ms	remaining: 8.82s
84:	learn: 734.6401236	total: 723ms	remaining: 8.8s
85:	learn: 730.1387828	total: 730ms	remaining: 8.78s
86:	learn: 726.1831263	total: 737ms	remaining: 8.76s
87:	learn: 723.0435141	total: 745ms	remaining: 8.74s
88:	learn: 718.9415770	total: 753ms	remaining: 8.73s
89:	learn: 714.7162420	total: 761ms	remaining: 8.71s
90:	learn: 711.0458429	total: 769ms	remaining: 8.69s
91:	learn: 706.9829380	total: 778ms	remaining: 8.69s
92:	learn: 703.4427426	total: 787ms	remaining: 8.69s
93:	learn: 700.5301193	total: 797ms	remaining: 8.7s
94:	learn: 697.2164148	total: 809ms	remaining: 8.72s
95:	learn: 694.0004135	total: 819ms	remaining: 8.73s
96:	learn: 691.0844590	total: 826ms	remaining: 8.71s
97:	learn: 688.6901782	total: 833ms	remaining: 8.69s
98:	learn: 685.6719519	total: 841ms	remaining: 8.68s
99:	learn: 682.5087467	total: 850ms	remaining: 8.67s
100:	learn: 679.4092765	total: 858ms	remaining: 8.65s
101:	learn: 676.8708376	total: 866ms	remaining: 8.64s
102:	learn: 674.1353888	total: 873ms	remaining: 8.62s
103:	learn: 671.7125231	total: 881ms	remaining: 8.61s
104:	learn: 669.0098270	total: 889ms	remaining: 8.6s
105:	learn: 666.1356472	total: 897ms	remaining: 8.58s
106:	learn: 663.9614464	total: 904ms	remaining: 8.56s
107:	learn: 661.4171089	total: 912ms	remaining: 8.54s
108:	learn: 659.2658557	total: 921ms	remaining: 8.54s
109:	learn: 656.8546730	total: 928ms	remaining: 8.52s
110:	learn: 654.5329374	total: 935ms	remaining: 8.5s
111:	learn: 651.7870171	total: 943ms	remaining: 8.49s
112:	learn: 649.4207510	total: 952ms	remaining: 8.48s
113:	learn: 647.5109653	total: 959ms	remaining: 8.46s
114:	learn: 645.8024947	total: 967ms	remaining: 8.46s
115:	learn: 643.8361666	total: 975ms	remaining: 8.44s
116:	learn: 641.9812297	total: 983ms	remaining: 8.42s
117:	learn: 640.1905884	total: 990ms	remaining: 8.4s
118:	learn: 638.7316716	total: 997ms	remaining: 8.39s
119:	learn: 636.6244253	total: 1s	remaining: 8.37s
120:	learn: 634.7304264	total: 1.01s	remaining: 8.36s
121:	learn: 633.4285258	total: 1.02s	remaining: 8.35s
122:	learn: 632.0218672	total: 1.03s	remaining: 8.33s
123:	learn: 631.2078580	total: 1.03s	remaining: 8.31s
124:	learn: 629.9452236	total: 1.04s	remaining: 8.32s
125:	learn: 628.5180148	total: 1.05s	remaining: 8.3s
126:	learn: 627.7534009	total: 1.06s	remaining: 8.28s
127:	learn: 626.4618865	total: 1.07s	remaining: 8.27s
128:	learn: 624.8683118	total: 1.07s	remaining: 8.25s
129:	learn: 623.5853455	total: 1.08s	remaining: 8.24s
130:	learn: 622.1493337	total: 1.09s	remaining: 8.24s
131:	learn: 621.3374328	total: 1.1s	remaining: 8.22s
132:	learn: 619.7635921	total: 1.1s	remaining: 8.21s
133:	learn: 618.3060702	total: 1.11s	remaining: 8.19s
134:	learn: 617.4304469	total: 1.13s	remaining: 8.26s
135:	learn: 616.2074664	total: 1.15s	remaining: 8.29s
136:	learn: 614.7970118	total: 1.15s	remaining: 8.27s
137:	learn: 613.8403832	total: 1.16s	remaining: 8.26s
138:	learn: 612.8132060	total: 1.17s	remaining: 8.24s
139:	learn: 611.7131406	total: 1.17s	remaining: 8.22s
140:	learn: 610.6018746	total: 1.18s	remaining: 8.21s
141:	learn: 609.3888301	total: 1.19s	remaining: 8.19s
142:	learn: 608.3925411	total: 1.2s	remaining: 8.18s
143:	learn: 606.9717539	total: 1.2s	remaining: 8.16s
144:	learn: 606.3181786	total: 1.21s	remaining: 8.15s
145:	learn: 605.3288261	total: 1.22s	remaining: 8.13s
146:	learn: 604.6078187	total: 1.23s	remaining: 8.12s
147:	learn: 603.7843049	total: 1.23s	remaining: 8.1s
148:	learn: 602.8250399	total: 1.24s	remaining: 8.09s
149:	learn: 602.0477361	total: 1.25s	remaining: 8.09s
150:	learn: 601.6055963	total: 1.26s	remaining: 8.08s
151:	learn: 600.5783283	total: 1.26s	remaining: 8.06s
152:	learn: 599.4984265	total: 1.27s	remaining: 8.04s
153:	learn: 599.0261894	total: 1.28s	remaining: 8.03s
154:	learn: 598.3541363	total: 1.29s	remaining: 8.04s
155:	learn: 597.3312181	total: 1.3s	remaining: 8.02s
156:	learn: 596.8501344	total: 1.3s	remaining: 8.01s
157:	learn: 596.1079638	total: 1.31s	remaining: 7.99s
158:	learn: 595.3536269	total: 1.32s	remaining: 7.98s
159:	learn: 594.6165424	total: 1.33s	remaining: 7.96s
160:	learn: 593.9716782	total: 1.34s	remaining: 7.96s
161:	learn: 592.9478971	total: 1.34s	remaining: 7.95s
162:	learn: 592.7349744	total: 1.35s	remaining: 7.93s
163:	learn: 591.8027444	total: 1.36s	remaining: 7.93s
164:	learn: 591.2006170	total: 1.37s	remaining: 7.91s
165:	learn: 590.4338516	total: 1.37s	remaining: 7.89s
166:	learn: 589.7055173	total: 1.38s	remaining: 7.88s
167:	learn: 589.2852398	total: 1.39s	remaining: 7.87s
168:	learn: 588.2874429	total: 1.4s	remaining: 7.86s
169:	learn: 587.2851314	total: 1.4s	remaining: 7.85s
170:	learn: 586.8058995	total: 1.41s	remaining: 7.84s
171:	learn: 586.0303032	total: 1.42s	remaining: 7.84s
172:	learn: 585.6843379	total: 1.43s	remaining: 7.82s
173:	learn: 584.8345424	total: 1.44s	remaining: 7.81s
174:	learn: 584.1806833	total: 1.45s	remaining: 7.81s
175:	learn: 583.5558162	total: 1.45s	remaining: 7.8s
176:	learn: 583.2492630	total: 1.46s	remaining: 7.79s
177:	learn: 582.7284613	total: 1.47s	remaining: 7.78s
178:	learn: 582.0864077	total: 1.48s	remaining: 7.76s
179:	learn: 581.6481779	total: 1.48s	remaining: 7.75s
180:	learn: 581.1477359	total: 1.49s	remaining: 7.74s
181:	learn: 580.1829825	total: 1.5s	remaining: 7.72s
182:	learn: 579.4636624	total: 1.5s	remaining: 7.71s
183:	learn: 578.8107620	total: 1.51s	remaining: 7.7s
184:	learn: 578.3017145	total: 1.52s	remaining: 7.69s
185:	learn: 577.8042751	total: 1.53s	remaining: 7.67s
186:	learn: 577.3370094	total: 1.54s	remaining: 7.68s
187:	learn: 576.8033337	total: 1.55s	remaining: 7.67s
188:	learn: 576.5133403	total: 1.55s	remaining: 7.66s
189:	learn: 576.0618616	total: 1.56s	remaining: 7.64s
190:	learn: 575.7403342	total: 1.57s	remaining: 7.63s
191:	learn: 575.2899176	total: 1.58s	remaining: 7.62s
192:	learn: 574.8829963	total: 1.58s	remaining: 7.6s
193:	learn: 574.4119207	total: 1.59s	remaining: 7.59s
194:	learn: 573.9574649	total: 1.6s	remaining: 7.58s
195:	learn: 573.4320715	total: 1.6s	remaining: 7.57s
196:	learn: 573.0393074	total: 1.61s	remaining: 7.56s
197:	learn: 572.7895109	total: 1.62s	remaining: 7.54s
198:	learn: 572.3194466	total: 1.63s	remaining: 7.53s
199:	learn: 571.9230568	total: 1.63s	remaining: 7.52s
200:	learn: 571.8694169	total: 1.64s	remaining: 7.5s
201:	learn: 571.5608217	total: 1.65s	remaining: 7.49s
202:	learn: 571.2018482	total: 1.66s	remaining: 7.48s
203:	learn: 570.7191248	total: 1.66s	remaining: 7.47s
204:	learn: 570.1559039	total: 1.67s	remaining: 7.46s
205:	learn: 569.4305047	total: 1.68s	remaining: 7.44s
206:	learn: 569.2473661	total: 1.69s	remaining: 7.43s
207:	learn: 568.7298565	total: 1.69s	remaining: 7.42s
208:	learn: 568.6088128	total: 1.7s	remaining: 7.41s
209:	learn: 568.1122053	total: 1.71s	remaining: 7.4s
210:	learn: 567.6964108	total: 1.72s	remaining: 7.39s
211:	learn: 567.4394801	total: 1.72s	remaining: 7.38s
212:	learn: 567.1834353	total: 1.73s	remaining: 7.36s
213:	learn: 566.5799396	total: 1.74s	remaining: 7.36s
214:	learn: 566.0600125	total: 1.75s	remaining: 7.35s
215:	learn: 565.9075790	total: 1.76s	remaining: 7.35s
216:	learn: 565.6660208	total: 1.77s	remaining: 7.35s
217:	learn: 565.3762415	total: 1.78s	remaining: 7.36s
218:	learn: 565.1720934	total: 1.78s	remaining: 7.34s
219:	learn: 564.9926120	total: 1.79s	remaining: 7.33s
220:	learn: 564.7973420	total: 1.8s	remaining: 7.32s
221:	learn: 564.5089311	total: 1.81s	remaining: 7.31s
222:	learn: 564.1857122	total: 1.81s	remaining: 7.3s
223:	learn: 563.9046201	total: 1.82s	remaining: 7.29s
224:	learn: 563.6760262	total: 1.83s	remaining: 7.27s
225:	learn: 563.4569794	total: 1.84s	remaining: 7.27s
226:	learn: 563.0145822	total: 1.84s	remaining: 7.26s
227:	learn: 562.4554085	total: 1.85s	remaining: 7.26s
228:	learn: 562.3379263	total: 1.86s	remaining: 7.24s
229:	learn: 562.0523806	total: 1.87s	remaining: 7.24s
230:	learn: 561.8291581	total: 1.88s	remaining: 7.23s
231:	learn: 561.7074000	total: 1.89s	remaining: 7.22s
232:	learn: 561.4191999	total: 1.89s	remaining: 7.21s
233:	learn: 561.0568807	total: 1.9s	remaining: 7.2s
234:	learn: 560.7773461	total: 1.91s	remaining: 7.19s
235:	learn: 560.5308986	total: 1.92s	remaining: 7.18s
236:	learn: 560.1346958	total: 1.93s	remaining: 7.17s
237:	learn: 559.5797836	total: 1.93s	remaining: 7.17s
238:	learn: 559.2238425	total: 1.94s	remaining: 7.17s
239:	learn: 558.7141653	total: 1.95s	remaining: 7.16s
240:	learn: 558.2886888	total: 1.96s	remaining: 7.15s
241:	learn: 557.9389808	total: 1.97s	remaining: 7.13s
242:	learn: 557.5668394	total: 1.97s	remaining: 7.12s
243:	learn: 557.3235733	total: 1.98s	remaining: 7.11s
244:	learn: 556.7049750	total: 1.99s	remaining: 7.1s
245:	learn: 556.4235542	total: 2s	remaining: 7.09s
246:	learn: 556.1775328	total: 2s	remaining: 7.08s
247:	learn: 556.0253849	total: 2.01s	remaining: 7.07s
248:	learn: 555.7246607	total: 2.02s	remaining: 7.06s
249:	learn: 555.2186900	total: 2.03s	remaining: 7.05s
250:	learn: 555.0314832	total: 2.03s	remaining: 7.04s
251:	learn: 554.8778087	total: 2.04s	remaining: 7.03s
252:	learn: 554.7596950	total: 2.05s	remaining: 7.02s
253:	learn: 554.6263677	total: 2.06s	remaining: 7.02s
254:	learn: 554.1759009	total: 2.07s	remaining: 7.02s
255:	learn: 553.7770537	total: 2.08s	remaining: 7s
256:	learn: 553.5921761	total: 2.08s	remaining: 6.99s
257:	learn: 553.3685510	total: 2.09s	remaining: 6.98s
258:	learn: 553.1781744	total: 2.1s	remaining: 6.97s
259:	learn: 552.8680259	total: 2.1s	remaining: 6.96s
260:	learn: 552.7322069	total: 2.11s	remaining: 6.95s
261:	learn: 552.4624284	total: 2.12s	remaining: 6.94s
262:	learn: 552.2250897	total: 2.14s	remaining: 6.98s
263:	learn: 552.0704258	total: 2.16s	remaining: 6.99s
264:	learn: 551.9865214	total: 2.16s	remaining: 6.98s
265:	learn: 551.6351200	total: 2.17s	remaining: 6.97s
266:	learn: 551.1998935	total: 2.18s	remaining: 6.96s
267:	learn: 550.8872574	total: 2.18s	remaining: 6.95s
268:	learn: 550.6955610	total: 2.19s	remaining: 6.93s
269:	learn: 550.2765392	total: 2.2s	remaining: 6.92s
270:	learn: 550.0108173	total: 2.21s	remaining: 6.92s
271:	learn: 549.7018402	total: 2.21s	remaining: 6.91s
272:	learn: 549.4450791	total: 2.22s	remaining: 6.9s
273:	learn: 549.1224624	total: 2.23s	remaining: 6.88s
274:	learn: 548.8913713	total: 2.24s	remaining: 6.88s
275:	learn: 548.5679653	total: 2.24s	remaining: 6.86s
276:	learn: 548.3708578	total: 2.25s	remaining: 6.85s
277:	learn: 548.1663391	total: 2.27s	remaining: 6.86s
278:	learn: 547.9841274	total: 2.27s	remaining: 6.86s
279:	learn: 547.7777360	total: 2.28s	remaining: 6.85s
280:	learn: 547.5441986	total: 2.29s	remaining: 6.84s
281:	learn: 547.4125031	total: 2.3s	remaining: 6.83s
282:	learn: 547.0787855	total: 2.31s	remaining: 6.82s
283:	learn: 546.9432582	total: 2.31s	remaining: 6.81s
284:	learn: 546.6443839	total: 2.32s	remaining: 6.81s
285:	learn: 546.4880665	total: 2.33s	remaining: 6.8s
286:	learn: 546.2651417	total: 2.34s	remaining: 6.79s
287:	learn: 546.1554030	total: 2.35s	remaining: 6.78s
288:	learn: 545.8492825	total: 2.35s	remaining: 6.77s
289:	learn: 545.6736144	total: 2.36s	remaining: 6.76s
290:	learn: 545.4791790	total: 2.37s	remaining: 6.75s
291:	learn: 545.2426450	total: 2.38s	remaining: 6.74s
292:	learn: 545.0030821	total: 2.39s	remaining: 6.74s
293:	learn: 544.7832433	total: 2.39s	remaining: 6.73s
294:	learn: 544.3841872	total: 2.4s	remaining: 6.72s
295:	learn: 544.1672811	total: 2.41s	remaining: 6.72s
296:	learn: 543.7229865	total: 2.42s	remaining: 6.71s
297:	learn: 543.4506309	total: 2.43s	remaining: 6.7s
298:	learn: 543.3422996	total: 2.44s	remaining: 6.69s
299:	learn: 543.1517738	total: 2.44s	remaining: 6.68s
300:	learn: 542.9384786	total: 2.45s	remaining: 6.67s
301:	learn: 542.6761303	total: 2.46s	remaining: 6.66s
302:	learn: 542.4941494	total: 2.47s	remaining: 6.67s
303:	learn: 542.2576984	total: 2.48s	remaining: 6.66s
304:	learn: 541.9964090	total: 2.49s	remaining: 6.65s
305:	learn: 541.7482261	total: 2.5s	remaining: 6.64s
306:	learn: 541.5661842	total: 2.5s	remaining: 6.63s
307:	learn: 541.4116751	total: 2.51s	remaining: 6.62s
308:	learn: 541.2394028	total: 2.52s	remaining: 6.61s
309:	learn: 541.0390525	total: 2.53s	remaining: 6.6s
310:	learn: 540.9415086	total: 2.53s	remaining: 6.59s
311:	learn: 540.6923715	total: 2.54s	remaining: 6.58s
312:	learn: 540.3770005	total: 2.55s	remaining: 6.58s
313:	learn: 540.0804139	total: 2.56s	remaining: 6.57s
314:	learn: 539.7940292	total: 2.56s	remaining: 6.55s
315:	learn: 539.3209379	total: 2.57s	remaining: 6.54s
316:	learn: 539.2105090	total: 2.58s	remaining: 6.53s
317:	learn: 538.8606627	total: 2.59s	remaining: 6.53s
318:	learn: 538.6879326	total: 2.59s	remaining: 6.51s
319:	learn: 538.4368392	total: 2.6s	remaining: 6.51s
320:	learn: 538.2431807	total: 2.61s	remaining: 6.5s
321:	learn: 537.9041429	total: 2.62s	remaining: 6.49s
322:	learn: 537.5221974	total: 2.63s	remaining: 6.48s
323:	learn: 537.3330158	total: 2.63s	remaining: 6.47s
324:	learn: 537.0042397	total: 2.64s	remaining: 6.46s
325:	learn: 536.8872751	total: 2.65s	remaining: 6.46s
326:	learn: 536.4941131	total: 2.66s	remaining: 6.45s
327:	learn: 536.1450637	total: 2.67s	remaining: 6.44s
328:	learn: 535.9189603	total: 2.68s	remaining: 6.44s
329:	learn: 535.5387955	total: 2.69s	remaining: 6.43s
330:	learn: 535.3999537	total: 2.69s	remaining: 6.42s
331:	learn: 535.0553675	total: 2.7s	remaining: 6.41s
332:	learn: 534.9409995	total: 2.71s	remaining: 6.41s
333:	learn: 534.6269788	total: 2.72s	remaining: 6.4s
334:	learn: 534.4775048	total: 2.73s	remaining: 6.4s
335:	learn: 534.1420219	total: 2.74s	remaining: 6.4s
336:	learn: 533.8498689	total: 2.76s	remaining: 6.4s
337:	learn: 533.7083511	total: 2.76s	remaining: 6.4s
338:	learn: 533.5467629	total: 2.78s	remaining: 6.4s
339:	learn: 533.3694012	total: 2.79s	remaining: 6.4s
340:	learn: 533.1893763	total: 2.79s	remaining: 6.39s
341:	learn: 532.9658012	total: 2.8s	remaining: 6.38s
342:	learn: 532.6837217	total: 2.81s	remaining: 6.37s
343:	learn: 532.5302644	total: 2.82s	remaining: 6.36s
344:	learn: 532.2581950	total: 2.82s	remaining: 6.34s
345:	learn: 532.1005205	total: 2.83s	remaining: 6.34s
346:	learn: 531.9095019	total: 2.84s	remaining: 6.33s
347:	learn: 531.7237060	total: 2.85s	remaining: 6.31s
348:	learn: 531.5627995	total: 2.85s	remaining: 6.3s
349:	learn: 531.1765010	total: 2.86s	remaining: 6.29s
350:	learn: 530.9804115	total: 2.87s	remaining: 6.28s
351:	learn: 530.7434656	total: 2.88s	remaining: 6.28s
352:	learn: 530.4229691	total: 2.88s	remaining: 6.27s
353:	learn: 530.2378680	total: 2.89s	remaining: 6.26s
354:	learn: 530.0588666	total: 2.9s	remaining: 6.25s
355:	learn: 529.8765877	total: 2.91s	remaining: 6.24s
356:	learn: 529.7224989	total: 2.92s	remaining: 6.24s
357:	learn: 529.3293830	total: 2.93s	remaining: 6.23s
358:	learn: 529.1694816	total: 2.93s	remaining: 6.22s
359:	learn: 529.0083960	total: 2.94s	remaining: 6.21s
360:	learn: 528.8684602	total: 2.95s	remaining: 6.21s
361:	learn: 528.6937000	total: 2.96s	remaining: 6.2s
362:	learn: 528.3427242	total: 2.97s	remaining: 6.19s
363:	learn: 528.1658726	total: 2.98s	remaining: 6.18s
364:	learn: 528.0653100	total: 2.98s	remaining: 6.17s
365:	learn: 527.8534179	total: 2.99s	remaining: 6.16s
366:	learn: 527.6329506	total: 3s	remaining: 6.15s
367:	learn: 527.4135383	total: 3.01s	remaining: 6.15s
368:	learn: 527.2400624	total: 3.02s	remaining: 6.14s
369:	learn: 527.0931376	total: 3.02s	remaining: 6.13s
370:	learn: 526.9434470	total: 3.03s	remaining: 6.12s
371:	learn: 526.7099033	total: 3.04s	remaining: 6.11s

In [43]:
y_pred = cat_boost_regr.predict(X_regr_test_s)

In [44]:
print(f"MAE: {mean_absolute_error(y_regr_test, y_pred)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_regr_test, y_pred))}")
print(f"R²: {r2_score(y_regr_test, y_pred)}")
print(f"MAPE: {mean_absolute_percentage_error(y_regr_test, y_pred)}")

MAE: 260.87685572073605
RMSE: 488.90722325750124
R²: 0.9843177291847929
MAPE: 0.07417724345954956

## 3.3.2 CatBoost Classification

In [45]:
cat_boost_clas = CatBoostClassifier(**{'iterations': 1466, 'learning_rate': 0.004896927153059759, 'depth': 7, 'l2_leaf_reg': 0.0015223359176138216, 'border_count': 226, 'grow_policy': 'SymmetricTree'}, task_type='CPU', thread_count=-1, random_state=42)
cat_boost_clas.fit(X_clas_train_bs, y_clas_train_b)

0:	learn: 0.6772416	total: 339ms	remaining: 8m 17s
1:	learn: 0.6608511	total: 653ms	remaining: 7m 57s
2:	learn: 0.6458591	total: 945ms	remaining: 7m 40s
3:	learn: 0.6316009	total: 1.28s	remaining: 7m 46s
4:	learn: 0.6176963	total: 1.6s	remaining: 7m 47s
5:	learn: 0.6024611	total: 1.9s	remaining: 7m 41s
6:	learn: 0.5889067	total: 2.19s	remaining: 7m 36s
7:	learn: 0.5763887	total: 2.49s	remaining: 7m 34s
8:	learn: 0.5625848	total: 2.81s	remaining: 7m 34s
9:	learn: 0.5499552	total: 3.1s	remaining: 7m 31s
10:	learn: 0.5363127	total: 3.41s	remaining: 7m 31s
11:	learn: 0.5242585	total: 3.73s	remaining: 7m 32s
12:	learn: 0.5133988	total: 4.02s	remaining: 7m 29s
13:	learn: 0.5024243	total: 4.31s	remaining: 7m 27s
14:	learn: 0.4912066	total: 4.61s	remaining: 7m 26s
15:	learn: 0.4805218	total: 4.91s	remaining: 7m 25s
16:	learn: 0.4714394	total: 5.21s	remaining: 7m 23s
17:	learn: 0.4623794	total: 5.5s	remaining: 7m 22s
18:	learn: 0.4530581	total: 5.82s	remaining: 7m 23s
19:	learn: 0.4431384	total: 6.13s	remaining: 7m 23s
20:	learn: 0.4345610	total: 6.43s	remaining: 7m 22s
21:	learn: 0.4267225	total: 6.76s	remaining: 7m 23s
22:	learn: 0.4185724	total: 7.15s	remaining: 7m 28s
23:	learn: 0.4109749	total: 7.66s	remaining: 7m 40s
24:	learn: 0.4048348	total: 8.17s	remaining: 7m 51s
25:	learn: 0.3981051	total: 8.73s	remaining: 8m 3s
26:	learn: 0.3897802	total: 9.28s	remaining: 8m 14s
27:	learn: 0.3827261	total: 9.84s	remaining: 8m 25s
28:	learn: 0.3751585	total: 10.2s	remaining: 8m 27s
29:	learn: 0.3687351	total: 10.5s	remaining: 8m 24s
30:	learn: 0.3623698	total: 10.8s	remaining: 8m 21s
31:	learn: 0.3554075	total: 11.1s	remaining: 8m 19s
32:	learn: 0.3487385	total: 11.4s	remaining: 8m 17s
33:	learn: 0.3426937	total: 11.8s	remaining: 8m 15s
34:	learn: 0.3371575	total: 12.1s	remaining: 8m 13s
35:	learn: 0.3312936	total: 12.4s	remaining: 8m 11s
36:	learn: 0.3257833	total: 12.7s	remaining: 8m 10s
37:	learn: 0.3209290	total: 13s	remaining: 8m 9s
38:	learn: 0.3150975	total: 13.3s	remaining: 8m 7s
39:	learn: 0.3102557	total: 13.6s	remaining: 8m 5s
40:	learn: 0.3054082	total: 13.9s	remaining: 8m 4s
41:	learn: 0.3010409	total: 14.3s	remaining: 8m 3s
42:	learn: 0.2954182	total: 14.6s	remaining: 8m 1s
43:	learn: 0.2900042	total: 14.9s	remaining: 8m 1s
44:	learn: 0.2847859	total: 15.2s	remaining: 8m
45:	learn: 0.2811522	total: 15.6s	remaining: 8m
46:	learn: 0.2772824	total: 15.9s	remaining: 7m 59s
47:	learn: 0.2736517	total: 16.2s	remaining: 7m 58s
48:	learn: 0.2686785	total: 16.5s	remaining: 7m 57s
49:	learn: 0.2649302	total: 16.8s	remaining: 7m 56s
50:	learn: 0.2613198	total: 17.1s	remaining: 7m 55s
51:	learn: 0.2554192	total: 17.5s	remaining: 7m 55s
52:	learn: 0.2515820	total: 17.8s	remaining: 7m 54s
53:	learn: 0.2485509	total: 18.1s	remaining: 7m 53s
54:	learn: 0.2452614	total: 18.4s	remaining: 7m 52s
55:	learn: 0.2409208	total: 18.7s	remaining: 7m 51s
56:	learn: 0.2382383	total: 19s	remaining: 7m 50s
57:	learn: 0.2348432	total: 19.4s	remaining: 7m 49s
58:	learn: 0.2317094	total: 19.7s	remaining: 7m 49s
59:	learn: 0.2289339	total: 20s	remaining: 7m 48s
60:	learn: 0.2254415	total: 20.5s	remaining: 7m 51s
61:	learn: 0.2210949	total: 21s	remaining: 7m 55s
62:	learn: 0.2186242	total: 21.6s	remaining: 8m
63:	learn: 0.2163443	total: 22.1s	remaining: 8m 5s
64:	learn: 0.2140063	total: 22.8s	remaining: 8m 10s
65:	learn: 0.2111641	total: 23.3s	remaining: 8m 14s
66:	learn: 0.2086252	total: 23.6s	remaining: 8m 13s
67:	learn: 0.2063660	total: 23.9s	remaining: 8m 11s
68:	learn: 0.2029596	total: 24.2s	remaining: 8m 10s
69:	learn: 0.1999566	total: 24.5s	remaining: 8m 9s
70:	learn: 0.1975327	total: 24.9s	remaining: 8m 8s
71:	learn: 0.1945391	total: 25.2s	remaining: 8m 7s
72:	learn: 0.1924704	total: 25.5s	remaining: 8m 6s
73:	learn: 0.1901791	total: 25.8s	remaining: 8m 5s
74:	learn: 0.1881139	total: 26.1s	remaining: 8m 4s
75:	learn: 0.1854054	total: 26.4s	remaining: 8m 3s
76:	learn: 0.1835594	total: 26.7s	remaining: 8m 2s
77:	learn: 0.1816663	total: 27s	remaining: 8m 1s
78:	learn: 0.1789585	total: 27.3s	remaining: 8m
79:	learn: 0.1762455	total: 27.7s	remaining: 7m 59s
80:	learn: 0.1743607	total: 28s	remaining: 7m 58s
81:	learn: 0.1724386	total: 28.3s	remaining: 7m 57s
82:	learn: 0.1703904	total: 28.6s	remaining: 7m 56s
83:	learn: 0.1684936	total: 28.9s	remaining: 7m 55s
84:	learn: 0.1666795	total: 29.2s	remaining: 7m 54s
85:	learn: 0.1648208	total: 29.5s	remaining: 7m 53s
86:	learn: 0.1628165	total: 29.9s	remaining: 7m 53s
87:	learn: 0.1611289	total: 30.2s	remaining: 7m 53s
88:	learn: 0.1593861	total: 30.6s	remaining: 7m 53s
89:	learn: 0.1579535	total: 30.9s	remaining: 7m 52s
90:	learn: 0.1563647	total: 31.2s	remaining: 7m 51s
91:	learn: 0.1546652	total: 31.6s	remaining: 7m 51s
92:	learn: 0.1530266	total: 31.9s	remaining: 7m 50s
93:	learn: 0.1513671	total: 32.2s	remaining: 7m 50s
94:	learn: 0.1490559	total: 32.5s	remaining: 7m 49s
95:	learn: 0.1473239	total: 32.8s	remaining: 7m 48s
96:	learn: 0.1457812	total: 33.2s	remaining: 7m 47s
97:	learn: 0.1444269	total: 33.6s	remaining: 7m 48s
98:	learn: 0.1430938	total: 34.1s	remaining: 7m 51s
99:	learn: 0.1415554	total: 34.6s	remaining: 7m 53s
100:	learn: 0.1401171	total: 35.2s	remaining: 7m 55s
101:	learn: 0.1387735	total: 35.7s	remaining: 7m 57s
102:	learn: 0.1370801	total: 36.3s	remaining: 8m
103:	learn: 0.1355511	total: 36.6s	remaining: 7m 59s
104:	learn: 0.1342351	total: 37s	remaining: 7m 59s
105:	learn: 0.1330324	total: 37.3s	remaining: 7m 58s
106:	learn: 0.1314902	total: 37.6s	remaining: 7m 57s
107:	learn: 0.1303140	total: 37.9s	remaining: 7m 56s
108:	learn: 0.1289664	total: 38.2s	remaining: 7m 55s
109:	learn: 0.1272124	total: 38.5s	remaining: 7m 54s
110:	learn: 0.1259980	total: 38.8s	remaining: 7m 53s
111:	learn: 0.1249985	total: 39.1s	remaining: 7m 52s
112:	learn: 0.1237603	total: 39.4s	remaining: 7m 51s
113:	learn: 0.1227818	total: 39.7s	remaining: 7m 50s
114:	learn: 0.1217045	total: 40s	remaining: 7m 49s
115:	learn: 0.1206470	total: 40.3s	remaining: 7m 49s
116:	learn: 0.1195648	total: 40.6s	remaining: 7m 48s
117:	learn: 0.1185929	total: 40.9s	remaining: 7m 47s
118:	learn: 0.1177280	total: 41.2s	remaining: 7m 46s
119:	learn: 0.1162427	total: 41.5s	remaining: 7m 45s
120:	learn: 0.1153465	total: 41.8s	remaining: 7m 44s
121:	learn: 0.1144210	total: 42.1s	remaining: 7m 43s
122:	learn: 0.1134278	total: 42.4s	remaining: 7m 43s
123:	learn: 0.1123602	total: 42.7s	remaining: 7m 42s
124:	learn: 0.1113522	total: 43s	remaining: 7m 41s
125:	learn: 0.1103804	total: 43.4s	remaining: 7m 41s
126:	learn: 0.1096298	total: 43.7s	remaining: 7m 40s
127:	learn: 0.1087506	total: 44s	remaining: 7m 39s
128:	learn: 0.1073138	total: 44.3s	remaining: 7m 39s
129:	learn: 0.1064309	total: 44.6s	remaining: 7m 38s
130:	learn: 0.1056408	total: 44.9s	remaining: 7m 37s
131:	learn: 0.1048326	total: 45.2s	remaining: 7m 36s
132:	learn: 0.1039544	total: 45.5s	remaining: 7m 36s
133:	learn: 0.1029846	total: 45.8s	remaining: 7m 35s
134:	learn: 0.1015282	total: 46.1s	remaining: 7m 34s
135:	learn: 0.1008044	total: 46.5s	remaining: 7m 34s
136:	learn: 0.1000039	total: 47s	remaining: 7m 35s
137:	learn: 0.0991559	total: 47.6s	remaining: 7m 37s
138:	learn: 0.0985604	total: 48.1s	remaining: 7m 39s
139:	learn: 0.0978444	total: 48.7s	remaining: 7m 40s
140:	learn: 0.0970470	total: 49.2s	remaining: 7m 42s
141:	learn: 0.0964138	total: 49.6s	remaining: 7m 42s
142:	learn: 0.0957652	total: 49.9s	remaining: 7m 41s
143:	learn: 0.0951621	total: 50.2s	remaining: 7m 40s
144:	learn: 0.0940091	total: 50.5s	remaining: 7m 40s
145:	learn: 0.0933901	total: 50.8s	remaining: 7m 39s
146:	learn: 0.0922526	total: 51.1s	remaining: 7m 38s
147:	learn: 0.0915018	total: 51.5s	remaining: 7m 38s
148:	learn: 0.0906514	total: 51.8s	remaining: 7m 37s
149:	learn: 0.0899944	total: 52.1s	remaining: 7m 36s
150:	learn: 0.0894100	total: 52.4s	remaining: 7m 36s
151:	learn: 0.0883510	total: 52.7s	remaining: 7m 35s
152:	learn: 0.0878356	total: 53s	remaining: 7m 35s
153:	learn: 0.0868998	total: 53.4s	remaining: 7m 34s
154:	learn: 0.0860349	total: 53.7s	remaining: 7m 34s
155:	learn: 0.0855733	total: 54s	remaining: 7m 33s
156:	learn: 0.0850769	total: 54.3s	remaining: 7m 32s
157:	learn: 0.0843591	total: 54.6s	remaining: 7m 32s
158:	learn: 0.0838327	total: 54.9s	remaining: 7m 31s
159:	learn: 0.0831274	total: 55.3s	remaining: 7m 31s
160:	learn: 0.0825434	total: 55.6s	remaining: 7m 30s
161:	learn: 0.0816678	total: 55.9s	remaining: 7m 29s
162:	learn: 0.0808458	total: 56.2s	remaining: 7m 29s
163:	learn: 0.0803796	total: 56.5s	remaining: 7m 28s
164:	learn: 0.0799833	total: 56.9s	remaining: 7m 28s
165:	learn: 0.0793258	total: 57.2s	remaining: 7m 27s
166:	learn: 0.0786868	total: 57.5s	remaining: 7m 27s
167:	learn: 0.0779850	total: 57.8s	remaining: 7m 26s
168:	learn: 0.0773403	total: 58.1s	remaining: 7m 26s
169:	learn: 0.0766873	total: 58.5s	remaining: 7m 25s
170:	learn: 0.0762515	total: 58.8s	remaining: 7m 25s
171:	learn: 0.0756642	total: 59.1s	remaining: 7m 24s
172:	learn: 0.0749748	total: 59.4s	remaining: 7m 24s
173:	learn: 0.0745245	total: 59.8s	remaining: 7m 24s
174:	learn: 0.0740814	total: 1m	remaining: 7m 25s
175:	learn: 0.0735503	total: 1m	remaining: 7m 26s
176:	learn: 0.0730181	total: 1m 1s	remaining: 7m 28s
177:	learn: 0.0723586	total: 1m 2s	remaining: 7m 29s
178:	learn: 0.0718414	total: 1m 2s	remaining: 7m 30s
179:	learn: 0.0714662	total: 1m 3s	remaining: 7m 30s
180:	learn: 0.0709452	total: 1m 3s	remaining: 7m 29s
181:	learn: 0.0704546	total: 1m 3s	remaining: 7m 29s
182:	learn: 0.0700367	total: 1m 3s	remaining: 7m 28s
183:	learn: 0.0694906	total: 1m 4s	remaining: 7m 28s
184:	learn: 0.0690224	total: 1m 4s	remaining: 7m 27s
185:	learn: 0.0686027	total: 1m 4s	remaining: 7m 27s
186:	learn: 0.0681452	total: 1m 5s	remaining: 7m 26s
187:	learn: 0.0677630	total: 1m 5s	remaining: 7m 25s
188:	learn: 0.0675686	total: 1m 5s	remaining: 7m 25s
189:	learn: 0.0671187	total: 1m 6s	remaining: 7m 24s
190:	learn: 0.0668434	total: 1m 6s	remaining: 7m 24s
191:	learn: 0.0664340	total: 1m 6s	remaining: 7m 23s
192:	learn: 0.0660295	total: 1m 7s	remaining: 7m 23s
193:	learn: 0.0657385	total: 1m 7s	remaining: 7m 22s
194:	learn: 0.0653502	total: 1m 7s	remaining: 7m 22s
195:	learn: 0.0649619	total: 1m 8s	remaining: 7m 21s
196:	learn: 0.0647145	total: 1m 8s	remaining: 7m 21s
197:	learn: 0.0643780	total: 1m 8s	remaining: 7m 20s
198:	learn: 0.0640579	total: 1m 9s	remaining: 7m 20s
199:	learn: 0.0636284	total: 1m 9s	remaining: 7m 19s
200:	learn: 0.0633146	total: 1m 9s	remaining: 7m 19s
201:	learn: 0.0629955	total: 1m 10s	remaining: 7m 18s
202:	learn: 0.0625890	total: 1m 10s	remaining: 7m 18s
203:	learn: 0.0622836	total: 1m 10s	remaining: 7m 17s
204:	learn: 0.0619860	total: 1m 11s	remaining: 7m 17s
205:	learn: 0.0616961	total: 1m 11s	remaining: 7m 16s
206:	learn: 0.0613479	total: 1m 11s	remaining: 7m 16s
207:	learn: 0.0610515	total: 1m 12s	remaining: 7m 15s
208:	learn: 0.0607938	total: 1m 12s	remaining: 7m 15s
209:	learn: 0.0604837	total: 1m 12s	remaining: 7m 14s
210:	learn: 0.0601867	total: 1m 13s	remaining: 7m 14s
211:	learn: 0.0599174	total: 1m 13s	remaining: 7m 15s
212:	learn: 0.0596623	total: 1m 14s	remaining: 7m 16s
213:	learn: 0.0593488	total: 1m 14s	remaining: 7m 17s
214:	learn: 0.0590744	total: 1m 15s	remaining: 7m 18s
215:	learn: 0.0588631	total: 1m 15s	remaining: 7m 19s
216:	learn: 0.0585985	total: 1m 16s	remaining: 7m 18s
217:	learn: 0.0583606	total: 1m 16s	remaining: 7m 18s
218:	learn: 0.0581190	total: 1m 16s	remaining: 7m 17s
219:	learn: 0.0578897	total: 1m 17s	remaining: 7m 17s
220:	learn: 0.0576753	total: 1m 17s	remaining: 7m 16s
221:	learn: 0.0572425	total: 1m 17s	remaining: 7m 16s
222:	learn: 0.0570106	total: 1m 18s	remaining: 7m 15s
223:	learn: 0.0567147	total: 1m 18s	remaining: 7m 14s
224:	learn: 0.0565258	total: 1m 18s	remaining: 7m 14s
225:	learn: 0.0562625	total: 1m 19s	remaining: 7m 13s
226:	learn: 0.0559670	total: 1m 19s	remaining: 7m 13s
227:	learn: 0.0557361	total: 1m 19s	remaining: 7m 12s
228:	learn: 0.0555406	total: 1m 19s	remaining: 7m 11s
229:	learn: 0.0553475	total: 1m 20s	remaining: 7m 11s
230:	learn: 0.0551843	total: 1m 20s	remaining: 7m 10s
231:	learn: 0.0550020	total: 1m 20s	remaining: 7m 10s
232:	learn: 0.0547695	total: 1m 21s	remaining: 7m 9s
233:	learn: 0.0545142	total: 1m 21s	remaining: 7m 9s
234:	learn: 0.0540789	total: 1m 21s	remaining: 7m 8s
235:	learn: 0.0539085	total: 1m 22s	remaining: 7m 7s
236:	learn: 0.0537313	total: 1m 22s	remaining: 7m 7s
237:	learn: 0.0535179	total: 1m 22s	remaining: 7m 6s
238:	learn: 0.0533894	total: 1m 23s	remaining: 7m 6s
239:	learn: 0.0531945	total: 1m 23s	remaining: 7m 5s
240:	learn: 0.0529786	total: 1m 23s	remaining: 7m 5s
241:	learn: 0.0528276	total: 1m 23s	remaining: 7m 4s
242:	learn: 0.0526399	total: 1m 24s	remaining: 7m 4s
243:	learn: 0.0522818	total: 1m 24s	remaining: 7m 3s
244:	learn: 0.0521255	total: 1m 24s	remaining: 7m 2s
245:	learn: 0.0519126	total: 1m 25s	remaining: 7m 2s
246:	learn: 0.0517547	total: 1m 25s	remaining: 7m 1s
247:	learn: 0.0515837	total: 1m 25s	remaining: 7m 1s
248:	learn: 0.0514187	total: 1m 26s	remaining: 7m 1s
249:	learn: 0.0512391	total: 1m 26s	remaining: 7m 2s
250:	learn: 0.0511007	total: 1m 27s	remaining: 7m 2s
251:	learn: 0.0509738	total: 1m 27s	remaining: 7m 3s
252:	learn: 0.0508198	total: 1m 28s	remaining: 7m 3s
253:	learn: 0.0506492	total: 1m 28s	remaining: 7m 4s
254:	learn: 0.0505009	total: 1m 29s	remaining: 7m 4s
255:	learn: 0.0503539	total: 1m 29s	remaining: 7m 3s
256:	learn: 0.0501828	total: 1m 29s	remaining: 7m 2s
257:	learn: 0.0500525	total: 1m 30s	remaining: 7m 2s
258:	learn: 0.0498940	total: 1m 30s	remaining: 7m 1s
259:	learn: 0.0497721	total: 1m 30s	remaining: 7m 1s
260:	learn: 0.0496752	total: 1m 31s	remaining: 7m
261:	learn: 0.0494943	total: 1m 31s	remaining: 7m
262:	learn: 0.0493621	total: 1m 31s	remaining: 7m
263:	learn: 0.0492089	total: 1m 32s	remaining: 6m 59s
264:	learn: 0.0490927	total: 1m 32s	remaining: 6m 59s
265:	learn: 0.0489553	total: 1m 32s	remaining: 6m 58s
266:	learn: 0.0488245	total: 1m 33s	remaining: 6m 58s
267:	learn: 0.0486948	total: 1m 33s	remaining: 6m 57s
268:	learn: 0.0485364	total: 1m 33s	remaining: 6m 57s
269:	learn: 0.0484148	total: 1m 34s	remaining: 6m 56s
270:	learn: 0.0480955	total: 1m 34s	remaining: 6m 56s
271:	learn: 0.0479849	total: 1m 34s	remaining: 6m 55s
272:	learn: 0.0478616	total: 1m 35s	remaining: 6m 55s
273:	learn: 0.0477555	total: 1m 35s	remaining: 6m 54s
274:	learn: 0.0476237	total: 1m 35s	remaining: 6m 54s
275:	learn: 0.0473458	total: 1m 35s	remaining: 6m 53s
276:	learn: 0.0472103	total: 1m 36s	remaining: 6m 53s
277:	learn: 0.0470995	total: 1m 36s	remaining: 6m 52s
278:	learn: 0.0470024	total: 1m 36s	remaining: 6m 52s
279:	learn: 0.0468744	total: 1m 37s	remaining: 6m 51s
280:	learn: 0.0467612	total: 1m 37s	remaining: 6m 51s
281:	learn: 0.0466696	total: 1m 37s	remaining: 6m 50s
282:	learn: 0.0463794	total: 1m 38s	remaining: 6m 50s
283:	learn: 0.0462720	total: 1m 38s	remaining: 6m 49s
284:	learn: 0.0461591	total: 1m 38s	remaining: 6m 49s
285:	learn: 0.0460323	total: 1m 39s	remaining: 6m 48s
286:	learn: 0.0459350	total: 1m 39s	remaining: 6m 49s
287:	learn: 0.0458206	total: 1m 40s	remaining: 6m 49s
288:	learn: 0.0457330	total: 1m 40s	remaining: 6m 50s
289:	learn: 0.0456565	total: 1m 41s	remaining: 6m 50s
290:	learn: 0.0455535	total: 1m 41s	remaining: 6m 51s
291:	learn: 0.0454010	total: 1m 42s	remaining: 6m 51s
292:	learn: 0.0453246	total: 1m 42s	remaining: 6m 51s
293:	learn: 0.0452118	total: 1m 43s	remaining: 6m 50s
294:	learn: 0.0451412	total: 1m 43s	remaining: 6m 50s
295:	learn: 0.0449957	total: 1m 43s	remaining: 6m 49s
296:	learn: 0.0449142	total: 1m 43s	remaining: 6m 49s
297:	learn: 0.0448494	total: 1m 44s	remaining: 6m 48s
298:	learn: 0.0447479	total: 1m 44s	remaining: 6m 47s
299:	learn: 0.0445449	total: 1m 44s	remaining: 6m 47s
300:	learn: 0.0444818	total: 1m 45s	remaining: 6m 46s
301:	learn: 0.0442710	total: 1m 45s	remaining: 6m 46s
302:	learn: 0.0441515	total: 1m 45s	remaining: 6m 45s
303:	learn: 0.0440427	total: 1m 46s	remaining: 6m 45s
304:	learn: 0.0438417	total: 1m 46s	remaining: 6m 44s
305:	learn: 0.0437621	total: 1m 46s	remaining: 6m 44s
306:	learn: 0.0436240	total: 1m 46s	remaining: 6m 43s
307:	learn: 0.0435606	total: 1m 47s	remaining: 6m 43s
308:	learn: 0.0434411	total: 1m 47s	remaining: 6m 43s
309:	learn: 0.0433709	total: 1m 47s	remaining: 6m 42s
310:	learn: 0.0433086	total: 1m 48s	remaining: 6m 41s
311:	learn: 0.0431921	total: 1m 48s	remaining: 6m 41s
312:	learn: 0.0430402	total: 1m 48s	remaining: 6m 40s
313:	learn: 0.0429768	total: 1m 49s	remaining: 6m 40s
314:	learn: 0.0428626	total: 1m 49s	remaining: 6m 39s
315:	learn: 0.0428084	total: 1m 49s	remaining: 6m 39s
316:	learn: 0.0427460	total: 1m 49s	remaining: 6m 38s
317:	learn: 0.0425890	total: 1m 50s	remaining: 6m 38s
318:	learn: 0.0424815	total: 1m 50s	remaining: 6m 37s
319:	learn: 0.0424237	total: 1m 50s	remaining: 6m 37s
320:	learn: 0.0423320	total: 1m 51s	remaining: 6m 36s
321:	learn: 0.0422464	total: 1m 51s	remaining: 6m 36s
322:	learn: 0.0420733	total: 1m 51s	remaining: 6m 35s
323:	learn: 0.0420213	total: 1m 52s	remaining: 6m 35s
324:	learn: 0.0419336	total: 1m 52s	remaining: 6m 35s
325:	learn: 0.0418803	total: 1m 53s	remaining: 6m 35s
326:	learn: 0.0418160	total: 1m 53s	remaining: 6m 36s
327:	learn: 0.0416681	total: 1m 54s	remaining: 6m 37s
328:	learn: 0.0415756	total: 1m 55s	remaining: 6m 37s
329:	learn: 0.0415176	total: 1m 55s	remaining: 6m 37s
330:	learn: 0.0414535	total: 1m 55s	remaining: 6m 37s
331:	learn: 0.0414031	total: 1m 56s	remaining: 6m 36s
332:	learn: 0.0413438	total: 1m 56s	remaining: 6m 36s
333:	learn: 0.0411924	total: 1m 56s	remaining: 6m 35s
334:	learn: 0.0411129	total: 1m 57s	remaining: 6m 35s
335:	learn: 0.0410121	total: 1m 57s	remaining: 6m 34s
336:	learn: 0.0409538	total: 1m 57s	remaining: 6m 34s
337:	learn: 0.0409015	total: 1m 57s	remaining: 6m 33s
338:	learn: 0.0408363	total: 1m 58s	remaining: 6m 33s
339:	learn: 0.0407806	total: 1m 58s	remaining: 6m 32s
340:	learn: 0.0407275	total: 1m 58s	remaining: 6m 32s
341:	learn: 0.0406706	total: 1m 59s	remaining: 6m 31s
342:	learn: 0.0405065	total: 1m 59s	remaining: 6m 31s
343:	learn: 0.0404190	total: 1m 59s	remaining: 6m 30s
344:	learn: 0.0403469	total: 2m	remaining: 6m 30s
345:	learn: 0.0401744	total: 2m	remaining: 6m 29s
346:	learn: 0.0400805	total: 2m	remaining: 6m 29s
347:	learn: 0.0400403	total: 2m 1s	remaining: 6m 28s
348:	learn: 0.0399848	total: 2m 1s	remaining: 6m 28s
349:	learn: 0.0399389	total: 2m 1s	remaining: 6m 27s
350:	learn: 0.0398792	total: 2m 1s	remaining: 6m 27s
351:	learn: 0.0397811	total: 2m 2s	remaining: 6m 27s
352:	learn: 0.0397396	total: 2m 2s	remaining: 6m 26s
353:	learn: 0.0396972	total: 2m 2s	remaining: 6m 26s
354:	learn: 0.0396522	total: 2m 3s	remaining: 6m 25s
355:	learn: 0.0395984	total: 2m 3s	remaining: 6m 25s
356:	learn: 0.0395304	total: 2m 3s	remaining: 6m 25s
357:	learn: 0.0394276	total: 2m 4s	remaining: 6m 24s
358:	learn: 0.0392834	total: 2m 4s	remaining: 6m 24s
359:	learn: 0.0392415	total: 2m 4s	remaining: 6m 23s
360:	learn: 0.0391939	total: 2m 5s	remaining: 6m 23s
361:	learn: 0.0391368	total: 2m 5s	remaining: 6m 22s
362:	learn: 0.0390918	total: 2m 6s	remaining: 6m 23s
363:	learn: 0.0389977	total: 2m 6s	remaining: 6m 23s
364:	learn: 0.0389583	total: 2m 7s	remaining: 6m 23s
365:	learn: 0.0389082	total: 2m 7s	remaining: 6m 24s
366:	learn: 0.0388683	total: 2m 8s	remaining: 6m 24s
367:	learn: 0.0387987	total: 2m 8s	remaining: 6m 23s
368:	learn: 0.0387459	total: 2m 8s	remaining: 6m 23s
369:	learn: 0.0387071	total: 2m 9s	remaining: 6m 22s
370:	learn: 0.0385990	total: 2m 9s	remaining: 6m 22s
371:	learn: 0.0385555	total: 2m 9s	remaining: 6m 22s
372:	learn: 0.0385279	total: 2m 10s	remaining: 6m 21s
373:	learn: 0.0384863	total: 2m 10s	remaining: 6m 21s
374:	learn: 0.0384106	total: 2m 10s	remaining: 6m 20s
375:	learn: 0.0383657	total: 2m 11s	remaining: 6m 20s
376:	learn: 0.0383248	total: 2m 11s	remaining: 6m 19s
377:	learn: 0.0382806	total: 2m 11s	remaining: 6m 19s

In [46]:
y_pred = cat_boost_clas.predict(X_clas_test_s)

In [47]:
print(classification_report(y_clas_test, y_pred))
accuracy_score(y_clas_test, y_pred)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    182519
           1       0.89      1.00      0.94     17481

    accuracy                           0.99    200000
   macro avg       0.95      0.99      0.97    200000
weighted avg       0.99      0.99      0.99    200000

0.989575

## 3.3.3 XGBoost Regression

In [48]:
xgboost_regr = XGBRegressor(**{'n_estimators': 773, 'max_depth': 7, 'learning_rate': 0.017064549414664634, 'subsample': 0.7747701428698828, 'colsample_bytree': 0.7899746430902906, 'gamma': 0.12319436780270282, 'reg_alpha': 0.009642742572935563, 'reg_lambda': 0.12610503197436898}, random_state=42, n_jobs=-1)
xgboost_regr.fit(X_regr_train_s, y_regr_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.7899746430902906, device=None,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0.12319436780270282,
             grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.017064549414664634,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=7, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=773, n_jobs=-1,
             num_parallel_tree=None, objective='reg:squarederror', ...)

In [49]:
y_pred = xgboost_regr.predict(X_regr_test_s)

In [50]:
print(f"MAE: {mean_absolute_error(y_regr_test, y_pred)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_regr_test, y_pred))}")
print(f"R²: {r2_score(y_regr_test, y_pred)}")
print(f"MAPE: {mean_absolute_percentage_error(y_regr_test, y_pred)}")

MAE: 256.7457918815425
RMSE: 496.9632928025655
R²: 0.9837966555165921
MAPE: 0.07159865212268225

## 3.3.4 XGBoost Classification

In [51]:
xgboost_clas = XGBClassifier(**{'n_estimators': 160, 'max_depth': 5, 'learning_rate': 0.03380924770634301, 'subsample': 0.8674150272975121, 'colsample_bytree': 0.9553110238818484, 'gamma': 0.2949825966699646, 'reg_alpha': 0.014787616897752608, 'reg_lambda': 1.4126794376806364})
xgboost_clas.fit(X_clas_train_bs, y_clas_train_b)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9553110238818484, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0.2949825966699646,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03380924770634301,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=160, n_jobs=None,
              num_parallel_tree=None, objective='binary:logistic', ...)

In [52]:
y_pred = xgboost_clas.predict(X_clas_test_s)

In [53]:
print(classification_report(y_clas_test, y_pred))
accuracy_score(y_clas_test, y_pred)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    182519
           1       0.89      1.00      0.94     17481

    accuracy                           0.99    200000
   macro avg       0.95      0.99      0.97    200000
weighted avg       0.99      0.99      0.99    200000

0.98956

## 3.3.5 LightGBM Regression

In [54]:
light_gbm_regr = LGBMRegressor(**{'n_estimators': 674, 'max_depth': 6, 'learning_rate': 0.014215547294580726, 'num_leaves': 244, 'min_child_samples': 8, 'subsample': 0.959970948373626, 'colsample_bytree': 0.7036459616308876, 'reg_alpha': 0.003675639993320709, 'reg_lambda': 0.2428815144688183}, force_col_wise=True)
light_gbm_regr.fit(X_regr_train_s, y_regr_train)

[LightGBM] [Info] Total Bins 1286
[LightGBM] [Info] Number of data points in the train set: 43035, number of used features: 9
[LightGBM] [Info] Start training from score 3944.883235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(boosting_type='gbdt', class_weight=None,
              colsample_bytree=0.7036459616308876, force_col_wise=True,
              importance_type='split', learning_rate=0.014215547294580726,
              max_depth=6, min_child_samples=8, min_child_weight=0.001,
              min_split_gain=0.0, n_estimators=674, n_jobs=None, num_leaves=244,
              objective=None, random_state=None, reg_alpha=0.003675639993320709,
              reg_lambda=0.2428815144688183, subsample=0.959970948373626,
              subsample_for_bin=200000, subsample_freq=0)

In [55]:
y_pred = light_gbm_regr.predict(X_regr_test_s)

In [56]:
print(f"MAE: {mean_absolute_error(y_regr_test, y_pred)}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_regr_test, y_pred))}")
print(f"R²: {r2_score(y_regr_test, y_pred)}")
print(f"MAPE: {mean_absolute_percentage_error(y_regr_test, y_pred)}")

MAE: 262.7696672879388
RMSE: 496.1804970901989
R²: 0.9838476609698762
MAPE: 0.07648626310468114

## 3.3.6 LightGBM Classification

In [57]:
light_gbm_clas = LGBMClassifier(**{'n_estimators': 378, 'max_depth': 4, 'learning_rate': 0.045472411633406845, 'num_leaves': 167, 'min_child_samples': 15, 'subsample': 0.787300997249121, 'colsample_bytree': 0.8020043291010864, 'reg_alpha': 0.6629728220339912, 'reg_lambda': 0.12603478242435429}, force_col_wise=True)
light_gbm_clas.fit(X_clas_train_bs, y_clas_train_b)

[LightGBM] [Info] Number of positive: 730078, number of negative: 730078
[LightGBM] [Info] Total Bins 1032
[LightGBM] [Info] Number of data points in the train set: 1460156, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(boosting_type='gbdt', class_weight=None,
               colsample_bytree=0.8020043291010864, force_col_wise=True,
               importance_type='split', learning_rate=0.045472411633406845,
               max_depth=4, min_child_samples=15, min_child_weight=0.001,
               min_split_gain=0.0, n_estimators=378, n_jobs=None,
               num_leaves=167, objective=None, random_state=None,
               reg_alpha=0.6629728220339912, reg_lambda=0.12603478242435429,
               subsample=0.787300997249121, subsample_for_bin=200000,
               subsample_freq=0)

In [58]:
y_pred = light_gbm_clas.predict(X_clas_test_s)

In [59]:
print(classification_report(y_clas_test, y_pred))
accuracy_score(y_clas_test, y_pred)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    182519
           1       0.90      1.00      0.95     17481

    accuracy                           0.99    200000
   macro avg       0.95      0.99      0.97    200000
weighted avg       0.99      0.99      0.99    200000

0.990095

## 3.3.7 ScetchBoost

**ScetchBoost** - часть экспериментальной библиотеки _sketchboost-paper_, которая является "расширенной" версией _py-boost_ под авторством Сбера. Я ознакомился с этим алгоритмом, а так же посмотрел вебинар-презентацию этого алгоритма, включая мотивации его создания и его результаты работы. Использовать на своём устройстве я не могу, так как требуются высокие вычислительные мощности GPU на основе NVIDIA, которыми моё устройство не обладает

## 3.4 Объединение моделей

In [60]:
models_regr = {'DecisionTreeRegressor': des_tree_regr,
               'BaggingRegressor': ens_bag_regr,
               'GradientBoostingRegressor': gb_regr,
               'StackingRegressor': stack_regr,
               'CatBoostRegressor': cat_boost_regr,
               'XGBoostRegressor': xgboost_regr,
               'LightGBMRegressor': light_gbm_regr}

models_clas = {'clas_DecisionTreeClassifier': des_tree_clas,
               'clas_BaggingClassifier': ens_bag_clas,
               'GradientBoostingClassifier': gb_clas,
               'StackingClassifier': stack_clas,
               'CatBoostClassifier': cat_boost_clas,
               'XGBoostClassifier': xgboost_clas,
               'LightGBMClassifier': light_gbm_clas}

# 4. Визуализация

In [61]:
def print_tree_rules_regressor(model, feature_names):
    tree_rules = export_text(
        model,
        feature_names=list(feature_names),
        spacing=3,
        decimals=2
    )
    print("Решающие правила для DecisionTreeRegressor:")
    print(tree_rules)

print_tree_rules_regressor(
    models_regr['DecisionTreeRegressor'],
    feature_names=X_regr.columns
)

Решающие правила для DecisionTreeRegressor:
|--- carat <= 0.41
|   |--- y <= -0.18
|   |   |--- carat <= -0.72
|   |   |   |--- x <= -1.01
|   |   |   |   |--- clarity <= -1.49
|   |   |   |   |   |--- carat <= -1.06
|   |   |   |   |   |   |--- carat <= -1.14
|   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |--- color <= -0.06
|   |   |   |   |   |   |   |   |   |--- x <= -1.54
|   |   |   |   |   |   |   |   |   |   |--- value: [634.45]
|   |   |   |   |   |   |   |   |   |--- x >  -1.54
|   |   |   |   |   |   |   |   |   |   |--- depth <= -0.49
|   |   |   |   |   |   |   |   |   |   |   |--- value: [669.82]
|   |   |   |   |   |   |   |   |   |   |--- depth >  -0.49
|   |   |   |   |   |   |   |   |   |   |   |--- value: [744.00]
|   |   |   |   |   |   |   |   |--- color >  -0.06
|   |   |   |   |   |   |   |   |   |--- color <= 0.53
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.57
|   |   |   |   |   |   |   |   |   |   |   |--- value: [537.62]
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.57
|   |   |   |   |   |   |   |   |   |   |   |--- value: [570.21]
|   |   |   |   |   |   |   |   |   |--- color >  0.53
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.54
|   |   |   |   |   |   |   |   |   |   |   |--- value: [456.90]
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.54
|   |   |   |   |   |   |   |   |   |   |   |--- value: [534.89]
|   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |--- z <= -1.55
|   |   |   |   |   |   |   |   |   |--- color <= -0.06
|   |   |   |   |   |   |   |   |   |   |--- y <= -1.45
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- y >  -1.45
|   |   |   |   |   |   |   |   |   |   |   |--- value: [537.14]
|   |   |   |   |   |   |   |   |   |--- color >  -0.06
|   |   |   |   |   |   |   |   |   |   |--- value: [447.64]
|   |   |   |   |   |   |   |   |--- z >  -1.55
|   |   |   |   |   |   |   |   |   |--- x <= -1.57
|   |   |   |   |   |   |   |   |   |   |--- table <= -0.43
|   |   |   |   |   |   |   |   |   |   |   |--- value: [525.38]
|   |   |   |   |   |   |   |   |   |   |--- table >  -0.43
|   |   |   |   |   |   |   |   |   |   |   |--- value: [501.86]
|   |   |   |   |   |   |   |   |   |--- x >  -1.57
|   |   |   |   |   |   |   |   |   |   |--- color <= -0.06
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- color >  -0.06
|   |   |   |   |   |   |   |   |   |   |   |--- value: [496.60]
|   |   |   |   |   |   |--- carat >  -1.14
|   |   |   |   |   |   |   |--- color <= -0.06
|   |   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |   |--- x <= -1.36
|   |   |   |   |   |   |   |   |   |   |--- depth <= 0.42
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- depth >  0.42
|   |   |   |   |   |   |   |   |   |   |   |--- value: [786.12]
|   |   |   |   |   |   |   |   |   |--- x >  -1.36
|   |   |   |   |   |   |   |   |   |   |--- value: [794.87]
|   |   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |   |--- y <= -1.28
|   |   |   |   |   |   |   |   |   |   |--- z <= -1.42
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- z >  -1.42
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- y >  -1.28
|   |   |   |   |   |   |   |   |   |   |--- value: [678.85]
|   |   |   |   |   |   |   |--- color >  -0.06
|   |   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |   |--- color <= 0.53
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.35
|   |   |   |   |   |   |   |   |   |   |   |--- value: [619.69]
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.35
|   |   |   |   |   |   |   |   |   |   |   |--- value: [658.50]
|   |   |   |   |   |   |   |   |   |--- color >  0.53
|   |   |   |   |   |   |   |   |   |   |--- value: [582.07]
|   |   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |   |--- z <= -1.41
|   |   |   |   |   |   |   |   |   |   |--- value: [515.22]
|   |   |   |   |   |   |   |   |   |--- z >  -1.41
|   |   |   |   |   |   |   |   |   |   |--- value: [565.17]
|   |   |   |   |   |--- carat >  -1.06
|   |   |   |   |   |   |--- color <= 0.53
|   |   |   |   |   |   |   |--- x <= -1.17
|   |   |   |   |   |   |   |   |--- clarity <= -2.10
|   |   |   |   |   |   |   |   |   |--- color <= -0.64
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.25
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.25
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- color >  -0.64
|   |   |   |   |   |   |   |   |   |   |--- carat <= -1.04
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- carat >  -1.04
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- clarity >  -2.10
|   |   |   |   |   |   |   |   |   |--- color <= -1.23
|   |   |   |   |   |   |   |   |   |   |--- depth <= 0.14
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- depth >  0.14
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- color >  -1.23
|   |   |   |   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- x >  -1.17
|   |   |   |   |   |   |   |   |--- color <= -1.23
|   |   |   |   |   |   |   |   |   |--- x <= -1.09
|   |   |   |   |   |   |   |   |   |   |--- value: [1176.17]
|   |   |   |   |   |   |   |   |   |--- x >  -1.09
|   |   |   |   |   |   |   |   |   |   |--- value: [1404.54]
|   |   |   |   |   |   |   |   |--- color >  -1.23
|   |   |   |   |   |   |   |   |   |--- color <= -0.64
|   |   |   |   |   |   |   |   |   |   |--- table <= 0.47
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- table >  0.47
|   |   |   |   |   |   |   |   |   |   |   |--- value: [905.64]
|   |   |   |   |   |   |   |   |   |--- color >  -0.64
|   |   |   |   |   |   |   |   |   |   |--- clarity <= -2.10
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- clarity >  -2.10
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |--- color >  0.53
|   |   |   |   |   |   |   |--- color <= 1.12
|   |   |   |   |   |   |   |   |--- x <= -1.18
|   |   |   |   |   |   |   |   |   |--- clarity <= -2.10
|   |   |   |   |   |   |   |   |   |   |--- depth <= -0.35
|   |   |   |   |   |   |   |   |   |   |   |--- value: [885.36]
|   |   |   |   |   |   |   |   |   |   |--- depth >  -0.35
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- clarity >  -2.10
|   |   |   |   |   |   |   |   |   |   |--- y <= -1.21
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- y >  -1.21
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- x >  -1.18
|   |   |   |   |   |   |   |   |   |--- y <= -1.14
|   |   |   |   |   |   |   |   |   |   |--- clarity <= -2.10
|   |   |   |   |   |   |   |   |   |   |   |--- value: [1056.10]
|   |   |   |   |   |   |   |   |   |   |--- clarity >  -2.10
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- y >  -1.14
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.14
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.14
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- color >  1.12
|   |   |   |   |   |   |   |   |--- color <= 1.71
|   |   |   |   |   |   |   |   |   |--- x <= -1.19
|   |   |   |   |   |   |   |   |   |   |--- clarity <= -2.10
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- clarity >  -2.10
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- x >  -1.19
|   |   |   |   |   |   |   |   |   |   |--- y <= -1.14
|   |   |   |   |   |   |   |   |   |   |   |--- value: [793.15]
|   |   |   |   |   |   |   |   |   |   |--- y >  -1.14
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- color >  1.71
|   |   |   |   |   |   |   |   |   |--- clarity <= -2.10
|   |   |   |   |   |   |   |   |   |   |--- value: [579.90]
|   |   |   |   |   |   |   |   |   |--- clarity >  -2.10
|   |   |   |   |   |   |   |   |   |   |--- value: [496.25]
|   |   |   |   |--- clarity >  -1.49
|   |   |   |   |   |--- color <= 0.53
|   |   |   |   |   |   |--- x <= -1.32
|   |   |   |   |   |   |   |--- clarity <= -0.88
|   |   |   |   |   |   |   |   |--- x <= -1.50
|   |   |   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |   |   |--- cut <= -0.53
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- cut >  -0.53
|   |   |   |   |   |   |   |   |   |   |   |--- value: [627.20]
|   |   |   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |   |   |--- color <= -0.06
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- color >  -0.06
|   |   |   |   |   |   |   |   |   |   |   |--- value: [432.80]
|   |   |   |   |   |   |   |   |--- x >  -1.50
|   |   |   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |   |   |--- color <= -0.06
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- color >  -0.06
|   |   |   |   |   |   |   |   |   |   |   |--- value: [583.08]
|   |   |   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |   |   |--- carat <= -1.06
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- carat >  -1.06
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- clarity >  -0.88
|   |   |   |   |   |   |   |   |--- x <= -1.41
|   |   |   |   |   |   |   |   |   |--- z <= -1.61
|   |   |   |   |   |   |   |   |   |   |--- z <= -1.74
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- z >  -1.74
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- z >  -1.61
|   |   |   |   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- x >  -1.41
|   |   |   |   |   |   |   |   |   |--- carat <= -1.06
|   |   |   |   |   |   |   |   |   |   |--- y <= -1.35
|   |   |   |   |   |   |   |   |   |   |   |--- value: [591.17]
|   |   |   |   |   |   |   |   |   |   |--- y >  -1.35
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- carat >  -1.06
|   |   |   |   |   |   |   |   |   |   |--- clarity <= 0.33
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- clarity >  0.33
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |--- x >  -1.32
|   |   |   |   |   |   |   |--- clarity <= 0.33
|   |   |   |   |   |   |   |   |--- color <= -0.64
|   |   |   |   |   |   |   |   |   |--- x <= -1.18
|   |   |   |   |   |   |   |   |   |   |--- clarity <= -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- clarity >  -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- x >  -1.18
|   |   |   |   |   |   |   |   |   |   |--- cut <= 0.36
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- cut >  0.36
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- color >  -0.64
|   |   |   |   |   |   |   |   |   |--- clarity <= -0.88
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.17
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.17
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- clarity >  -0.88
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.18
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.18
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- clarity >  0.33
|   |   |   |   |   |   |   |   |--- clarity <= 0.94
|   |   |   |   |   |   |   |   |   |--- color <= -0.64
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.17
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.17
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- color >  -0.64
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.17
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.17
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- clarity >  0.94
|   |   |   |   |   |   |   |   |   |--- x <= -1.14
|   |   |   |   |   |   |   |   |   |   |--- color <= -1.23
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- color >  -1.23
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- x >  -1.14
|   |   |   |   |   |   |   |   |   |   |--- y <= -1.09
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- y >  -1.09
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |--- color >  0.53
|   |   |   |   |   |   |--- clarity <= -0.27
|   |   |   |   |   |   |   |--- x <= -1.27
|   |   |   |   |   |   |   |   |--- x <= -1.33
|   |   |   |   |   |   |   |   |   |--- x <= -1.54
|   |   |   |   |   |   |   |   |   |   |--- value: [388.69]
|   |   |   |   |   |   |   |   |   |--- x >  -1.54
|   |   |   |   |   |   |   |   |   |   |--- clarity <= -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- clarity >  -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- x >  -1.33
|   |   |   |   |   |   |   |   |   |--- y <= -1.28
|   |   |   |   |   |   |   |   |   |   |--- clarity <= -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- value: [774.78]
|   |   |   |   |   |   |   |   |   |   |--- clarity >  -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- y >  -1.28
|   |   |   |   |   |   |   |   |   |   |--- color <= 1.12
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- color >  1.12
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- x >  -1.27
|   |   |   |   |   |   |   |   |--- color <= 1.12
|   |   |   |   |   |   |   |   |   |--- clarity <= -0.88
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.23
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.23
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- clarity >  -0.88
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.14
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.14
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- color >  1.12
|   |   |   |   |   |   |   |   |   |--- color <= 1.71
|   |   |   |   |   |   |   |   |   |   |--- clarity <= -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- clarity >  -0.88
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- color >  1.71
|   |   |   |   |   |   |   |   |   |   |--- depth <= 0.53
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- depth >  0.53
|   |   |   |   |   |   |   |   |   |   |   |--- value: [542.11]
|   |   |   |   |   |   |--- clarity >  -0.27
|   |   |   |   |   |   |   |--- x <= -1.21
|   |   |   |   |   |   |   |   |--- color <= 1.12
|   |   |   |   |   |   |   |   |   |--- clarity <= 0.33
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.31
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.31
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- clarity >  0.33
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.31
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.31
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- color >  1.12
|   |   |   |   |   |   |   |   |   |--- x <= -1.26
|   |   |   |   |   |   |   |   |   |   |--- y <= -1.29
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- y >  -1.29
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- x >  -1.26
|   |   |   |   |   |   |   |   |   |   |--- y <= -1.22
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- y >  -1.22
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- x >  -1.21
|   |   |   |   |   |   |   |   |--- color <= 1.12
|   |   |   |   |   |   |   |   |   |--- clarity <= 0.94
|   |   |   |   |   |   |   |   |   |   |--- x <= -1.11
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- x >  -1.11

In [62]:
def print_tree_rules_classifier(model, feature_names, class_names):
    tree_rules = export_text(
        model,
        feature_names=list(feature_names),
        class_names=class_names,
        spacing=3,
        decimals=2
    )
    print("Решающие правила для DecisionTreeClassifier:")
    print(tree_rules)

print_tree_rules_classifier(
    models_clas['clas_DecisionTreeClassifier'],
    feature_names=X_clas.columns,
    class_names=['0', '1']
)

Решающие правила для DecisionTreeClassifier:
|--- ratio_to_median_purchase_price <= 0.04
|   |--- distance_from_home <= 0.61
|   |   |--- distance_from_last_transaction <= 0.75
|   |   |   |--- ratio_to_median_purchase_price <= -0.35
|   |   |   |   |--- distance_from_home <= 0.27
|   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.40
|   |   |   |   |   |   |--- distance_from_home <= 0.16
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_home >  0.16
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.40
|   |   |   |   |   |   |--- distance_from_last_transaction <= 0.62
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_last_transaction >  0.62
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- distance_from_home >  0.27
|   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.58
|   |   |   |   |   |   |--- distance_from_home <= 0.49
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_home >  0.49
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.58
|   |   |   |   |   |   |--- used_chip <= 0.65
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- used_chip >  0.65
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- ratio_to_median_purchase_price >  -0.35
|   |   |   |   |--- distance_from_home <= 0.09
|   |   |   |   |   |--- distance_from_last_transaction <= 0.19
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.12
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.12
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_last_transaction >  0.19
|   |   |   |   |   |   |--- used_chip <= 0.65
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- used_chip >  0.65
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- distance_from_home >  0.09
|   |   |   |   |   |--- used_chip <= 0.65
|   |   |   |   |   |   |--- online_order <= -0.62
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- online_order >  -0.62
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- used_chip >  0.65
|   |   |   |   |   |   |--- distance_from_last_transaction <= 0.19
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_last_transaction >  0.19
|   |   |   |   |   |   |   |--- class: 0
|   |   |--- distance_from_last_transaction >  0.75
|   |   |   |--- used_chip <= 0.65
|   |   |   |   |--- online_order <= -0.62
|   |   |   |   |   |--- repeat_retailer <= -0.91
|   |   |   |   |   |   |--- distance_from_home <= -0.44
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_home >  -0.44
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- repeat_retailer >  -0.91
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.38
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.38
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- online_order >  -0.62
|   |   |   |   |   |--- distance_from_last_transaction <= 1.46
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.55
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.55
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- distance_from_last_transaction >  1.46
|   |   |   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- used_chip >  0.65
|   |   |   |   |--- repeat_retailer <= -0.91
|   |   |   |   |   |--- distance_from_home <= -0.44
|   |   |   |   |   |   |--- distance_from_last_transaction <= 1.46
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_last_transaction >  1.46
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- distance_from_home >  -0.44
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- repeat_retailer >  -0.91
|   |   |   |   |   |--- distance_from_home <= 0.18
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_home >  0.18
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.41
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.41
|   |   |   |   |   |   |   |--- class: 0
|   |--- distance_from_home >  0.61
|   |   |--- used_chip <= 0.65
|   |   |   |--- online_order <= -0.62
|   |   |   |   |--- ratio_to_median_purchase_price <= -0.57
|   |   |   |   |   |--- distance_from_last_transaction <= 0.62
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.76
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.76
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_last_transaction >  0.62
|   |   |   |   |   |   |--- distance_from_last_transaction <= 1.46
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- distance_from_last_transaction >  1.46
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- ratio_to_median_purchase_price >  -0.57
|   |   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |   |--- distance_from_home <= 0.72
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_home >  0.72
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |   |--- class: 0
|   |   |   |--- online_order >  -0.62
|   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |--- distance_from_home <= 0.69
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.65
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.65
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- distance_from_home >  0.69
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |--- class: 0
|   |   |--- used_chip >  0.65
|   |   |   |--- distance_from_last_transaction <= 1.41
|   |   |   |   |--- distance_from_last_transaction <= 0.57
|   |   |   |   |   |--- ratio_to_median_purchase_price <= 0.02
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- ratio_to_median_purchase_price >  0.02
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= 0.02
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  0.02
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- distance_from_last_transaction >  0.57
|   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.22
|   |   |   |   |   |   |--- ratio_to_median_purchase_price <= -0.57
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.57
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- ratio_to_median_purchase_price >  -0.22
|   |   |   |   |   |   |--- distance_from_home <= 2.90
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- distance_from_home >  2.90
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- distance_from_last_transaction >  1.41
|   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |--- distance_from_home <= 0.69
|   |   |   |   |   |   |--- Unnamed: 0 <= -0.82
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- Unnamed: 0 >  -0.82
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_home >  0.69
|   |   |   |   |   |   |--- distance_from_last_transaction <= 1.47
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_last_transaction >  1.47
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |--- class: 0
|--- ratio_to_median_purchase_price >  0.04
|   |--- online_order <= -0.62
|   |   |--- repeat_retailer <= -0.91
|   |   |   |--- used_chip <= 0.65
|   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |--- class: 0
|   |   |   |--- used_chip >  0.65
|   |   |   |   |--- distance_from_home <= -0.44
|   |   |   |   |   |--- distance_from_last_transaction <= 1.45
|   |   |   |   |   |   |--- distance_from_last_transaction <= 0.18
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_last_transaction >  0.18
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_last_transaction >  1.45
|   |   |   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- distance_from_home >  -0.44
|   |   |   |   |   |--- class: 1
|   |   |--- repeat_retailer >  -0.91
|   |   |   |--- distance_from_home <= 0.69
|   |   |   |   |--- distance_from_last_transaction <= 0.64
|   |   |   |   |   |--- distance_from_home <= 0.03
|   |   |   |   |   |   |--- distance_from_last_transaction <= 0.12
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- distance_from_last_transaction >  0.12
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_home >  0.03
|   |   |   |   |   |   |--- used_chip <= 0.65
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- used_chip >  0.65
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- distance_from_last_transaction >  0.64
|   |   |   |   |   |--- distance_from_last_transaction <= 1.46
|   |   |   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_last_transaction >  1.46
|   |   |   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- distance_from_home >  0.69
|   |   |   |   |--- used_pin_number <= 1.95
|   |   |   |   |   |--- distance_from_home <= 0.69
|   |   |   |   |   |   |--- distance_from_home <= 0.69
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- distance_from_home >  0.69
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_home >  0.69
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- used_pin_number >  1.95
|   |   |   |   |   |--- class: 0
|   |--- online_order >  -0.62
|   |   |--- used_pin_number <= 1.95
|   |   |   |--- ratio_to_median_purchase_price <= 0.04
|   |   |   |   |--- Unnamed: 0 <= -1.10
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- Unnamed: 0 >  -1.10
|   |   |   |   |   |--- distance_from_home <= 0.39
|   |   |   |   |   |   |--- repeat_retailer <= -0.91
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- repeat_retailer >  -0.91
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_home >  0.39
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- ratio_to_median_purchase_price >  0.04
|   |   |   |   |--- class: 1
|   |   |--- used_pin_number >  1.95
|   |   |   |--- distance_from_home <= 0.69
|   |   |   |   |--- distance_from_last_transaction <= 1.47
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- distance_from_last_transaction >  1.47
|   |   |   |   |   |--- used_chip <= 0.65
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- used_chip >  0.65
|   |   |   |   |   |   |--- distance_from_home <= -0.45
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- distance_from_home >  -0.45
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- distance_from_home >  0.69
|   |   |   |   |--- used_chip <= 0.65
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- used_chip >  0.65
|   |   |   |   |   |--- distance_from_last_transaction <= 1.33
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- distance_from_last_transaction >  1.33
|   |   |   |   |   |   |--- class: 1

# 5. Оценка качества моделей (создание моделей с помощью PyCaret)

При подключении PyCaret возникли проблемы несовместимости в связи с чем для взаимодействия с библиотекой был использован сервис Google Colab

## Регрессия

In [5]:
import pycaret.regression as pyreg

reg_exp = pyreg.setup(
    data=data_regr,
    target='price',
    session_id=42,
    verbose=True
)

In [6]:
best_reg = pyreg.compare_models(sort='R2', n_select=1)

Processing:   0%|          | 0/85 [00:00<?, ?it/s]

## Классификация

In [7]:
import pycaret.classification as pyclf

clf_exp = pyclf.setup(
    data=data_clas,
    target='fraud',
    session_id=42,
    verbose=True
)

In [8]:
best_clf = pyclf.compare_models(sort='F1', n_select=1)

Processing:   0%|          | 0/69 [00:00<?, ?it/s]

# 6. Создание таблицы результатов

In [63]:
models_regr_cv = {'DecisionTreeRegressor': DecisionTreeRegressor(**{'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 8}, random_state=42),
                  'BaggingRegressor': BaggingRegressor(**{'n_estimators': 82, 'max_samples': 0.7650220936235242, 'max_features': 0.9943533773759213}, random_state=42, n_jobs=-1),
                  'GradientBoostingRegressor': GradientBoostingRegressor(**{'n_estimators': 333, 'learning_rate': 0.015750619803704784, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.7276427960501565}, random_state=42),
                  'StackingRegressor': StackingRegressor(estimators=[('Ridge', Ridge(alpha=25.241424867460356, random_state=42)), ('GradientBoosting', GradientBoostingRegressor(**{'n_estimators': 333, 'learning_rate': 0.015750619803704784, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'subsample': 0.7276427960501565}, random_state=42)), ('RandomTree', RandomForestRegressor(**{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_features': 1.0, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 50, 'verbose': 0, 'warm_start': False}))], final_estimator=ElasticNet(alpha=0.002183419021890954, l1_ratio=0.6572558012453984, random_state=42), n_jobs=-1),
                  'CatBoostRegressor': CatBoostRegressor(**{'iterations': 1120, 'learning_rate': 0.0387592525723667, 'depth': 6, 'l2_leaf_reg': 0.0006357456098930143, 'bagging_temperature': 0.03172310195167838, 'random_strength': 3.7360878294978876, 'grow_policy': 'SymmetricTree'}, task_type='CPU', thread_count=-1, random_state=42),
                  'XGBoostRegressor': XGBRegressor(**{'n_estimators': 773, 'max_depth': 7, 'learning_rate': 0.017064549414664634, 'subsample': 0.7747701428698828, 'colsample_bytree': 0.7899746430902906, 'gamma': 0.12319436780270282, 'reg_alpha': 0.009642742572935563, 'reg_lambda': 0.12610503197436898}, random_state=42, n_jobs=-1),
                  'LightGBMRegressor': LGBMRegressor(**{'n_estimators': 674, 'max_depth': 6, 'learning_rate': 0.014215547294580726, 'num_leaves': 244, 'min_child_samples': 8, 'subsample': 0.959970948373626, 'colsample_bytree': 0.7036459616308876, 'reg_alpha': 0.003675639993320709, 'reg_lambda': 0.2428815144688183}, force_col_wise=True)}

models_clas_cv = {'clas_DecisionTreeClassifier': DecisionTreeClassifier(min_samples_split=5, max_depth=7, criterion='entropy', class_weight='balanced', random_state=42),
                  'clas_BaggingClassifier': BaggingClassifier(**{'n_estimators': 43, 'max_samples': 0.7999412510648061, 'max_features': 0.9521873714773709}, random_state=42, n_jobs=-1),
                  'GradientBoostingClassifier': GradientBoostingClassifier(**{'n_estimators': 500, 'learning_rate': 0.047491241225455304, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 2, 'subsample': 0.7314298772479082, 'max_features': 'log2'}, random_state=42),
                  'StackingClassifier': StackingClassifier(estimators=[('SVC', SVC(gamma=0.1, random_state=42)), ('Tree', DecisionTreeClassifier(min_samples_split=5, max_depth=7, criterion='entropy', class_weight='balanced', random_state=42)), ('RandomTree', RandomForestClassifier(**{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'gini', 'max_features': 'sqrt', 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 51, 'verbose': 0, 'warm_start': False}))], final_estimator=LGBMClassifier(**{'n_estimators': 378, 'max_depth': 4, 'learning_rate': 0.045472411633406845, 'num_leaves': 167, 'min_child_samples': 15, 'subsample': 0.787300997249121, 'colsample_bytree': 0.8020043291010864, 'reg_alpha': 0.6629728220339912, 'reg_lambda': 0.12603478242435429}, force_col_wise=True), n_jobs=-1),
                  'CatBoostClassifier': CatBoostClassifier(**{'iterations': 1466, 'learning_rate': 0.004896927153059759, 'depth': 7, 'l2_leaf_reg': 0.0015223359176138216, 'border_count': 226, 'grow_policy': 'SymmetricTree'}, task_type='CPU', thread_count=-1, random_state=42),
                  'XGBoostClassifier': XGBClassifier(**{'n_estimators': 160, 'max_depth': 5, 'learning_rate': 0.03380924770634301, 'subsample': 0.8674150272975121, 'colsample_bytree': 0.9553110238818484, 'gamma': 0.2949825966699646, 'reg_alpha': 0.014787616897752608, 'reg_lambda': 1.4126794376806364}),
                  'LightGBMClassifier': LGBMClassifier(**{'n_estimators': 378, 'max_depth': 4, 'learning_rate': 0.045472411633406845, 'num_leaves': 167, 'min_child_samples': 15, 'subsample': 0.787300997249121, 'colsample_bytree': 0.8020043291010864, 'reg_alpha': 0.6629728220339912, 'reg_lambda': 0.12603478242435429}, force_col_wise=True)}

## 6.1 Регрессия

### Функции

In [64]:
def generate_regression_table1(models_regr, X_train, y_train, X_test, y_test):
    results = []

    for name, model in models_regr.items():
        print(f"Добавление строки для регрессионной модели: {name}")

        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)

        train_metrics = {
            'Algorithm': name,
            'Train R2': round(r2_score(y_train, y_train_pred), 2),
            'Train RMSE': round(np.sqrt(mean_squared_error(y_train, y_train_pred)), 4),
            'Train MAE': round(mean_absolute_error(y_train, y_train_pred), 4),
            'Test R2': round(r2_score(y_test, y_test_pred), 2),
            'Test RMSE': round(np.sqrt(mean_squared_error(y_test, y_test_pred)), 4),
            'Test MAE': round(mean_absolute_error(y_test, y_test_pred), 4)
        }

        results.append(train_metrics)

    return pd.DataFrame(results)

df_regr_table1 = generate_regression_table1(models_regr, X_regr_train_s, y_regr_train, X_regr_test_s, y_regr_test)

Добавление строки для регрессионной модели: DecisionTreeRegressor
Добавление строки для регрессионной модели: BaggingRegressor
Добавление строки для регрессионной модели: GradientBoostingRegressor
Добавление строки для регрессионной модели: StackingRegressor
Добавление строки для регрессионной модели: CatBoostRegressor
Добавление строки для регрессионной модели: XGBoostRegressor
Добавление строки для регрессионной модели: LightGBMRegressor

In [65]:
def generate_regression_table2(models_regr, X, y, X_test_h_o, y_test_h_o):
    results = []
    kf = KFold(n_splits=3, shuffle=True, random_state=42)

    for name, model in models_regr.items():
        print(f"Обработка модели: {name}")

        y_pred_holdout = model.predict(X_test_h_o)

        r2_scores, rmse_scores, mae_scores = [], [], []

        for train_idx, test_idx in kf.split(X):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

            cv_model = models_regr_cv[name]
            cv_model.fit(X_train, y_train)

            y_pred = cv_model.predict(X_test)
            r2_scores.append(r2_score(y_test, y_pred))
            rmse_scores.append(np.sqrt(mean_squared_error(y_test, y_pred)))
            mae_scores.append(mean_absolute_error(y_test, y_pred))

        metrics = {
            'Algorithm': name,
            'Hold-out R2': round(r2_score(y_test_h_o, y_pred_holdout), 2),
            'Hold-out RMSE': round(np.sqrt(mean_squared_error(y_test_h_o, y_pred_holdout)), 4),
            'Hold-out MAE': round(mean_absolute_error(y_test_h_o, y_pred_holdout), 4),
            'K-Fold R2 (mean)': round(np.mean(r2_scores), 2),
            'K-Fold RMSE (mean)': round(np.mean(rmse_scores), 4),
            'K-Fold MAE (mean)': round(np.mean(mae_scores), 4)
        }

        results.append(metrics)

    return pd.DataFrame(results)

df_regr_table2 = generate_regression_table2(models_regr, X_regr, y_regr, X_regr_test_s, y_regr_test)

Выходные данные были обрезаны до нескольких последних строк (5000).
393:	learn: 519.9077897	total: 2.56s	remaining: 4.72s
394:	learn: 519.7348190	total: 2.57s	remaining: 4.72s
395:	learn: 519.3594256	total: 2.58s	remaining: 4.71s
396:	learn: 519.2238726	total: 2.58s	remaining: 4.7s
397:	learn: 518.9175435	total: 2.59s	remaining: 4.7s
398:	learn: 518.5999856	total: 2.6s	remaining: 4.69s
399:	learn: 518.3193457	total: 2.6s	remaining: 4.68s
400:	learn: 518.1569464	total: 2.61s	remaining: 4.67s
401:	learn: 517.9978987	total: 2.61s	remaining: 4.67s
402:	learn: 517.7797889	total: 2.62s	remaining: 4.66s
403:	learn: 517.5641673	total: 2.63s	remaining: 4.65s
404:	learn: 517.4408459	total: 2.63s	remaining: 4.65s
405:	learn: 517.2799050	total: 2.64s	remaining: 4.64s
406:	learn: 517.0484400	total: 2.64s	remaining: 4.63s
407:	learn: 516.8271450	total: 2.65s	remaining: 4.62s
408:	learn: 516.5368659	total: 2.65s	remaining: 4.61s
409:	learn: 516.3247036	total: 2.66s	remaining: 4.61s
410:	learn: 516.0943482	total: 2.67s	remaining: 4.61s
411:	learn: 515.9238276	total: 2.69s	remaining: 4.62s
412:	learn: 515.7722860	total: 2.7s	remaining: 4.62s
413:	learn: 515.6428599	total: 2.71s	remaining: 4.62s
414:	learn: 515.3356353	total: 2.71s	remaining: 4.61s
415:	learn: 515.1971108	total: 2.72s	remaining: 4.6s
416:	learn: 515.0057131	total: 2.73s	remaining: 4.59s
417:	learn: 514.7743101	total: 2.73s	remaining: 4.59s
418:	learn: 514.5574215	total: 2.74s	remaining: 4.58s
419:	learn: 514.3392158	total: 2.74s	remaining: 4.57s
420:	learn: 514.2238796	total: 2.75s	remaining: 4.56s
421:	learn: 514.0689052	total: 2.75s	remaining: 4.56s
422:	learn: 513.8978689	total: 2.76s	remaining: 4.55s
423:	learn: 513.7760294	total: 2.77s	remaining: 4.54s
424:	learn: 513.6660227	total: 2.77s	remaining: 4.53s
425:	learn: 513.4785992	total: 2.78s	remaining: 4.53s
426:	learn: 513.3302080	total: 2.78s	remaining: 4.52s
427:	learn: 513.1241220	total: 2.79s	remaining: 4.51s
428:	learn: 512.9801546	total: 2.8s	remaining: 4.51s
429:	learn: 512.9045498	total: 2.81s	remaining: 4.5s
430:	learn: 512.7571566	total: 2.81s	remaining: 4.5s
431:	learn: 512.5526572	total: 2.82s	remaining: 4.49s
432:	learn: 512.2584914	total: 2.82s	remaining: 4.48s
433:	learn: 512.1608704	total: 2.83s	remaining: 4.47s
434:	learn: 511.8939735	total: 2.83s	remaining: 4.46s
435:	learn: 511.7943824	total: 2.84s	remaining: 4.46s
436:	learn: 511.6439542	total: 2.85s	remaining: 4.45s
437:	learn: 511.6066678	total: 2.85s	remaining: 4.44s
438:	learn: 511.3915998	total: 2.86s	remaining: 4.43s
439:	learn: 511.2480119	total: 2.86s	remaining: 4.42s
440:	learn: 511.0992179	total: 2.87s	remaining: 4.42s
441:	learn: 510.9665026	total: 2.88s	remaining: 4.41s
442:	learn: 510.7204608	total: 2.88s	remaining: 4.41s
443:	learn: 510.5116731	total: 2.89s	remaining: 4.4s
444:	learn: 510.3197032	total: 2.9s	remaining: 4.39s
445:	learn: 510.0966366	total: 2.9s	remaining: 4.39s
446:	learn: 509.9414874	total: 2.91s	remaining: 4.38s
447:	learn: 509.7871926	total: 2.92s	remaining: 4.38s
448:	learn: 509.5649575	total: 2.92s	remaining: 4.37s
449:	learn: 509.4078558	total: 2.93s	remaining: 4.36s
450:	learn: 509.1395171	total: 2.94s	remaining: 4.35s
451:	learn: 508.9797915	total: 2.94s	remaining: 4.34s
452:	learn: 508.7188921	total: 2.95s	remaining: 4.34s
453:	learn: 508.6229046	total: 2.95s	remaining: 4.33s
454:	learn: 508.4225023	total: 2.96s	remaining: 4.32s
455:	learn: 508.3004179	total: 2.96s	remaining: 4.32s
456:	learn: 508.1708627	total: 2.97s	remaining: 4.31s
457:	learn: 508.0579990	total: 2.98s	remaining: 4.3s
458:	learn: 507.9614053	total: 2.98s	remaining: 4.29s
459:	learn: 507.7035830	total: 2.99s	remaining: 4.29s
460:	learn: 507.5137542	total: 2.99s	remaining: 4.28s
461:	learn: 507.3983614	total: 3s	remaining: 4.27s
462:	learn: 507.2193514	total: 3s	remaining: 4.26s
463:	learn: 507.0647780	total: 3.01s	remaining: 4.26s
464:	learn: 506.9548456	total: 3.02s	remaining: 4.25s
465:	learn: 506.6979911	total: 3.02s	remaining: 4.24s
466:	learn: 506.6382208	total: 3.03s	remaining: 4.24s
467:	learn: 506.4913242	total: 3.04s	remaining: 4.23s
468:	learn: 506.2482474	total: 3.04s	remaining: 4.22s
469:	learn: 506.0322693	total: 3.05s	remaining: 4.22s
470:	learn: 505.8855013	total: 3.06s	remaining: 4.21s
471:	learn: 505.7127770	total: 3.06s	remaining: 4.2s
472:	learn: 505.5884946	total: 3.07s	remaining: 4.2s
473:	learn: 505.4067479	total: 3.07s	remaining: 4.19s
474:	learn: 505.3751486	total: 3.08s	remaining: 4.18s
475:	learn: 505.1426006	total: 3.08s	remaining: 4.17s
476:	learn: 505.0298040	total: 3.09s	remaining: 4.17s
477:	learn: 504.8924217	total: 3.1s	remaining: 4.16s
478:	learn: 504.6794167	total: 3.1s	remaining: 4.15s
479:	learn: 504.5625900	total: 3.11s	remaining: 4.15s
480:	learn: 504.3936871	total: 3.12s	remaining: 4.14s
481:	learn: 504.2575468	total: 3.12s	remaining: 4.13s
482:	learn: 504.1568130	total: 3.13s	remaining: 4.12s
483:	learn: 503.9611614	total: 3.13s	remaining: 4.12s
484:	learn: 503.8540128	total: 3.14s	remaining: 4.11s
485:	learn: 503.6350122	total: 3.14s	remaining: 4.1s
486:	learn: 503.4092654	total: 3.15s	remaining: 4.09s
487:	learn: 503.2225955	total: 3.15s	remaining: 4.09s
488:	learn: 503.0658108	total: 3.16s	remaining: 4.08s
489:	learn: 502.9251197	total: 3.17s	remaining: 4.07s
490:	learn: 502.8932937	total: 3.17s	remaining: 4.06s
491:	learn: 502.7005589	total: 3.18s	remaining: 4.06s
492:	learn: 502.5517853	total: 3.18s	remaining: 4.05s
493:	learn: 502.4629760	total: 3.19s	remaining: 4.04s
494:	learn: 502.2153660	total: 3.19s	remaining: 4.04s
495:	learn: 502.0584462	total: 3.2s	remaining: 4.03s
496:	learn: 501.9652544	total: 3.21s	remaining: 4.02s
497:	learn: 501.8492347	total: 3.21s	remaining: 4.01s
498:	learn: 501.6136277	total: 3.22s	remaining: 4.01s
499:	learn: 501.4834576	total: 3.23s	remaining: 4s
500:	learn: 501.4555478	total: 3.23s	remaining: 3.99s
501:	learn: 501.3553568	total: 3.24s	remaining: 3.98s
502:	learn: 501.2096003	total: 3.24s	remaining: 3.98s
503:	learn: 501.1012419	total: 3.25s	remaining: 3.97s
504:	learn: 501.0228321	total: 3.25s	remaining: 3.96s
505:	learn: 500.9425196	total: 3.26s	remaining: 3.96s
506:	learn: 500.7794386	total: 3.27s	remaining: 3.95s
507:	learn: 500.6609207	total: 3.27s	remaining: 3.94s
508:	learn: 500.4927353	total: 3.28s	remaining: 3.94s
509:	learn: 500.4066226	total: 3.28s	remaining: 3.93s
510:	learn: 500.2655631	total: 3.29s	remaining: 3.92s
511:	learn: 500.1513956	total: 3.3s	remaining: 3.92s
512:	learn: 500.0113619	total: 3.31s	remaining: 3.91s
513:	learn: 499.9128231	total: 3.31s	remaining: 3.9s
514:	learn: 499.7424620	total: 3.32s	remaining: 3.9s
515:	learn: 499.5553084	total: 3.32s	remaining: 3.89s
516:	learn: 499.4299086	total: 3.33s	remaining: 3.88s
517:	learn: 499.2213765	total: 3.33s	remaining: 3.88s
518:	learn: 499.1119163	total: 3.34s	remaining: 3.87s
519:	learn: 498.9167760	total: 3.35s	remaining: 3.86s
520:	learn: 498.8396549	total: 3.35s	remaining: 3.85s
521:	learn: 498.7659916	total: 3.36s	remaining: 3.85s
522:	learn: 498.6636422	total: 3.36s	remaining: 3.84s
523:	learn: 498.5617988	total: 3.37s	remaining: 3.83s
524:	learn: 498.4121021	total: 3.38s	remaining: 3.83s
525:	learn: 498.2821133	total: 3.38s	remaining: 3.82s
526:	learn: 498.1643474	total: 3.39s	remaining: 3.81s
527:	learn: 498.0681925	total: 3.39s	remaining: 3.81s
528:	learn: 497.9123696	total: 3.4s	remaining: 3.8s
529:	learn: 497.7073680	total: 3.41s	remaining: 3.79s
530:	learn: 497.5689164	total: 3.41s	remaining: 3.79s
531:	learn: 497.3008172	total: 3.42s	remaining: 3.78s
532:	learn: 497.1494530	total: 3.42s	remaining: 3.77s
533:	learn: 497.0207904	total: 3.43s	remaining: 3.77s
534:	learn: 496.9932105	total: 3.44s	remaining: 3.76s
535:	learn: 496.8578577	total: 3.44s	remaining: 3.75s
536:	learn: 496.7142308	total: 3.45s	remaining: 3.75s
537:	learn: 496.5148833	total: 3.46s	remaining: 3.74s
538:	learn: 496.2993363	total: 3.46s	remaining: 3.73s
539:	learn: 496.2326598	total: 3.47s	remaining: 3.73s
540:	learn: 496.1476637	total: 3.47s	remaining: 3.72s
541:	learn: 495.9994219	total: 3.48s	remaining: 3.71s
542:	learn: 495.9117536	total: 3.49s	remaining: 3.71s
543:	learn: 495.7510931	total: 3.49s	remaining: 3.7s
544:	learn: 495.6331926	total: 3.5s	remaining: 3.69s
545:	learn: 495.4907148	total: 3.51s	remaining: 3.69s
546:	learn: 495.2751684	total: 3.51s	remaining: 3.68s
547:	learn: 495.1882682	total: 3.52s	remaining: 3.68s
548:	learn: 495.1433893	total: 3.53s	remaining: 3.67s
549:	learn: 494.9578726	total: 3.54s	remaining: 3.67s
550:	learn: 494.8248072	total: 3.55s	remaining: 3.66s
551:	learn: 494.6695084	total: 3.55s	remaining: 3.65s
552:	learn: 494.5107032	total: 3.56s	remaining: 3.65s
553:	learn: 494.3748893	total: 3.56s	remaining: 3.64s
554:	learn: 494.2510118	total: 3.57s	remaining: 3.63s
555:	learn: 494.1003923	total: 3.58s	remaining: 3.63s
556:	learn: 493.8937417	total: 3.58s	remaining: 3.62s
557:	learn: 493.7929569	total: 3.59s	remaining: 3.61s
558:	learn: 493.6618341	total: 3.59s	remaining: 3.6s
559:	learn: 493.6148153	total: 3.6s	remaining: 3.6s
560:	learn: 493.5121316	total: 3.6s	remaining: 3.59s
561:	learn: 493.4184327	total: 3.61s	remaining: 3.58s
562:	learn: 493.2996842	total: 3.62s	remaining: 3.58s
563:	learn: 493.1591705	total: 3.62s	remaining: 3.57s
564:	learn: 493.0454310	total: 3.63s	remaining: 3.56s
565:	learn: 492.9202882	total: 3.64s	remaining: 3.56s
566:	learn: 492.8910997	total: 3.64s	remaining: 3.55s
567:	learn: 492.7433281	total: 3.65s	remaining: 3.55s
568:	learn: 492.6220527	total: 3.65s	remaining: 3.54s
569:	learn: 492.4732630	total: 3.66s	remaining: 3.53s
570:	learn: 492.3441399	total: 3.68s	remaining: 3.54s
571:	learn: 492.1665911	total: 3.69s	remaining: 3.54s
572:	learn: 492.0625732	total: 3.7s	remaining: 3.53s
573:	learn: 491.9261135	total: 3.71s	remaining: 3.53s
574:	learn: 491.8178340	total: 3.71s	remaining: 3.52s
575:	learn: 491.6370592	total: 3.72s	remaining: 3.51s
576:	learn: 491.5296299	total: 3.73s	remaining: 3.51s
577:	learn: 491.5096480	total: 3.73s	remaining: 3.5s
578:	learn: 491.3986269	total: 3.74s	remaining: 3.49s
579:	learn: 491.3010172	total: 3.74s	remaining: 3.48s
580:	learn: 491.2512695	total: 3.75s	remaining: 3.48s
581:	learn: 491.1478523	total: 3.75s	remaining: 3.47s
582:	learn: 490.9884965	total: 3.76s	remaining: 3.46s
583:	learn: 490.8818200	total: 3.77s	remaining: 3.46s
584:	learn: 490.7616117	total: 3.77s	remaining: 3.45s
585:	learn: 490.6624025	total: 3.78s	remaining: 3.44s
586:	learn: 490.5613610	total: 3.79s	remaining: 3.44s
587:	learn: 490.4718100	total: 3.79s	remaining: 3.43s
588:	learn: 490.3812316	total: 3.8s	remaining: 3.42s
589:	learn: 490.2784964	total: 3.8s	remaining: 3.42s
590:	learn: 490.1368599	total: 3.81s	remaining: 3.41s
591:	learn: 490.0278284	total: 3.82s	remaining: 3.4s
592:	learn: 489.9440019	total: 3.82s	remaining: 3.4s
593:	learn: 489.8363992	total: 3.83s	remaining: 3.39s
594:	learn: 489.6411654	total: 3.83s	remaining: 3.38s
595:	learn: 489.5230416	total: 3.84s	remaining: 3.38s
596:	learn: 489.4334115	total: 3.85s	remaining: 3.37s
597:	learn: 489.2938791	total: 3.85s	remaining: 3.36s
598:	learn: 489.1400667	total: 3.86s	remaining: 3.36s
599:	learn: 489.0192043	total: 3.87s	remaining: 3.35s
600:	learn: 488.9143467	total: 3.87s	remaining: 3.34s
601:	learn: 488.8153679	total: 3.88s	remaining: 3.34s
602:	learn: 488.7582597	total: 3.88s	remaining: 3.33s
603:	learn: 488.6805031	total: 3.89s	remaining: 3.32s
604:	learn: 488.6193005	total: 3.9s	remaining: 3.32s
605:	learn: 488.4828462	total: 3.9s	remaining: 3.31s
606:	learn: 488.2939544	total: 3.91s	remaining: 3.3s
607:	learn: 488.1359679	total: 3.92s	remaining: 3.3s
608:	learn: 488.0210032	total: 3.92s	remaining: 3.29s
609:	learn: 487.8419532	total: 3.93s	remaining: 3.28s
610:	learn: 487.7330902	total: 3.93s	remaining: 3.28s
611:	learn: 487.6731743	total: 3.94s	remaining: 3.27s
612:	learn: 487.6058365	total: 3.94s	remaining: 3.26s
613:	learn: 487.5362796	total: 3.95s	remaining: 3.25s
614:	learn: 487.4455264	total: 3.96s	remaining: 3.25s
615:	learn: 487.3087446	total: 3.96s	remaining: 3.24s
616:	learn: 487.2181670	total: 3.97s	remaining: 3.23s
617:	learn: 487.0997121	total: 3.98s	remaining: 3.23s
618:	learn: 487.0043315	total: 3.98s	remaining: 3.22s
619:	learn: 486.9086390	total: 3.99s	remaining: 3.21s
620:	learn: 486.7680506	total: 3.99s	remaining: 3.21s
621:	learn: 486.6872123	total: 4s	remaining: 3.2s
622:	learn: 486.6452773	total: 4.01s	remaining: 3.2s
623:	learn: 486.5287144	total: 4.01s	remaining: 3.19s
624:	learn: 486.4378572	total: 4.02s	remaining: 3.18s
625:	learn: 486.4154549	total: 4.03s	remaining: 3.18s
626:	learn: 486.2830860	total: 4.03s	remaining: 3.17s
627:	learn: 486.2346700	total: 4.04s	remaining: 3.16s
628:	learn: 486.1806281	total: 4.04s	remaining: 3.16s
629:	learn: 486.0640390	total: 4.05s	remaining: 3.15s
630:	learn: 486.0124314	total: 4.06s	remaining: 3.14s
631:	learn: 485.9520000	total: 4.06s	remaining: 3.14s
632:	learn: 485.9067385	total: 4.07s	remaining: 3.13s
633:	learn: 485.8521320	total: 4.08s	remaining: 3.12s
634:	learn: 485.7219234	total: 4.08s	remaining: 3.12s
635:	learn: 485.5672506	total: 4.09s	remaining: 3.11s
636:	learn: 485.4537728	total: 4.1s	remaining: 3.11s
637:	learn: 485.4006788	total: 4.11s	remaining: 3.1s
638:	learn: 485.3024581	total: 4.11s	remaining: 3.1s
639:	learn: 485.2158178	total: 4.12s	remaining: 3.09s
640:	learn: 485.1058848	total: 4.12s	remaining: 3.08s
641:	learn: 484.9297525	total: 4.13s	remaining: 3.08s
642:	learn: 484.8178469	total: 4.14s	remaining: 3.07s
643:	learn: 484.6423811	total: 4.14s	remaining: 3.06s
644:	learn: 484.5949943	total: 4.15s	remaining: 3.06s
645:	learn: 484.5131180	total: 4.16s	remaining: 3.05s
646:	learn: 484.3699112	total: 4.16s	remaining: 3.04s
647:	learn: 484.2269015	total: 4.17s	remaining: 3.04s
648:	learn: 484.0356823	total: 4.17s	remaining: 3.03s
649:	learn: 483.9536236	total: 4.18s	remaining: 3.02s
650:	learn: 483.8036286	total: 4.18s	remaining: 3.02s
651:	learn: 483.7015592	total: 4.19s	remaining: 3.01s
652:	learn: 483.5685720	total: 4.2s	remaining: 3s
653:	learn: 483.4143594	total: 4.21s	remaining: 3s
654:	learn: 483.3089149	total: 4.21s	remaining: 2.99s
655:	learn: 483.2406373	total: 4.22s	remaining: 2.98s
656:	learn: 483.0425145	total: 4.22s	remaining: 2.98s
657:	learn: 482.8802170	total: 4.23s	remaining: 2.97s
658:	learn: 482.7680348	total: 4.24s	remaining: 2.96s
659:	learn: 482.7045009	total: 4.25s	remaining: 2.96s
660:	learn: 482.6623062	total: 4.25s	remaining: 2.95s
661:	learn: 482.6053693	total: 4.26s	remaining: 2.95s
662:	learn: 482.3990097	total: 4.27s	remaining: 2.94s
663:	learn: 482.3479205	total: 4.28s	remaining: 2.94s
664:	learn: 482.1575663	total: 4.28s	remaining: 2.93s
665:	learn: 482.0885542	total: 4.29s	remaining: 2.92s
666:	learn: 481.9929463	total: 4.3s	remaining: 2.92s
667:	learn: 481.7713623	total: 4.31s	remaining: 2.91s
668:	learn: 481.6883287	total: 4.31s	remaining: 2.91s
669:	learn: 481.5803704	total: 4.32s	remaining: 2.9s
670:	learn: 481.4301799	total: 4.33s	remaining: 2.9s
671:	learn: 481.3477016	total: 4.33s	remaining: 2.89s
672:	learn: 481.2229661	total: 4.34s	remaining: 2.88s
673:	learn: 481.1057667	total: 4.35s	remaining: 2.88s
674:	learn: 481.0027789	total: 4.35s	remaining: 2.87s
675:	learn: 480.9481707	total: 4.36s	remaining: 2.87s
676:	learn: 480.7970916	total: 4.37s	remaining: 2.86s
677:	learn: 480.7458647	total: 4.38s	remaining: 2.85s
678:	learn: 480.6432930	total: 4.38s	remaining: 2.85s
679:	learn: 480.5383769	total: 4.39s	remaining: 2.84s
680:	learn: 480.3764604	total: 4.4s	remaining: 2.83s
681:	learn: 480.3123368	total: 4.41s	remaining: 2.83s
682:	learn: 480.2018194	total: 4.42s	remaining: 2.83s
683:	learn: 480.1328436	total: 4.42s	remaining: 2.82s
684:	learn: 480.0962139	total: 4.44s	remaining: 2.82s
685:	learn: 480.0000371	total: 4.46s	remaining: 2.82s
686:	learn: 479.9006899	total: 4.48s	remaining: 2.82s
687:	learn: 479.7867790	total: 4.49s	remaining: 2.82s
688:	learn: 479.6849915	total: 4.53s	remaining: 2.83s
689:	learn: 479.6302338	total: 4.55s	remaining: 2.83s
690:	learn: 479.5055365	total: 4.56s	remaining: 2.83s
691:	learn: 479.3472616	total: 4.57s	remaining: 2.83s
692:	learn: 479.3034933	total: 4.58s	remaining: 2.82s
693:	learn: 479.1396428	total: 4.59s	remaining: 2.82s
694:	learn: 479.0308136	total: 4.61s	remaining: 2.82s
695:	learn: 478.9598677	total: 4.63s	remaining: 2.82s
696:	learn: 478.7233836	total: 4.64s	remaining: 2.82s
697:	learn: 478.6641054	total: 4.67s	remaining: 2.82s
698:	learn: 478.5991841	total: 4.68s	remaining: 2.82s
699:	learn: 478.4260011	total: 4.7s	remaining: 2.82s
700:	learn: 478.4100287	total: 4.72s	remaining: 2.82s
701:	learn: 478.2345351	total: 4.73s	remaining: 2.82s
702:	learn: 478.1243483	total: 4.74s	remaining: 2.81s
703:	learn: 478.0714629	total: 4.75s	remaining: 2.81s
704:	learn: 477.9696387	total: 4.78s	remaining: 2.81s
705:	learn: 477.8571305	total: 4.79s	remaining: 2.81s
706:	learn: 477.7137207	total: 4.81s	remaining: 2.81s
707:	learn: 477.6067268	total: 4.82s	remaining: 2.8s
708:	learn: 477.4344641	total: 4.83s	remaining: 2.8s
709:	learn: 477.3607953	total: 4.84s	remaining: 2.79s
710:	learn: 477.2406235	total: 4.84s	remaining: 2.79s
711:	learn: 477.0678942	total: 4.85s	remaining: 2.78s
712:	learn: 476.9082369	total: 4.86s	remaining: 2.77s
713:	learn: 476.8321871	total: 4.87s	remaining: 2.77s
714:	learn: 476.7302801	total: 4.88s	remaining: 2.76s
715:	learn: 476.6520913	total: 4.9s	remaining: 2.76s
716:	learn: 476.4865663	total: 4.92s	remaining: 2.77s
717:	learn: 476.4398024	total: 4.94s	remaining: 2.77s
718:	learn: 476.3821382	total: 4.96s	remaining: 2.77s
719:	learn: 476.2722700	total: 4.98s	remaining: 2.77s
720:	learn: 476.2089340	total: 5s	remaining: 2.77s
721:	learn: 476.1188745	total: 5.02s	remaining: 2.77s
722:	learn: 476.0826366	total: 5.04s	remaining: 2.76s
723:	learn: 475.9145531	total: 5.05s	remaining: 2.76s
724:	learn: 475.8223683	total: 5.06s	remaining: 2.76s
725:	learn: 475.7369516	total: 5.07s	remaining: 2.75s
726:	learn: 475.6774723	total: 5.08s	remaining: 2.75s
727:	learn: 475.6251602	total: 5.1s	remaining: 2.75s
728:	learn: 475.4911665	total: 5.12s	remaining: 2.75s
729:	learn: 475.3417315	total: 5.14s	remaining: 2.75s
730:	learn: 475.3008971	total: 5.16s	remaining: 2.75s
731:	learn: 475.1502005	total: 5.18s	remaining: 2.75s
732:	learn: 474.9754687	total: 5.2s	remaining: 2.74s
733:	learn: 474.8453824	total: 5.21s	remaining: 2.74s
734:	learn: 474.7598620	total: 5.23s	remaining: 2.74s
735:	learn: 474.6918817	total: 5.25s	remaining: 2.74s
736:	learn: 474.6199357	total: 5.28s	remaining: 2.74s
737:	learn: 474.5178096	total: 5.29s	remaining: 2.74s
738:	learn: 474.4246741	total: 5.31s	remaining: 2.74s
739:	learn: 474.3126588	total: 5.33s	remaining: 2.74s
740:	learn: 474.2700889	total: 5.35s	remaining: 2.74s
741:	learn: 474.1626672	total: 5.37s	remaining: 2.73s
742:	learn: 474.1179663	total: 5.38s	remaining: 2.73s
743:	learn: 474.0653623	total: 5.4s	remaining: 2.73s
744:	learn: 473.9860841	total: 5.42s	remaining: 2.73s
745:	learn: 473.8516346	total: 5.43s	remaining: 2.73s
746:	learn: 473.7733464	total: 5.45s	remaining: 2.72s
747:	learn: 473.6994236	total: 5.47s	remaining: 2.72s
748:	learn: 473.6192737	total: 5.49s	remaining: 2.72s
749:	learn: 473.5720183	total: 5.51s	remaining: 2.72s
750:	learn: 473.4439925	total: 5.52s	remaining: 2.71s
751:	learn: 473.3350697	total: 5.54s	remaining: 2.71s
752:	learn: 473.2431016	total: 5.57s	remaining: 2.71s
753:	learn: 473.1950155	total: 5.58s	remaining: 2.71s
754:	learn: 473.1200084	total: 5.6s	remaining: 2.71s
755:	learn: 473.0539940	total: 5.61s	remaining: 2.7s
756:	learn: 473.0132785	total: 5.63s	remaining: 2.7s
757:	learn: 472.9134861	total: 5.64s	remaining: 2.69s
758:	learn: 472.8686717	total: 5.66s	remaining: 2.69s
759:	learn: 472.7637004	total: 5.68s	remaining: 2.69s
760:	learn: 472.7085090	total: 5.69s	remaining: 2.69s
761:	learn: 472.6091719	total: 5.7s	remaining: 2.68s
762:	learn: 472.4858012	total: 5.71s	remaining: 2.67s

### Таблицы

In [66]:
df_regr_table1

,Algorithm,Train R2,Train RMSE,Train MAE,Test R2,Test RMSE,Test MAE
0,DecisionTreeRegressor,0.98,497.6098,260.7205,0.98,583.6247,307.3832
1,BaggingRegressor,1.00,263.5555,131.1693,0.98,518.2833,264.6809
2,GradientBoostingRegressor,0.99,421.2451,228.0877,0.98,492.5275,256.5495
3,StackingRegressor,0.99,393.4665,209.8533,0.98,490.3069,251.8534
4,CatBoostRegressor,0.99,453.1789,249.0446,0.98,488.9072,260.8769
5,XGBoostRegressor,0.99,383.3123,218.1048,0.98,496.9633,256.7458
6,LightGBMRegressor,0.99,465.4514,251.6873,0.98,496.1805,262.7697

In [67]:
df_regr_table2

,Algorithm,Hold-out R2,Hold-out RMSE,Hold-out MAE,K-Fold R2 (mean),K-Fold RMSE (mean),K-Fold MAE (mean)
0,DecisionTreeRegressor,0.98,583.6247,307.3832,0.98,620.7680,318.5793
1,BaggingRegressor,0.98,518.2833,264.6809,0.98,556.0614,278.6160
2,GradientBoostingRegressor,0.98,492.5275,256.5495,0.98,525.4151,267.6510
3,StackingRegressor,0.98,490.3069,251.8534,0.92,1100.5427,720.0705
4,CatBoostRegressor,0.98,488.9072,260.8769,0.98,528.1662,273.0047
5,XGBoostRegressor,0.98,496.9633,256.7458,0.98,533.8251,268.3176
6,LightGBMRegressor,0.98,496.1805,262.7697,0.98,531.3557,273.7520

## 6.2 Классификация

### Функции

In [68]:
def generate_classification_table1(models_clas, X_train, y_train, X_test, y_test):
    results = []

    for name, model in models_clas.items():
        print(f"Добавление строки для классификационной модели: {name}")

        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)

        train_metrics = {
            'Algorithm': name,
            'Train Accuracy': round(accuracy_score(y_train, y_train_pred), 2),
            'Train Precision': round(precision_score(y_train, y_train_pred, average='weighted'), 2),
            'Train Recall': round(recall_score(y_train, y_train_pred, average='weighted'), 2),
            'Train F1': round(f1_score(y_train, y_train_pred, average='weighted'), 2),
            'Test Accuracy': round(accuracy_score(y_test, y_test_pred), 2),
            'Test Precision': round(precision_score(y_test, y_test_pred, average='weighted'), 2),
            'Test Recall': round(recall_score(y_test, y_test_pred, average='weighted'), 2),
            'Test F1': round(f1_score(y_test, y_test_pred, average='weighted'), 2)
        }

        results.append(train_metrics)

    return pd.DataFrame(results)

df_clas_table1 = generate_classification_table1(models_clas, X_clas_train_bus_svc, y_clas_train_bu_svc, X_clas_test_s, y_clas_test)

Добавление строки для классификационной модели: clas_DecisionTreeClassifier
Добавление строки для классификационной модели: clas_BaggingClassifier
Добавление строки для классификационной модели: GradientBoostingClassifier
Добавление строки для классификационной модели: StackingClassifier
Добавление строки для классификационной модели: CatBoostClassifier
Добавление строки для классификационной модели: XGBoostClassifier
Добавление строки для классификационной модели: LightGBMClassifier

In [70]:
def generate_classification_table2(models_clas, X, y, X_test_h_o, y_test_h_o):
    results = []
    kf = KFold(n_splits=3, shuffle=True, random_state=42)

    for name, model in models_clas.items():
        print(f"Обработка классификатора: {name}")

        y_pred_holdout = model.predict(X_test_h_o)

        accuracy_scores, precision_scores = [], []
        recall_scores, f1_scores = [], []

        y_values = y.values if hasattr(y, 'values') else y

        for train_idx, test_idx in kf.split(X):
            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y_values[train_idx], y_values[test_idx]

            cv_model = models_clas_cv[name]
            cv_model.fit(X_train, y_train)

            y_pred = cv_model.predict(X_test)

            accuracy_scores.append(accuracy_score(y_test, y_pred))
            precision_scores.append(precision_score(y_test, y_pred, average='weighted'))
            recall_scores.append(recall_score(y_test, y_pred, average='weighted'))
            f1_scores.append(f1_score(y_test, y_pred, average='weighted'))

        metrics = {
            'Algorithm': name,
            'Hold-out Accuracy': round(accuracy_score(y_test_h_o, y_pred_holdout), 2),
            'Hold-out Precision': round(precision_score(y_test_h_o, y_pred_holdout, average='weighted'), 2),
            'Hold-out Recall': round(recall_score(y_test_h_o, y_pred_holdout, average='weighted'), 2),
            'Hold-out F1': round(f1_score(y_test_h_o, y_pred_holdout, average='weighted'), 2),
            'K-Fold Accuracy (mean)': round(np.mean(accuracy_scores), 2),
            'K-Fold Precision (mean)': round(np.mean(precision_scores), 2),
            'K-Fold Recall (mean)': round(np.mean(recall_scores), 2),
            'K-Fold F1 (mean)': round(np.mean(f1_scores), 2)
        }

        print(metrics)

        results.append(metrics)

    return pd.DataFrame(results)

df_clas_table2 = generate_classification_table2(models_clas, X_clas_train_bus_svc, y_clas_train_bu_svc, X_clas_test_s, y_clas_test)

Выходные данные были обрезаны до нескольких последних строк (5000).
552:	learn: 0.0043241	total: 9.31s	remaining: 15.4s
553:	learn: 0.0043148	total: 9.36s	remaining: 15.4s
554:	learn: 0.0043125	total: 9.39s	remaining: 15.4s
555:	learn: 0.0043058	total: 9.43s	remaining: 15.4s
556:	learn: 0.0042998	total: 9.48s	remaining: 15.5s
557:	learn: 0.0042957	total: 9.53s	remaining: 15.5s
558:	learn: 0.0042932	total: 9.57s	remaining: 15.5s
559:	learn: 0.0042883	total: 9.61s	remaining: 15.5s
560:	learn: 0.0042854	total: 9.65s	remaining: 15.6s
561:	learn: 0.0042803	total: 9.7s	remaining: 15.6s
562:	learn: 0.0042774	total: 9.75s	remaining: 15.6s
563:	learn: 0.0042715	total: 9.78s	remaining: 15.6s
564:	learn: 0.0042655	total: 9.83s	remaining: 15.7s
565:	learn: 0.0042637	total: 9.87s	remaining: 15.7s
566:	learn: 0.0042570	total: 9.91s	remaining: 15.7s
567:	learn: 0.0042526	total: 9.94s	remaining: 15.7s
568:	learn: 0.0042499	total: 9.99s	remaining: 15.7s
569:	learn: 0.0042469	total: 10s	remaining: 15.8s
570:	learn: 0.0042425	total: 10.1s	remaining: 15.8s
571:	learn: 0.0042380	total: 10.1s	remaining: 15.8s
572:	learn: 0.0042344	total: 10.2s	remaining: 15.8s
573:	learn: 0.0042317	total: 10.2s	remaining: 15.9s
574:	learn: 0.0042248	total: 10.3s	remaining: 15.9s
575:	learn: 0.0042202	total: 10.3s	remaining: 15.9s
576:	learn: 0.0042158	total: 10.3s	remaining: 15.9s
577:	learn: 0.0042109	total: 10.4s	remaining: 16s
578:	learn: 0.0042053	total: 10.4s	remaining: 16s
579:	learn: 0.0042016	total: 10.5s	remaining: 16s
580:	learn: 0.0041976	total: 10.5s	remaining: 16s
581:	learn: 0.0041934	total: 10.6s	remaining: 16s
582:	learn: 0.0041908	total: 10.6s	remaining: 16.1s
583:	learn: 0.0041897	total: 10.6s	remaining: 16.1s
584:	learn: 0.0041798	total: 10.7s	remaining: 16.1s
585:	learn: 0.0041768	total: 10.7s	remaining: 16.1s
586:	learn: 0.0041743	total: 10.7s	remaining: 16s
587:	learn: 0.0041705	total: 10.7s	remaining: 16s
588:	learn: 0.0041679	total: 10.8s	remaining: 16.1s
589:	learn: 0.0041583	total: 10.8s	remaining: 16.1s
590:	learn: 0.0041524	total: 10.9s	remaining: 16.1s
591:	learn: 0.0041457	total: 10.9s	remaining: 16.1s
592:	learn: 0.0041416	total: 10.9s	remaining: 16s
593:	learn: 0.0041392	total: 10.9s	remaining: 16s
594:	learn: 0.0041340	total: 11s	remaining: 16.1s
595:	learn: 0.0041304	total: 11s	remaining: 16.1s
596:	learn: 0.0041291	total: 11s	remaining: 16.1s
597:	learn: 0.0041264	total: 11.1s	remaining: 16.1s
598:	learn: 0.0041221	total: 11.1s	remaining: 16.1s
599:	learn: 0.0041184	total: 11.2s	remaining: 16.1s
600:	learn: 0.0041160	total: 11.2s	remaining: 16.1s
601:	learn: 0.0041137	total: 11.3s	remaining: 16.2s
602:	learn: 0.0041104	total: 11.3s	remaining: 16.2s
603:	learn: 0.0041049	total: 11.3s	remaining: 16.2s
604:	learn: 0.0041018	total: 11.4s	remaining: 16.2s
605:	learn: 0.0040878	total: 11.4s	remaining: 16.2s
606:	learn: 0.0040849	total: 11.4s	remaining: 16.2s
607:	learn: 0.0040826	total: 11.5s	remaining: 16.2s
608:	learn: 0.0040795	total: 11.5s	remaining: 16.2s
609:	learn: 0.0040785	total: 11.6s	remaining: 16.2s
610:	learn: 0.0040752	total: 11.6s	remaining: 16.2s
611:	learn: 0.0040709	total: 11.6s	remaining: 16.2s
612:	learn: 0.0040683	total: 11.6s	remaining: 16.2s
613:	learn: 0.0040651	total: 11.7s	remaining: 16.2s
614:	learn: 0.0040613	total: 11.7s	remaining: 16.1s
615:	learn: 0.0040596	total: 11.7s	remaining: 16.1s
616:	learn: 0.0040576	total: 11.7s	remaining: 16.1s
617:	learn: 0.0040545	total: 11.7s	remaining: 16.1s
618:	learn: 0.0040511	total: 11.7s	remaining: 16.1s
619:	learn: 0.0040473	total: 11.8s	remaining: 16s
620:	learn: 0.0040446	total: 11.8s	remaining: 16s
621:	learn: 0.0040425	total: 11.8s	remaining: 16s
622:	learn: 0.0040403	total: 11.8s	remaining: 16s
623:	learn: 0.0040357	total: 11.8s	remaining: 15.9s
624:	learn: 0.0040312	total: 11.8s	remaining: 15.9s
625:	learn: 0.0040285	total: 11.8s	remaining: 15.9s
626:	learn: 0.0040253	total: 11.9s	remaining: 15.9s
627:	learn: 0.0040231	total: 11.9s	remaining: 15.9s
628:	learn: 0.0040197	total: 11.9s	remaining: 15.8s
629:	learn: 0.0040176	total: 11.9s	remaining: 15.8s
630:	learn: 0.0040154	total: 11.9s	remaining: 15.8s
631:	learn: 0.0040097	total: 11.9s	remaining: 15.8s
632:	learn: 0.0039972	total: 12s	remaining: 15.7s
633:	learn: 0.0039937	total: 12s	remaining: 15.7s
634:	learn: 0.0039919	total: 12s	remaining: 15.7s
635:	learn: 0.0039886	total: 12s	remaining: 15.7s
636:	learn: 0.0039868	total: 12s	remaining: 15.6s
637:	learn: 0.0039832	total: 12s	remaining: 15.6s
638:	learn: 0.0039800	total: 12.1s	remaining: 15.6s
639:	learn: 0.0039771	total: 12.1s	remaining: 15.6s
640:	learn: 0.0039729	total: 12.1s	remaining: 15.6s
641:	learn: 0.0039697	total: 12.1s	remaining: 15.5s
642:	learn: 0.0039651	total: 12.1s	remaining: 15.5s
643:	learn: 0.0039626	total: 12.1s	remaining: 15.5s
644:	learn: 0.0039606	total: 12.2s	remaining: 15.5s
645:	learn: 0.0039567	total: 12.2s	remaining: 15.5s
646:	learn: 0.0039548	total: 12.2s	remaining: 15.4s
647:	learn: 0.0039513	total: 12.2s	remaining: 15.4s
648:	learn: 0.0039472	total: 12.2s	remaining: 15.4s
649:	learn: 0.0039429	total: 12.2s	remaining: 15.4s
650:	learn: 0.0039383	total: 12.3s	remaining: 15.4s
651:	learn: 0.0039368	total: 12.3s	remaining: 15.3s
652:	learn: 0.0039328	total: 12.3s	remaining: 15.3s
653:	learn: 0.0039306	total: 12.3s	remaining: 15.3s
654:	learn: 0.0039287	total: 12.3s	remaining: 15.3s
655:	learn: 0.0039248	total: 12.3s	remaining: 15.2s
656:	learn: 0.0039221	total: 12.4s	remaining: 15.2s
657:	learn: 0.0039180	total: 12.4s	remaining: 15.2s
658:	learn: 0.0039145	total: 12.4s	remaining: 15.2s
659:	learn: 0.0039118	total: 12.4s	remaining: 15.2s
660:	learn: 0.0039090	total: 12.4s	remaining: 15.1s
661:	learn: 0.0039061	total: 12.4s	remaining: 15.1s
662:	learn: 0.0039033	total: 12.5s	remaining: 15.1s
663:	learn: 0.0038997	total: 12.5s	remaining: 15.1s
664:	learn: 0.0038950	total: 12.5s	remaining: 15.1s
665:	learn: 0.0038902	total: 12.5s	remaining: 15s
666:	learn: 0.0038882	total: 12.5s	remaining: 15s
667:	learn: 0.0038853	total: 12.5s	remaining: 15s
668:	learn: 0.0038833	total: 12.6s	remaining: 15s
669:	learn: 0.0038800	total: 12.6s	remaining: 14.9s
670:	learn: 0.0038748	total: 12.6s	remaining: 14.9s
671:	learn: 0.0038650	total: 12.6s	remaining: 14.9s
672:	learn: 0.0038618	total: 12.6s	remaining: 14.9s
673:	learn: 0.0038594	total: 12.6s	remaining: 14.8s
674:	learn: 0.0038548	total: 12.7s	remaining: 14.8s
675:	learn: 0.0038520	total: 12.7s	remaining: 14.8s
676:	learn: 0.0038508	total: 12.7s	remaining: 14.8s
677:	learn: 0.0038453	total: 12.7s	remaining: 14.8s
678:	learn: 0.0038403	total: 12.7s	remaining: 14.7s
679:	learn: 0.0038365	total: 12.7s	remaining: 14.7s
680:	learn: 0.0038328	total: 12.7s	remaining: 14.7s
681:	learn: 0.0038307	total: 12.8s	remaining: 14.7s
682:	learn: 0.0038262	total: 12.8s	remaining: 14.7s
683:	learn: 0.0038220	total: 12.8s	remaining: 14.6s
684:	learn: 0.0038178	total: 12.8s	remaining: 14.6s
685:	learn: 0.0038158	total: 12.8s	remaining: 14.6s
686:	learn: 0.0038145	total: 12.8s	remaining: 14.6s
687:	learn: 0.0038120	total: 12.9s	remaining: 14.5s
688:	learn: 0.0038082	total: 12.9s	remaining: 14.5s
689:	learn: 0.0038050	total: 12.9s	remaining: 14.5s
690:	learn: 0.0038006	total: 12.9s	remaining: 14.5s
691:	learn: 0.0037981	total: 12.9s	remaining: 14.5s
692:	learn: 0.0037927	total: 12.9s	remaining: 14.4s
693:	learn: 0.0037859	total: 12.9s	remaining: 14.4s
694:	learn: 0.0037827	total: 13s	remaining: 14.4s
695:	learn: 0.0037784	total: 13s	remaining: 14.4s
696:	learn: 0.0037748	total: 13s	remaining: 14.3s
697:	learn: 0.0037723	total: 13s	remaining: 14.3s
698:	learn: 0.0037654	total: 13s	remaining: 14.3s
699:	learn: 0.0037636	total: 13s	remaining: 14.3s
700:	learn: 0.0037610	total: 13.1s	remaining: 14.2s
701:	learn: 0.0037523	total: 13.1s	remaining: 14.2s
702:	learn: 0.0037512	total: 13.1s	remaining: 14.2s
703:	learn: 0.0037494	total: 13.1s	remaining: 14.2s
704:	learn: 0.0037463	total: 13.1s	remaining: 14.2s
705:	learn: 0.0037437	total: 13.1s	remaining: 14.1s
706:	learn: 0.0037415	total: 13.2s	remaining: 14.1s
707:	learn: 0.0037382	total: 13.2s	remaining: 14.1s
708:	learn: 0.0037350	total: 13.2s	remaining: 14.1s
709:	learn: 0.0037313	total: 13.2s	remaining: 14.1s
710:	learn: 0.0037299	total: 13.2s	remaining: 14.1s
711:	learn: 0.0037283	total: 13.3s	remaining: 14s
712:	learn: 0.0037265	total: 13.3s	remaining: 14s
713:	learn: 0.0037246	total: 13.3s	remaining: 14s
714:	learn: 0.0037221	total: 13.3s	remaining: 14s
715:	learn: 0.0037190	total: 13.3s	remaining: 13.9s
716:	learn: 0.0037138	total: 13.3s	remaining: 13.9s
717:	learn: 0.0037092	total: 13.3s	remaining: 13.9s
718:	learn: 0.0037025	total: 13.4s	remaining: 13.9s
719:	learn: 0.0037004	total: 13.4s	remaining: 13.9s
720:	learn: 0.0036984	total: 13.4s	remaining: 13.8s
721:	learn: 0.0036958	total: 13.4s	remaining: 13.8s
722:	learn: 0.0036906	total: 13.4s	remaining: 13.8s
723:	learn: 0.0036886	total: 13.4s	remaining: 13.8s
724:	learn: 0.0036876	total: 13.5s	remaining: 13.8s
725:	learn: 0.0036841	total: 13.5s	remaining: 13.7s
726:	learn: 0.0036806	total: 13.5s	remaining: 13.7s
727:	learn: 0.0036781	total: 13.5s	remaining: 13.7s
728:	learn: 0.0036752	total: 13.5s	remaining: 13.7s
729:	learn: 0.0036731	total: 13.5s	remaining: 13.6s
730:	learn: 0.0036682	total: 13.5s	remaining: 13.6s
731:	learn: 0.0036642	total: 13.6s	remaining: 13.6s
732:	learn: 0.0036630	total: 13.6s	remaining: 13.6s
733:	learn: 0.0036585	total: 13.6s	remaining: 13.6s
734:	learn: 0.0036552	total: 13.6s	remaining: 13.5s
735:	learn: 0.0036526	total: 13.6s	remaining: 13.5s
736:	learn: 0.0036507	total: 13.6s	remaining: 13.5s
737:	learn: 0.0036467	total: 13.7s	remaining: 13.5s
738:	learn: 0.0036434	total: 13.7s	remaining: 13.5s
739:	learn: 0.0036400	total: 13.7s	remaining: 13.4s
740:	learn: 0.0036382	total: 13.7s	remaining: 13.4s
741:	learn: 0.0036365	total: 13.7s	remaining: 13.4s
742:	learn: 0.0036337	total: 13.7s	remaining: 13.4s
743:	learn: 0.0036304	total: 13.8s	remaining: 13.4s
744:	learn: 0.0036271	total: 13.8s	remaining: 13.3s
745:	learn: 0.0036241	total: 13.8s	remaining: 13.3s
746:	learn: 0.0036205	total: 13.8s	remaining: 13.3s
747:	learn: 0.0036187	total: 13.8s	remaining: 13.3s
748:	learn: 0.0036134	total: 13.8s	remaining: 13.2s
749:	learn: 0.0036112	total: 13.8s	remaining: 13.2s
750:	learn: 0.0036103	total: 13.9s	remaining: 13.2s
751:	learn: 0.0036057	total: 13.9s	remaining: 13.2s
752:	learn: 0.0036040	total: 13.9s	remaining: 13.2s
753:	learn: 0.0036015	total: 13.9s	remaining: 13.1s
754:	learn: 0.0035987	total: 13.9s	remaining: 13.1s
755:	learn: 0.0035971	total: 13.9s	remaining: 13.1s
756:	learn: 0.0035952	total: 14s	remaining: 13.1s
757:	learn: 0.0035920	total: 14s	remaining: 13s
758:	learn: 0.0035905	total: 14s	remaining: 13s
759:	learn: 0.0035893	total: 14s	remaining: 13s
760:	learn: 0.0035874	total: 14s	remaining: 13s
761:	learn: 0.0035847	total: 14s	remaining: 13s
762:	learn: 0.0035830	total: 14s	remaining: 12.9s
763:	learn: 0.0035800	total: 14.1s	remaining: 12.9s
764:	learn: 0.0035772	total: 14.1s	remaining: 12.9s
765:	learn: 0.0035752	total: 14.1s	remaining: 12.9s
766:	learn: 0.0035716	total: 14.1s	remaining: 12.9s
767:	learn: 0.0035689	total: 14.1s	remaining: 12.8s
768:	learn: 0.0035647	total: 14.1s	remaining: 12.8s
769:	learn: 0.0035625	total: 14.2s	remaining: 12.8s
770:	learn: 0.0035612	total: 14.2s	remaining: 12.8s
771:	learn: 0.0035587	total: 14.2s	remaining: 12.8s
772:	learn: 0.0035557	total: 14.2s	remaining: 12.8s
773:	learn: 0.0035509	total: 14.2s	remaining: 12.7s
774:	learn: 0.0035481	total: 14.3s	remaining: 12.7s
775:	learn: 0.0035458	total: 14.3s	remaining: 12.7s
776:	learn: 0.0035444	total: 14.3s	remaining: 12.7s
777:	learn: 0.0035386	total: 14.3s	remaining: 12.6s
778:	learn: 0.0035369	total: 14.3s	remaining: 12.6s
779:	learn: 0.0035358	total: 14.3s	remaining: 12.6s
780:	learn: 0.0035318	total: 14.3s	remaining: 12.6s
781:	learn: 0.0035297	total: 14.4s	remaining: 12.6s
782:	learn: 0.0035267	total: 14.4s	remaining: 12.6s
783:	learn: 0.0035209	total: 14.4s	remaining: 12.5s
784:	learn: 0.0035197	total: 14.4s	remaining: 12.5s
785:	learn: 0.0035176	total: 14.4s	remaining: 12.5s
786:	learn: 0.0035139	total: 14.4s	remaining: 12.5s
787:	learn: 0.0035123	total: 14.5s	remaining: 12.4s
788:	learn: 0.0035079	total: 14.5s	remaining: 12.4s
789:	learn: 0.0035062	total: 14.5s	remaining: 12.4s
790:	learn: 0.0035031	total: 14.5s	remaining: 12.4s
791:	learn: 0.0035014	total: 14.5s	remaining: 12.4s
792:	learn: 0.0034971	total: 14.5s	remaining: 12.3s
793:	learn: 0.0034932	total: 14.6s	remaining: 12.3s
794:	learn: 0.0034907	total: 14.6s	remaining: 12.3s
795:	learn: 0.0034883	total: 14.6s	remaining: 12.3s
796:	learn: 0.0034835	total: 14.6s	remaining: 12.3s
797:	learn: 0.0034819	total: 14.6s	remaining: 12.2s
798:	learn: 0.0034798	total: 14.6s	remaining: 12.2s
799:	learn: 0.0034768	total: 14.7s	remaining: 12.2s
800:	learn: 0.0034751	total: 14.7s	remaining: 12.2s
801:	learn: 0.0034733	total: 14.7s	remaining: 12.2s
802:	learn: 0.0034700	total: 14.7s	remaining: 12.1s
803:	learn: 0.0034672	total: 14.7s	remaining: 12.1s
804:	learn: 0.0034649	total: 14.7s	remaining: 12.1s
805:	learn: 0.0034631	total: 14.8s	remaining: 12.1s
806:	learn: 0.0034600	total: 14.8s	remaining: 12.1s
807:	learn: 0.0034582	total: 14.8s	remaining: 12s
808:	learn: 0.0034562	total: 14.8s	remaining: 12s
809:	learn: 0.0034543	total: 14.8s	remaining: 12s
810:	learn: 0.0034515	total: 14.8s	remaining: 12s
811:	learn: 0.0034491	total: 14.8s	remaining: 12s
812:	learn: 0.0034454	total: 14.9s	remaining: 11.9s
813:	learn: 0.0034440	total: 14.9s	remaining: 11.9s
814:	learn: 0.0034413	total: 14.9s	remaining: 11.9s
815:	learn: 0.0034388	total: 14.9s	remaining: 11.9s
816:	learn: 0.0034346	total: 14.9s	remaining: 11.9s
817:	learn: 0.0034322	total: 14.9s	remaining: 11.8s
818:	learn: 0.0034312	total: 15s	remaining: 11.8s
819:	learn: 0.0034292	total: 15s	remaining: 11.8s
820:	learn: 0.0034292	total: 15s	remaining: 11.8s
821:	learn: 0.0034269	total: 15s	remaining: 11.8s
822:	learn: 0.0034229	total: 15s	remaining: 11.7s
823:	learn: 0.0034171	total: 15s	remaining: 11.7s
824:	learn: 0.0034149	total: 15s	remaining: 11.7s
825:	learn: 0.0034069	total: 15.1s	remaining: 11.7s
826:	learn: 0.0034030	total: 15.1s	remaining: 11.7s
827:	learn: 0.0033995	total: 15.1s	remaining: 11.6s
828:	learn: 0.0033976	total: 15.1s	remaining: 11.6s
829:	learn: 0.0033951	total: 15.1s	remaining: 11.6s
830:	learn: 0.0033940	total: 15.1s	remaining: 11.6s
831:	learn: 0.0033916	total: 15.2s	remaining: 11.6s
832:	learn: 0.0033879	total: 15.2s	remaining: 11.5s
833:	learn: 0.0033868	total: 15.2s	remaining: 11.5s
834:	learn: 0.0033851	total: 15.2s	remaining: 11.5s
835:	learn: 0.0033833	total: 15.3s	remaining: 11.5s
836:	learn: 0.0033828	total: 15.3s	remaining: 11.5s
837:	learn: 0.0033814	total: 15.3s	remaining: 11.4s
838:	learn: 0.0033794	total: 15.3s	remaining: 11.4s
839:	learn: 0.0033779	total: 15.3s	remaining: 11.4s
840:	learn: 0.0033761	total: 15.3s	remaining: 11.4s
841:	learn: 0.0033738	total: 15.3s	remaining: 11.4s
842:	learn: 0.0033731	total: 15.4s	remaining: 11.3s
843:	learn: 0.0033709	total: 15.4s	remaining: 11.3s
844:	learn: 0.0033680	total: 15.4s	remaining: 11.3s
845:	learn: 0.0033665	total: 15.4s	remaining: 11.3s
846:	learn: 0.0033646	total: 15.4s	remaining: 11.3s
847:	learn: 0.0033617	total: 15.4s	remaining: 11.2s
848:	learn: 0.0033594	total: 15.5s	remaining: 11.2s
849:	learn: 0.0033556	total: 15.5s	remaining: 11.2s
850:	learn: 0.0033539	total: 15.5s	remaining: 11.2s
851:	learn: 0.0033508	total: 15.5s	remaining: 11.2s
852:	learn: 0.0033494	total: 15.5s	remaining: 11.1s
853:	learn: 0.0033481	total: 15.5s	remaining: 11.1s
854:	learn: 0.0033452	total: 15.5s	remaining: 11.1s
855:	learn: 0.0033429	total: 15.6s	remaining: 11.1s
856:	learn: 0.0033412	total: 15.6s	remaining: 11.1s
857:	learn: 0.0033392	total: 15.6s	remaining: 11s
858:	learn: 0.0033366	total: 15.6s	remaining: 11s
859:	learn: 0.0033336	total: 15.6s	remaining: 11s
860:	learn: 0.0033328	total: 15.6s	remaining: 11s
861:	learn: 0.0033314	total: 15.7s	remaining: 11s
862:	learn: 0.0033288	total: 15.7s	remaining: 11s
863:	learn: 0.0033269	total: 15.7s	remaining: 10.9s
864:	learn: 0.0033233	total: 15.7s	remaining: 10.9s
865:	learn: 0.0033207	total: 15.7s	remaining: 10.9s
866:	learn: 0.0033174	total: 15.7s	remaining: 10.9s
867:	learn: 0.0033147	total: 15.7s	remaining: 10.8s
868:	learn: 0.0033135	total: 15.8s	remaining: 10.8s
869:	learn: 0.0033115	total: 15.8s	remaining: 10.8s
870:	learn: 0.0033104	total: 15.8s	remaining: 10.8s
871:	learn: 0.0033075	total: 15.8s	remaining: 10.8s
872:	learn: 0.0033055	total: 15.8s	remaining: 10.7s
873:	learn: 0.0033025	total: 15.8s	remaining: 10.7s
874:	learn: 0.0033015	total: 15.9s	remaining: 10.7s
875:	learn: 0.0032992	total: 15.9s	remaining: 10.7s
876:	learn: 0.0032977	total: 15.9s	remaining: 10.7s
877:	learn: 0.0032948	total: 15.9s	remaining: 10.6s
878:	learn: 0.0032922	total: 15.9s	remaining: 10.6s
879:	learn: 0.0032912	total: 15.9s	remaining: 10.6s
880:	learn: 0.0032883	total: 15.9s	remaining: 10.6s
881:	learn: 0.0032866	total: 16s	remaining: 10.6s
882:	learn: 0.0032841	total: 16s	remaining: 10.6s
883:	learn: 0.0032815	total: 16s	remaining: 10.5s
884:	learn: 0.0032807	total: 16s	remaining: 10.5s
885:	learn: 0.0032783	total: 16s	remaining: 10.5s
886:	learn: 0.0032766	total: 16s	remaining: 10.5s
887:	learn: 0.0032748	total: 16.1s	remaining: 10.5s
888:	learn: 0.0032737	total: 16.1s	remaining: 10.4s
889:	learn: 0.0032716	total: 16.1s	remaining: 10.4s
890:	learn: 0.0032703	total: 16.1s	remaining: 10.4s
891:	learn: 0.0032689	total: 16.1s	remaining: 10.4s
892:	learn: 0.0032686	total: 16.1s	remaining: 10.4s
893:	learn: 0.0032656	total: 16.2s	remaining: 10.3s
894:	learn: 0.0032628	total: 16.2s	remaining: 10.3s
895:	learn: 0.0032601	total: 16.2s	remaining: 10.3s
896:	learn: 0.0032570	total: 16.2s	remaining: 10.3s
897:	learn: 0.0032552	total: 16.2s	remaining: 10.3s
898:	learn: 0.0032522	total: 16.3s	remaining: 10.3s
899:	learn: 0.0032500	total: 16.3s	remaining: 10.2s
900:	learn: 0.0032484	total: 16.3s	remaining: 10.2s
901:	learn: 0.0032471	total: 16.3s	remaining: 10.2s
902:	learn: 0.0032444	total: 16.3s	remaining: 10.2s
903:	learn: 0.0032432	total: 16.3s	remaining: 10.2s
904:	learn: 0.0032418	total: 16.4s	remaining: 10.1s
905:	learn: 0.0032398	total: 16.4s	remaining: 10.1s
906:	learn: 0.0032365	total: 16.4s	remaining: 10.1s
907:	learn: 0.0032346	total: 16.4s	remaining: 10.1s
908:	learn: 0.0032326	total: 16.4s	remaining: 10.1s
909:	learn: 0.0032302	total: 16.4s	remaining: 10s
910:	learn: 0.0032278	total: 16.5s	remaining: 10s
911:	learn: 0.0032241	total: 16.5s	remaining: 10s
912:	learn: 0.0032232	total: 16.5s	remaining: 9.98s
913:	learn: 0.0032211	total: 16.5s	remaining: 9.97s
914:	learn: 0.0032195	total: 16.5s	remaining: 9.95s
915:	learn: 0.0032176	total: 16.5s	remaining: 9.93s
916:	learn: 0.0032166	total: 16.6s	remaining: 9.91s
917:	learn: 0.0032134	total: 16.6s	remaining: 9.89s
918:	learn: 0.0032116	total: 16.6s	remaining: 9.87s
919:	learn: 0.0032101	total: 16.6s	remaining: 9.85s
920:	learn: 0.0032096	total: 16.6s	remaining: 9.83s
921:	learn: 0.0032075	total: 16.6s	remaining: 9.81s
922:	learn: 0.0032054	total: 16.6s	remaining: 9.79s
923:	learn: 0.0032029	total: 16.7s	remaining: 9.77s
924:	learn: 0.0032014	total: 16.7s	remaining: 9.75s
925:	learn: 0.0032004	total: 16.7s	remaining: 9.73s
926:	learn: 0.0031991	total: 16.7s	remaining: 9.71s
927:	learn: 0.0031960	total: 16.7s	remaining: 9.69s
928:	learn: 0.0031946	total: 16.7s	remaining: 9.68s
929:	learn: 0.0031918	total: 16.8s	remaining: 9.66s
930:	learn: 0.0031883	total: 16.8s	remaining: 9.64s
931:	learn: 0.0031865	total: 16.8s	remaining: 9.62s
932:	learn: 0.0031848	total: 16.8s	remaining: 9.6s
933:	learn: 0.0031821	total: 16.8s	remaining: 9.58s
934:	learn: 0.0031814	total: 16.8s	remaining: 9.56s
935:	learn: 0.0031807	total: 16.8s	remaining: 9.54s
936:	learn: 0.0031766	total: 16.9s	remaining: 9.52s
937:	learn: 0.0031747	total: 16.9s	remaining: 9.5s

### Таблицы

In [71]:
df_clas_table1

,Algorithm,Train Accuracy,Train Precision,Train Recall,Train F1,Test Accuracy,Test Precision,Test Recall,Test F1
0,clas_DecisionTreeClassifier,0.96,0.96,0.96,0.96,0.98,0.99,0.98,0.99
1,clas_BaggingClassifier,0.96,0.96,0.96,0.96,0.99,0.99,0.99,0.99
2,GradientBoostingClassifier,1.00,1.00,1.00,1.00,0.98,0.98,0.98,0.98
3,StackingClassifier,1.00,1.00,1.00,1.00,0.98,0.98,0.98,0.98
4,CatBoostClassifier,0.96,0.96,0.96,0.96,0.99,0.99,0.99,0.99
5,XGBoostClassifier,0.89,0.92,0.89,0.90,0.99,0.99,0.99,0.99
6,LightGBMClassifier,0.96,0.96,0.96,0.96,0.99,0.99,0.99,0.99

In [72]:
df_clas_table2

,Algorithm,Hold-out Accuracy,Hold-out Precision,Hold-out Recall,Hold-out F1,K-Fold Accuracy (mean),K-Fold Precision (mean),K-Fold Recall (mean),K-Fold F1 (mean)
0,clas_DecisionTreeClassifier,0.98,0.99,0.98,0.99,1.0,1.0,1.0,1.0
1,clas_BaggingClassifier,0.99,0.99,0.99,0.99,1.0,1.0,1.0,1.0
2,GradientBoostingClassifier,0.98,0.98,0.98,0.98,1.0,1.0,1.0,1.0
3,StackingClassifier,0.98,0.98,0.98,0.98,1.0,1.0,1.0,1.0
4,CatBoostClassifier,0.99,0.99,0.99,0.99,1.0,1.0,1.0,1.0
5,XGBoostClassifier,0.99,0.99,0.99,0.99,1.0,1.0,1.0,1.0
6,LightGBMClassifier,0.99,0.99,0.99,0.99,1.0,1.0,1.0,1.0

# 7. Вывод

**Общие мысли:** деревья решений являются хорошим алгоритмом на уровне баланса скорости и точности, а используя ансамбли моделей и градиентный бустинг можно повысить точность до крайне хороших результатов, однако, необходимо подробно рассмотреть гиперпараметры

**Регрессор:** В результате лабораторной работы был выявлен лучший (наиболее подходящий на моих данных) регрессор - *GradientBoostingRegressor*. Такой вывод следует из анализа метрик каждой модели. Благодаря таблицам явно видно, что этот регрессор обладает наименьшими показателями $RMSE = 525.4151$ и $MAE = 267.6510$ при хорошем показателе $R^2 = 0.98$. <br>
**Однако**, этот классификатор побеждает лишь в точности, в балансе между скоростью и точностью лидирует *XGBoostRegressor* с показателями $RMSE = 533.6009$ и $MAE = 267.9068$ при том же показателе $R^2 = 0.98$

**Классификатор:** В результате лабораторной работы был выявлен так же лучший (наиболее подходящий на моих данных) классификатор - *DecisionTreeClassifier*. Такой вывод следует из анализа метрик каждой модели. Благодаря таблицам явно видно, что метрики всех моделей $Accuracy, Precision, Recall, F1 = 1$ на кросс-валидационной выборке. Из этого можно сделать вывод, что насчёт точности предсказаний модели имеют очень схожий высокий результат, но вот самая быстрая модель - выбранная мной *DecisionTreeClassifier*